package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"hmans.de/chatto/internal/graph/model"
)

// MyServerEvents is the resolver for the myServerEvents field.
//
// Multiplexes the two core streams into a single channel of model.ServerEvent
// wrappers. Each wrapper carries exactly one of the two proto types — Actor
// and Event field resolvers dispatch on whichever is set.
func (r *subscriptionResolver) MyServerEvents(ctx context.Context) (<-chan *model.ServerEvent, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	roomCh, err := r.core.StreamMyServerEvents(ctx, user.Id)
	if err != nil {
		return nil, fmt.Errorf("subscribe room events: %w", err)
	}
	liveCh, err := r.core.StreamMyLiveEvents(ctx, user.Id)
	if err != nil {
		return nil, fmt.Errorf("subscribe live events: %w", err)
	}

	out := make(chan *model.ServerEvent)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case e, ok := <-roomCh:
				if !ok {
					roomCh = nil
					if liveCh == nil {
						return
					}
					continue
				}
				select {
				case out <- &model.ServerEvent{
					Id:        e.Id,
					ActorId:   e.ActorId,
					CreatedAt: e.CreatedAt,
					RoomProto: e,
				}:
				case <-ctx.Done():
					return
				}
			case e, ok := <-liveCh:
				if !ok {
					liveCh = nil
					if roomCh == nil {
						return
					}
					continue
				}
				select {
				case out <- &model.ServerEvent{
					Id:        e.Id,
					ActorId:   e.ActorId,
					CreatedAt: e.CreatedAt,
					LiveProto: e,
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
