# SPDX-FileCopyrightText: 2026 ChattoCorp GmbH
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = "**"
precedence = "override"
SPDX-FileCopyrightText = "2026 ChattoCorp GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "cli/**"
precedence = "override"
SPDX-FileCopyrightText = "2026 ChattoCorp GmbH"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "LICENSE-AGPL"
precedence = "override"
SPDX-FileCopyrightText = "2007 Free Software Foundation, Inc."
SPDX-License-Identifier = "AGPL-3.0-or-later"
