// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/auth/v1/setup.proto

package authv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/auth/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServerSetupServiceName is the fully-qualified name of the ServerSetupService service.
	ServerSetupServiceName = "chatto.auth.v1.ServerSetupService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServerSetupServiceCompleteSetupProcedure is the fully-qualified name of the ServerSetupService's
	// CompleteSetup RPC.
	ServerSetupServiceCompleteSetupProcedure = "/chatto.auth.v1.ServerSetupService/CompleteSetup"
)

// ServerSetupServiceClient is a client for the chatto.auth.v1.ServerSetupService service.
type ServerSetupServiceClient interface {
	// Public while setup is available. Atomically creates the owner and server
	// settings, then permanently closes setup. Concurrent or later submissions
	// fail with FAILED_PRECONDITION. A lost response can be recovered by signing in.
	CompleteSetup(context.Context, *connect.Request[v1.CompleteSetupRequest]) (*connect.Response[v1.CompleteSetupResponse], error)
}

// NewServerSetupServiceClient constructs a client for the chatto.auth.v1.ServerSetupService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServerSetupServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServerSetupServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serverSetupServiceMethods := v1.File_chatto_auth_v1_setup_proto.Services().ByName("ServerSetupService").Methods()
	return &serverSetupServiceClient{
		completeSetup: connect.NewClient[v1.CompleteSetupRequest, v1.CompleteSetupResponse](
			httpClient,
			baseURL+ServerSetupServiceCompleteSetupProcedure,
			connect.WithSchema(serverSetupServiceMethods.ByName("CompleteSetup")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serverSetupServiceClient implements ServerSetupServiceClient.
type serverSetupServiceClient struct {
	completeSetup *connect.Client[v1.CompleteSetupRequest, v1.CompleteSetupResponse]
}

// CompleteSetup calls chatto.auth.v1.ServerSetupService.CompleteSetup.
func (c *serverSetupServiceClient) CompleteSetup(ctx context.Context, req *connect.Request[v1.CompleteSetupRequest]) (*connect.Response[v1.CompleteSetupResponse], error) {
	return c.completeSetup.CallUnary(ctx, req)
}

// ServerSetupServiceHandler is an implementation of the chatto.auth.v1.ServerSetupService service.
type ServerSetupServiceHandler interface {
	// Public while setup is available. Atomically creates the owner and server
	// settings, then permanently closes setup. Concurrent or later submissions
	// fail with FAILED_PRECONDITION. A lost response can be recovered by signing in.
	CompleteSetup(context.Context, *connect.Request[v1.CompleteSetupRequest]) (*connect.Response[v1.CompleteSetupResponse], error)
}

// NewServerSetupServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServerSetupServiceHandler(svc ServerSetupServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serverSetupServiceMethods := v1.File_chatto_auth_v1_setup_proto.Services().ByName("ServerSetupService").Methods()
	serverSetupServiceCompleteSetupHandler := connect.NewUnaryHandler(
		ServerSetupServiceCompleteSetupProcedure,
		svc.CompleteSetup,
		connect.WithSchema(serverSetupServiceMethods.ByName("CompleteSetup")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.auth.v1.ServerSetupService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServerSetupServiceCompleteSetupProcedure:
			serverSetupServiceCompleteSetupHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServerSetupServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServerSetupServiceHandler struct{}

func (UnimplementedServerSetupServiceHandler) CompleteSetup(context.Context, *connect.Request[v1.CompleteSetupRequest]) (*connect.Response[v1.CompleteSetupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.auth.v1.ServerSetupService.CompleteSetup is not implemented"))
}
