// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/admin/v1/server.proto

package adminv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/admin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminServerServiceName is the fully-qualified name of the AdminServerService service.
	AdminServerServiceName = "chatto.admin.v1.AdminServerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminServerServiceGetServerConfigProcedure is the fully-qualified name of the
	// AdminServerService's GetServerConfig RPC.
	AdminServerServiceGetServerConfigProcedure = "/chatto.admin.v1.AdminServerService/GetServerConfig"
	// AdminServerServiceUpdateServerConfigProcedure is the fully-qualified name of the
	// AdminServerService's UpdateServerConfig RPC.
	AdminServerServiceUpdateServerConfigProcedure = "/chatto.admin.v1.AdminServerService/UpdateServerConfig"
	// AdminServerServiceUploadServerLogoProcedure is the fully-qualified name of the
	// AdminServerService's UploadServerLogo RPC.
	AdminServerServiceUploadServerLogoProcedure = "/chatto.admin.v1.AdminServerService/UploadServerLogo"
	// AdminServerServiceDeleteServerLogoProcedure is the fully-qualified name of the
	// AdminServerService's DeleteServerLogo RPC.
	AdminServerServiceDeleteServerLogoProcedure = "/chatto.admin.v1.AdminServerService/DeleteServerLogo"
	// AdminServerServiceUploadServerBannerProcedure is the fully-qualified name of the
	// AdminServerService's UploadServerBanner RPC.
	AdminServerServiceUploadServerBannerProcedure = "/chatto.admin.v1.AdminServerService/UploadServerBanner"
	// AdminServerServiceDeleteServerBannerProcedure is the fully-qualified name of the
	// AdminServerService's DeleteServerBanner RPC.
	AdminServerServiceDeleteServerBannerProcedure = "/chatto.admin.v1.AdminServerService/DeleteServerBanner"
	// AdminServerServiceGetServerSecurityConfigProcedure is the fully-qualified name of the
	// AdminServerService's GetServerSecurityConfig RPC.
	AdminServerServiceGetServerSecurityConfigProcedure = "/chatto.admin.v1.AdminServerService/GetServerSecurityConfig"
	// AdminServerServiceUpdateBlockedUsernamesProcedure is the fully-qualified name of the
	// AdminServerService's UpdateBlockedUsernames RPC.
	AdminServerServiceUpdateBlockedUsernamesProcedure = "/chatto.admin.v1.AdminServerService/UpdateBlockedUsernames"
	// AdminServerServiceListNeighborsProcedure is the fully-qualified name of the AdminServerService's
	// ListNeighbors RPC.
	AdminServerServiceListNeighborsProcedure = "/chatto.admin.v1.AdminServerService/ListNeighbors"
	// AdminServerServiceGetNeighborProcedure is the fully-qualified name of the AdminServerService's
	// GetNeighbor RPC.
	AdminServerServiceGetNeighborProcedure = "/chatto.admin.v1.AdminServerService/GetNeighbor"
	// AdminServerServiceCreateNeighborProcedure is the fully-qualified name of the AdminServerService's
	// CreateNeighbor RPC.
	AdminServerServiceCreateNeighborProcedure = "/chatto.admin.v1.AdminServerService/CreateNeighbor"
	// AdminServerServiceUpdateNeighborProcedure is the fully-qualified name of the AdminServerService's
	// UpdateNeighbor RPC.
	AdminServerServiceUpdateNeighborProcedure = "/chatto.admin.v1.AdminServerService/UpdateNeighbor"
	// AdminServerServiceDeleteNeighborProcedure is the fully-qualified name of the AdminServerService's
	// DeleteNeighbor RPC.
	AdminServerServiceDeleteNeighborProcedure = "/chatto.admin.v1.AdminServerService/DeleteNeighbor"
)

// AdminServerServiceClient is a client for the chatto.admin.v1.AdminServerService service.
type AdminServerServiceClient interface {
	// Gets runtime-editable server profile settings. This RPC requires
	// server.manage.
	GetServerConfig(context.Context, *connect.Request[v1.GetServerConfigRequest]) (*connect.Response[v1.GetServerConfigResponse], error)
	// Updates runtime-editable server profile settings. This RPC requires
	// server.manage.
	UpdateServerConfig(context.Context, *connect.Request[v1.UpdateServerConfigRequest]) (*connect.Response[v1.UpdateServerConfigResponse], error)
	// Uploads and sets the public server logo. This RPC requires server.manage.
	UploadServerLogo(context.Context, *connect.Request[v1.UploadServerLogoRequest]) (*connect.Response[v1.UploadServerLogoResponse], error)
	// Clears the public server logo. This RPC requires server.manage.
	DeleteServerLogo(context.Context, *connect.Request[v1.DeleteServerLogoRequest]) (*connect.Response[v1.DeleteServerLogoResponse], error)
	// Uploads and sets the public server banner. This RPC requires server.manage.
	UploadServerBanner(context.Context, *connect.Request[v1.UploadServerBannerRequest]) (*connect.Response[v1.UploadServerBannerResponse], error)
	// Clears the public server banner. This RPC requires server.manage.
	DeleteServerBanner(context.Context, *connect.Request[v1.DeleteServerBannerRequest]) (*connect.Response[v1.DeleteServerBannerResponse], error)
	// Returns security-sensitive server configuration. This RPC requires
	// server.manage.
	GetServerSecurityConfig(context.Context, *connect.Request[v1.GetServerSecurityConfigRequest]) (*connect.Response[v1.GetServerSecurityConfigResponse], error)
	// Updates the blocked-username list. This RPC requires server.manage.
	UpdateBlockedUsernames(context.Context, *connect.Request[v1.UpdateBlockedUsernamesRequest]) (*connect.Response[v1.UpdateBlockedUsernamesResponse], error)
	// Lists configured Neighbors. This RPC requires server.manage-neighbors.
	ListNeighbors(context.Context, *connect.Request[v1.ListNeighborsRequest]) (*connect.Response[v1.ListNeighborsResponse], error)
	// Gets one configured Neighbor. This RPC requires server.manage-neighbors.
	GetNeighbor(context.Context, *connect.Request[v1.GetNeighborRequest]) (*connect.Response[v1.GetNeighborResponse], error)
	// Advertises one server origin. The origin must not identify this server.
	// This RPC requires server.manage-neighbors.
	CreateNeighbor(context.Context, *connect.Request[v1.CreateNeighborRequest]) (*connect.Response[v1.CreateNeighborResponse], error)
	// Changes one advertised server origin. The new origin must not identify
	// this server. This RPC requires server.manage-neighbors.
	UpdateNeighbor(context.Context, *connect.Request[v1.UpdateNeighborRequest]) (*connect.Response[v1.UpdateNeighborResponse], error)
	// Stops advertising one server origin. This RPC requires
	// server.manage-neighbors.
	DeleteNeighbor(context.Context, *connect.Request[v1.DeleteNeighborRequest]) (*connect.Response[v1.DeleteNeighborResponse], error)
}

// NewAdminServerServiceClient constructs a client for the chatto.admin.v1.AdminServerService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminServerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminServerServiceMethods := v1.File_chatto_admin_v1_server_proto.Services().ByName("AdminServerService").Methods()
	return &adminServerServiceClient{
		getServerConfig: connect.NewClient[v1.GetServerConfigRequest, v1.GetServerConfigResponse](
			httpClient,
			baseURL+AdminServerServiceGetServerConfigProcedure,
			connect.WithSchema(adminServerServiceMethods.ByName("GetServerConfig")),
			connect.WithClientOptions(opts...),
		),
		updateServerConfig: connect.NewClient[v1.UpdateServerConfigRequest, v1.UpdateServerConfigResponse](
			httpClient,
			baseURL+AdminServerServiceUpdateServerConfigProcedure,
			connect.WithSchema(adminServerServiceMethods.ByName("UpdateServerConfig")),
			connect.WithClientOptions(opts...),
		),
		uploadServerLogo: connect.NewClient[v1.UploadServerLogoRequest, v1.UploadServerLogoResponse](
			httpClient,
			baseURL+AdminServerServiceUploadServerLogoProcedure,
			connect.WithSchema(adminServerServiceMethods.ByName("UploadServerLogo")),
			connect.WithClientOptions(opts...),
		),
		deleteServerLogo: connect.NewClient[v1.DeleteServerLogoRequest, v1.DeleteServerLogoResponse](
			httpClient,
			baseURL+AdminServerServiceDeleteServerLogoProcedure,
			connect.WithSchema(adminServerServiceMethods.ByName("DeleteServerLogo")),
			connect.WithClientOptions(opts...),
		),
		uploadServerBanner: connect.NewClient[v1.UploadServerBannerRequest, v1.UploadServerBannerResponse](
			httpClient,
			baseURL+AdminServerServiceUploadServerBannerProcedure,
			connect.WithSchema(adminServerServiceMethods.ByName("UploadServerBanner")),
			connect.WithClientOptions(opts...),
		),
		deleteServerBanner: connect.NewClient[v1.DeleteServerBannerRequest, v1.DeleteServerBannerResponse](
			httpClient,
			baseURL+AdminServerServiceDeleteServerBannerProcedure,
			connect.WithSchema(adminServerServiceMethods.ByName("DeleteServerBanner")),
			connect.WithClientOptions(opts...),
		),
		getServerSecurityConfig: connect.NewClient[v1.GetServerSecurityConfigRequest, v1.GetServerSecurityConfigResponse](
			httpClient,
			baseURL+AdminServerServiceGetServerSecurityConfigProcedure,
			connect.WithSchema(adminServerServiceMethods.ByName("GetServerSecurityConfig")),
			connect.WithClientOptions(opts...),
		),
		updateBlockedUsernames: connect.NewClient[v1.UpdateBlockedUsernamesRequest, v1.UpdateBlockedUsernamesResponse](
			httpClient,
			baseURL+AdminServerServiceUpdateBlockedUsernamesProcedure,
			connect.WithSchema(adminServerServiceMethods.ByName("UpdateBlockedUsernames")),
			connect.WithClientOptions(opts...),
		),
		listNeighbors: connect.NewClient[v1.ListNeighborsRequest, v1.ListNeighborsResponse](
			httpClient,
			baseURL+AdminServerServiceListNeighborsProcedure,
			connect.WithSchema(adminServerServiceMethods.ByName("ListNeighbors")),
			connect.WithClientOptions(opts...),
		),
		getNeighbor: connect.NewClient[v1.GetNeighborRequest, v1.GetNeighborResponse](
			httpClient,
			baseURL+AdminServerServiceGetNeighborProcedure,
			connect.WithSchema(adminServerServiceMethods.ByName("GetNeighbor")),
			connect.WithClientOptions(opts...),
		),
		createNeighbor: connect.NewClient[v1.CreateNeighborRequest, v1.CreateNeighborResponse](
			httpClient,
			baseURL+AdminServerServiceCreateNeighborProcedure,
			connect.WithSchema(adminServerServiceMethods.ByName("CreateNeighbor")),
			connect.WithClientOptions(opts...),
		),
		updateNeighbor: connect.NewClient[v1.UpdateNeighborRequest, v1.UpdateNeighborResponse](
			httpClient,
			baseURL+AdminServerServiceUpdateNeighborProcedure,
			connect.WithSchema(adminServerServiceMethods.ByName("UpdateNeighbor")),
			connect.WithClientOptions(opts...),
		),
		deleteNeighbor: connect.NewClient[v1.DeleteNeighborRequest, v1.DeleteNeighborResponse](
			httpClient,
			baseURL+AdminServerServiceDeleteNeighborProcedure,
			connect.WithSchema(adminServerServiceMethods.ByName("DeleteNeighbor")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminServerServiceClient implements AdminServerServiceClient.
type adminServerServiceClient struct {
	getServerConfig         *connect.Client[v1.GetServerConfigRequest, v1.GetServerConfigResponse]
	updateServerConfig      *connect.Client[v1.UpdateServerConfigRequest, v1.UpdateServerConfigResponse]
	uploadServerLogo        *connect.Client[v1.UploadServerLogoRequest, v1.UploadServerLogoResponse]
	deleteServerLogo        *connect.Client[v1.DeleteServerLogoRequest, v1.DeleteServerLogoResponse]
	uploadServerBanner      *connect.Client[v1.UploadServerBannerRequest, v1.UploadServerBannerResponse]
	deleteServerBanner      *connect.Client[v1.DeleteServerBannerRequest, v1.DeleteServerBannerResponse]
	getServerSecurityConfig *connect.Client[v1.GetServerSecurityConfigRequest, v1.GetServerSecurityConfigResponse]
	updateBlockedUsernames  *connect.Client[v1.UpdateBlockedUsernamesRequest, v1.UpdateBlockedUsernamesResponse]
	listNeighbors           *connect.Client[v1.ListNeighborsRequest, v1.ListNeighborsResponse]
	getNeighbor             *connect.Client[v1.GetNeighborRequest, v1.GetNeighborResponse]
	createNeighbor          *connect.Client[v1.CreateNeighborRequest, v1.CreateNeighborResponse]
	updateNeighbor          *connect.Client[v1.UpdateNeighborRequest, v1.UpdateNeighborResponse]
	deleteNeighbor          *connect.Client[v1.DeleteNeighborRequest, v1.DeleteNeighborResponse]
}

// GetServerConfig calls chatto.admin.v1.AdminServerService.GetServerConfig.
func (c *adminServerServiceClient) GetServerConfig(ctx context.Context, req *connect.Request[v1.GetServerConfigRequest]) (*connect.Response[v1.GetServerConfigResponse], error) {
	return c.getServerConfig.CallUnary(ctx, req)
}

// UpdateServerConfig calls chatto.admin.v1.AdminServerService.UpdateServerConfig.
func (c *adminServerServiceClient) UpdateServerConfig(ctx context.Context, req *connect.Request[v1.UpdateServerConfigRequest]) (*connect.Response[v1.UpdateServerConfigResponse], error) {
	return c.updateServerConfig.CallUnary(ctx, req)
}

// UploadServerLogo calls chatto.admin.v1.AdminServerService.UploadServerLogo.
func (c *adminServerServiceClient) UploadServerLogo(ctx context.Context, req *connect.Request[v1.UploadServerLogoRequest]) (*connect.Response[v1.UploadServerLogoResponse], error) {
	return c.uploadServerLogo.CallUnary(ctx, req)
}

// DeleteServerLogo calls chatto.admin.v1.AdminServerService.DeleteServerLogo.
func (c *adminServerServiceClient) DeleteServerLogo(ctx context.Context, req *connect.Request[v1.DeleteServerLogoRequest]) (*connect.Response[v1.DeleteServerLogoResponse], error) {
	return c.deleteServerLogo.CallUnary(ctx, req)
}

// UploadServerBanner calls chatto.admin.v1.AdminServerService.UploadServerBanner.
func (c *adminServerServiceClient) UploadServerBanner(ctx context.Context, req *connect.Request[v1.UploadServerBannerRequest]) (*connect.Response[v1.UploadServerBannerResponse], error) {
	return c.uploadServerBanner.CallUnary(ctx, req)
}

// DeleteServerBanner calls chatto.admin.v1.AdminServerService.DeleteServerBanner.
func (c *adminServerServiceClient) DeleteServerBanner(ctx context.Context, req *connect.Request[v1.DeleteServerBannerRequest]) (*connect.Response[v1.DeleteServerBannerResponse], error) {
	return c.deleteServerBanner.CallUnary(ctx, req)
}

// GetServerSecurityConfig calls chatto.admin.v1.AdminServerService.GetServerSecurityConfig.
func (c *adminServerServiceClient) GetServerSecurityConfig(ctx context.Context, req *connect.Request[v1.GetServerSecurityConfigRequest]) (*connect.Response[v1.GetServerSecurityConfigResponse], error) {
	return c.getServerSecurityConfig.CallUnary(ctx, req)
}

// UpdateBlockedUsernames calls chatto.admin.v1.AdminServerService.UpdateBlockedUsernames.
func (c *adminServerServiceClient) UpdateBlockedUsernames(ctx context.Context, req *connect.Request[v1.UpdateBlockedUsernamesRequest]) (*connect.Response[v1.UpdateBlockedUsernamesResponse], error) {
	return c.updateBlockedUsernames.CallUnary(ctx, req)
}

// ListNeighbors calls chatto.admin.v1.AdminServerService.ListNeighbors.
func (c *adminServerServiceClient) ListNeighbors(ctx context.Context, req *connect.Request[v1.ListNeighborsRequest]) (*connect.Response[v1.ListNeighborsResponse], error) {
	return c.listNeighbors.CallUnary(ctx, req)
}

// GetNeighbor calls chatto.admin.v1.AdminServerService.GetNeighbor.
func (c *adminServerServiceClient) GetNeighbor(ctx context.Context, req *connect.Request[v1.GetNeighborRequest]) (*connect.Response[v1.GetNeighborResponse], error) {
	return c.getNeighbor.CallUnary(ctx, req)
}

// CreateNeighbor calls chatto.admin.v1.AdminServerService.CreateNeighbor.
func (c *adminServerServiceClient) CreateNeighbor(ctx context.Context, req *connect.Request[v1.CreateNeighborRequest]) (*connect.Response[v1.CreateNeighborResponse], error) {
	return c.createNeighbor.CallUnary(ctx, req)
}

// UpdateNeighbor calls chatto.admin.v1.AdminServerService.UpdateNeighbor.
func (c *adminServerServiceClient) UpdateNeighbor(ctx context.Context, req *connect.Request[v1.UpdateNeighborRequest]) (*connect.Response[v1.UpdateNeighborResponse], error) {
	return c.updateNeighbor.CallUnary(ctx, req)
}

// DeleteNeighbor calls chatto.admin.v1.AdminServerService.DeleteNeighbor.
func (c *adminServerServiceClient) DeleteNeighbor(ctx context.Context, req *connect.Request[v1.DeleteNeighborRequest]) (*connect.Response[v1.DeleteNeighborResponse], error) {
	return c.deleteNeighbor.CallUnary(ctx, req)
}

// AdminServerServiceHandler is an implementation of the chatto.admin.v1.AdminServerService service.
type AdminServerServiceHandler interface {
	// Gets runtime-editable server profile settings. This RPC requires
	// server.manage.
	GetServerConfig(context.Context, *connect.Request[v1.GetServerConfigRequest]) (*connect.Response[v1.GetServerConfigResponse], error)
	// Updates runtime-editable server profile settings. This RPC requires
	// server.manage.
	UpdateServerConfig(context.Context, *connect.Request[v1.UpdateServerConfigRequest]) (*connect.Response[v1.UpdateServerConfigResponse], error)
	// Uploads and sets the public server logo. This RPC requires server.manage.
	UploadServerLogo(context.Context, *connect.Request[v1.UploadServerLogoRequest]) (*connect.Response[v1.UploadServerLogoResponse], error)
	// Clears the public server logo. This RPC requires server.manage.
	DeleteServerLogo(context.Context, *connect.Request[v1.DeleteServerLogoRequest]) (*connect.Response[v1.DeleteServerLogoResponse], error)
	// Uploads and sets the public server banner. This RPC requires server.manage.
	UploadServerBanner(context.Context, *connect.Request[v1.UploadServerBannerRequest]) (*connect.Response[v1.UploadServerBannerResponse], error)
	// Clears the public server banner. This RPC requires server.manage.
	DeleteServerBanner(context.Context, *connect.Request[v1.DeleteServerBannerRequest]) (*connect.Response[v1.DeleteServerBannerResponse], error)
	// Returns security-sensitive server configuration. This RPC requires
	// server.manage.
	GetServerSecurityConfig(context.Context, *connect.Request[v1.GetServerSecurityConfigRequest]) (*connect.Response[v1.GetServerSecurityConfigResponse], error)
	// Updates the blocked-username list. This RPC requires server.manage.
	UpdateBlockedUsernames(context.Context, *connect.Request[v1.UpdateBlockedUsernamesRequest]) (*connect.Response[v1.UpdateBlockedUsernamesResponse], error)
	// Lists configured Neighbors. This RPC requires server.manage-neighbors.
	ListNeighbors(context.Context, *connect.Request[v1.ListNeighborsRequest]) (*connect.Response[v1.ListNeighborsResponse], error)
	// Gets one configured Neighbor. This RPC requires server.manage-neighbors.
	GetNeighbor(context.Context, *connect.Request[v1.GetNeighborRequest]) (*connect.Response[v1.GetNeighborResponse], error)
	// Advertises one server origin. The origin must not identify this server.
	// This RPC requires server.manage-neighbors.
	CreateNeighbor(context.Context, *connect.Request[v1.CreateNeighborRequest]) (*connect.Response[v1.CreateNeighborResponse], error)
	// Changes one advertised server origin. The new origin must not identify
	// this server. This RPC requires server.manage-neighbors.
	UpdateNeighbor(context.Context, *connect.Request[v1.UpdateNeighborRequest]) (*connect.Response[v1.UpdateNeighborResponse], error)
	// Stops advertising one server origin. This RPC requires
	// server.manage-neighbors.
	DeleteNeighbor(context.Context, *connect.Request[v1.DeleteNeighborRequest]) (*connect.Response[v1.DeleteNeighborResponse], error)
}

// NewAdminServerServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServerServiceHandler(svc AdminServerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminServerServiceMethods := v1.File_chatto_admin_v1_server_proto.Services().ByName("AdminServerService").Methods()
	adminServerServiceGetServerConfigHandler := connect.NewUnaryHandler(
		AdminServerServiceGetServerConfigProcedure,
		svc.GetServerConfig,
		connect.WithSchema(adminServerServiceMethods.ByName("GetServerConfig")),
		connect.WithHandlerOptions(opts...),
	)
	adminServerServiceUpdateServerConfigHandler := connect.NewUnaryHandler(
		AdminServerServiceUpdateServerConfigProcedure,
		svc.UpdateServerConfig,
		connect.WithSchema(adminServerServiceMethods.ByName("UpdateServerConfig")),
		connect.WithHandlerOptions(opts...),
	)
	adminServerServiceUploadServerLogoHandler := connect.NewUnaryHandler(
		AdminServerServiceUploadServerLogoProcedure,
		svc.UploadServerLogo,
		connect.WithSchema(adminServerServiceMethods.ByName("UploadServerLogo")),
		connect.WithHandlerOptions(opts...),
	)
	adminServerServiceDeleteServerLogoHandler := connect.NewUnaryHandler(
		AdminServerServiceDeleteServerLogoProcedure,
		svc.DeleteServerLogo,
		connect.WithSchema(adminServerServiceMethods.ByName("DeleteServerLogo")),
		connect.WithHandlerOptions(opts...),
	)
	adminServerServiceUploadServerBannerHandler := connect.NewUnaryHandler(
		AdminServerServiceUploadServerBannerProcedure,
		svc.UploadServerBanner,
		connect.WithSchema(adminServerServiceMethods.ByName("UploadServerBanner")),
		connect.WithHandlerOptions(opts...),
	)
	adminServerServiceDeleteServerBannerHandler := connect.NewUnaryHandler(
		AdminServerServiceDeleteServerBannerProcedure,
		svc.DeleteServerBanner,
		connect.WithSchema(adminServerServiceMethods.ByName("DeleteServerBanner")),
		connect.WithHandlerOptions(opts...),
	)
	adminServerServiceGetServerSecurityConfigHandler := connect.NewUnaryHandler(
		AdminServerServiceGetServerSecurityConfigProcedure,
		svc.GetServerSecurityConfig,
		connect.WithSchema(adminServerServiceMethods.ByName("GetServerSecurityConfig")),
		connect.WithHandlerOptions(opts...),
	)
	adminServerServiceUpdateBlockedUsernamesHandler := connect.NewUnaryHandler(
		AdminServerServiceUpdateBlockedUsernamesProcedure,
		svc.UpdateBlockedUsernames,
		connect.WithSchema(adminServerServiceMethods.ByName("UpdateBlockedUsernames")),
		connect.WithHandlerOptions(opts...),
	)
	adminServerServiceListNeighborsHandler := connect.NewUnaryHandler(
		AdminServerServiceListNeighborsProcedure,
		svc.ListNeighbors,
		connect.WithSchema(adminServerServiceMethods.ByName("ListNeighbors")),
		connect.WithHandlerOptions(opts...),
	)
	adminServerServiceGetNeighborHandler := connect.NewUnaryHandler(
		AdminServerServiceGetNeighborProcedure,
		svc.GetNeighbor,
		connect.WithSchema(adminServerServiceMethods.ByName("GetNeighbor")),
		connect.WithHandlerOptions(opts...),
	)
	adminServerServiceCreateNeighborHandler := connect.NewUnaryHandler(
		AdminServerServiceCreateNeighborProcedure,
		svc.CreateNeighbor,
		connect.WithSchema(adminServerServiceMethods.ByName("CreateNeighbor")),
		connect.WithHandlerOptions(opts...),
	)
	adminServerServiceUpdateNeighborHandler := connect.NewUnaryHandler(
		AdminServerServiceUpdateNeighborProcedure,
		svc.UpdateNeighbor,
		connect.WithSchema(adminServerServiceMethods.ByName("UpdateNeighbor")),
		connect.WithHandlerOptions(opts...),
	)
	adminServerServiceDeleteNeighborHandler := connect.NewUnaryHandler(
		AdminServerServiceDeleteNeighborProcedure,
		svc.DeleteNeighbor,
		connect.WithSchema(adminServerServiceMethods.ByName("DeleteNeighbor")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.admin.v1.AdminServerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServerServiceGetServerConfigProcedure:
			adminServerServiceGetServerConfigHandler.ServeHTTP(w, r)
		case AdminServerServiceUpdateServerConfigProcedure:
			adminServerServiceUpdateServerConfigHandler.ServeHTTP(w, r)
		case AdminServerServiceUploadServerLogoProcedure:
			adminServerServiceUploadServerLogoHandler.ServeHTTP(w, r)
		case AdminServerServiceDeleteServerLogoProcedure:
			adminServerServiceDeleteServerLogoHandler.ServeHTTP(w, r)
		case AdminServerServiceUploadServerBannerProcedure:
			adminServerServiceUploadServerBannerHandler.ServeHTTP(w, r)
		case AdminServerServiceDeleteServerBannerProcedure:
			adminServerServiceDeleteServerBannerHandler.ServeHTTP(w, r)
		case AdminServerServiceGetServerSecurityConfigProcedure:
			adminServerServiceGetServerSecurityConfigHandler.ServeHTTP(w, r)
		case AdminServerServiceUpdateBlockedUsernamesProcedure:
			adminServerServiceUpdateBlockedUsernamesHandler.ServeHTTP(w, r)
		case AdminServerServiceListNeighborsProcedure:
			adminServerServiceListNeighborsHandler.ServeHTTP(w, r)
		case AdminServerServiceGetNeighborProcedure:
			adminServerServiceGetNeighborHandler.ServeHTTP(w, r)
		case AdminServerServiceCreateNeighborProcedure:
			adminServerServiceCreateNeighborHandler.ServeHTTP(w, r)
		case AdminServerServiceUpdateNeighborProcedure:
			adminServerServiceUpdateNeighborHandler.ServeHTTP(w, r)
		case AdminServerServiceDeleteNeighborProcedure:
			adminServerServiceDeleteNeighborHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServerServiceHandler struct{}

func (UnimplementedAdminServerServiceHandler) GetServerConfig(context.Context, *connect.Request[v1.GetServerConfigRequest]) (*connect.Response[v1.GetServerConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminServerService.GetServerConfig is not implemented"))
}

func (UnimplementedAdminServerServiceHandler) UpdateServerConfig(context.Context, *connect.Request[v1.UpdateServerConfigRequest]) (*connect.Response[v1.UpdateServerConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminServerService.UpdateServerConfig is not implemented"))
}

func (UnimplementedAdminServerServiceHandler) UploadServerLogo(context.Context, *connect.Request[v1.UploadServerLogoRequest]) (*connect.Response[v1.UploadServerLogoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminServerService.UploadServerLogo is not implemented"))
}

func (UnimplementedAdminServerServiceHandler) DeleteServerLogo(context.Context, *connect.Request[v1.DeleteServerLogoRequest]) (*connect.Response[v1.DeleteServerLogoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminServerService.DeleteServerLogo is not implemented"))
}

func (UnimplementedAdminServerServiceHandler) UploadServerBanner(context.Context, *connect.Request[v1.UploadServerBannerRequest]) (*connect.Response[v1.UploadServerBannerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminServerService.UploadServerBanner is not implemented"))
}

func (UnimplementedAdminServerServiceHandler) DeleteServerBanner(context.Context, *connect.Request[v1.DeleteServerBannerRequest]) (*connect.Response[v1.DeleteServerBannerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminServerService.DeleteServerBanner is not implemented"))
}

func (UnimplementedAdminServerServiceHandler) GetServerSecurityConfig(context.Context, *connect.Request[v1.GetServerSecurityConfigRequest]) (*connect.Response[v1.GetServerSecurityConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminServerService.GetServerSecurityConfig is not implemented"))
}

func (UnimplementedAdminServerServiceHandler) UpdateBlockedUsernames(context.Context, *connect.Request[v1.UpdateBlockedUsernamesRequest]) (*connect.Response[v1.UpdateBlockedUsernamesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminServerService.UpdateBlockedUsernames is not implemented"))
}

func (UnimplementedAdminServerServiceHandler) ListNeighbors(context.Context, *connect.Request[v1.ListNeighborsRequest]) (*connect.Response[v1.ListNeighborsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminServerService.ListNeighbors is not implemented"))
}

func (UnimplementedAdminServerServiceHandler) GetNeighbor(context.Context, *connect.Request[v1.GetNeighborRequest]) (*connect.Response[v1.GetNeighborResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminServerService.GetNeighbor is not implemented"))
}

func (UnimplementedAdminServerServiceHandler) CreateNeighbor(context.Context, *connect.Request[v1.CreateNeighborRequest]) (*connect.Response[v1.CreateNeighborResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminServerService.CreateNeighbor is not implemented"))
}

func (UnimplementedAdminServerServiceHandler) UpdateNeighbor(context.Context, *connect.Request[v1.UpdateNeighborRequest]) (*connect.Response[v1.UpdateNeighborResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminServerService.UpdateNeighbor is not implemented"))
}

func (UnimplementedAdminServerServiceHandler) DeleteNeighbor(context.Context, *connect.Request[v1.DeleteNeighborRequest]) (*connect.Response[v1.DeleteNeighborResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminServerService.DeleteNeighbor is not implemented"))
}
