// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/live/v1/live_events.proto

package livev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TimeFormat is the transient preference value used by live synchronization.
// Durable preference facts use the independent EVT enum.
type TimeFormat int32

const (
	TimeFormat_TIME_FORMAT_UNSPECIFIED TimeFormat = 0
	TimeFormat_TIME_FORMAT_12H         TimeFormat = 1
	TimeFormat_TIME_FORMAT_24H         TimeFormat = 2
)

// Enum value maps for TimeFormat.
var (
	TimeFormat_name = map[int32]string{
		0: "TIME_FORMAT_UNSPECIFIED",
		1: "TIME_FORMAT_12H",
		2: "TIME_FORMAT_24H",
	}
	TimeFormat_value = map[string]int32{
		"TIME_FORMAT_UNSPECIFIED": 0,
		"TIME_FORMAT_12H":         1,
		"TIME_FORMAT_24H":         2,
	}
)

func (x TimeFormat) Enum() *TimeFormat {
	p := new(TimeFormat)
	*p = x
	return p
}

func (x TimeFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_core_live_v1_live_events_proto_enumTypes[0].Descriptor()
}

func (TimeFormat) Type() protoreflect.EnumType {
	return &file_chatto_core_live_v1_live_events_proto_enumTypes[0]
}

func (x TimeFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeFormat.Descriptor instead.
func (TimeFormat) EnumDescriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{0}
}

// CallParticipantEventSource describes the source of a transient call
// participant update.
type CallParticipantEventSource int32

const (
	CallParticipantEventSource_CALL_PARTICIPANT_EVENT_SOURCE_UNSPECIFIED    CallParticipantEventSource = 0
	CallParticipantEventSource_CALL_PARTICIPANT_EVENT_SOURCE_USER           CallParticipantEventSource = 1
	CallParticipantEventSource_CALL_PARTICIPANT_EVENT_SOURCE_LIVEKIT        CallParticipantEventSource = 2
	CallParticipantEventSource_CALL_PARTICIPANT_EVENT_SOURCE_RECONCILIATION CallParticipantEventSource = 3
)

// Enum value maps for CallParticipantEventSource.
var (
	CallParticipantEventSource_name = map[int32]string{
		0: "CALL_PARTICIPANT_EVENT_SOURCE_UNSPECIFIED",
		1: "CALL_PARTICIPANT_EVENT_SOURCE_USER",
		2: "CALL_PARTICIPANT_EVENT_SOURCE_LIVEKIT",
		3: "CALL_PARTICIPANT_EVENT_SOURCE_RECONCILIATION",
	}
	CallParticipantEventSource_value = map[string]int32{
		"CALL_PARTICIPANT_EVENT_SOURCE_UNSPECIFIED":    0,
		"CALL_PARTICIPANT_EVENT_SOURCE_USER":           1,
		"CALL_PARTICIPANT_EVENT_SOURCE_LIVEKIT":        2,
		"CALL_PARTICIPANT_EVENT_SOURCE_RECONCILIATION": 3,
	}
)

func (x CallParticipantEventSource) Enum() *CallParticipantEventSource {
	p := new(CallParticipantEventSource)
	*p = x
	return p
}

func (x CallParticipantEventSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallParticipantEventSource) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_core_live_v1_live_events_proto_enumTypes[1].Descriptor()
}

func (CallParticipantEventSource) Type() protoreflect.EnumType {
	return &file_chatto_core_live_v1_live_events_proto_enumTypes[1]
}

func (x CallParticipantEventSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallParticipantEventSource.Descriptor instead.
func (CallParticipantEventSource) EnumDescriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{1}
}

// LiveEvent is the wire-format envelope for transient pubsub signals.
// These events are never stored in EVT and are not projection input. They
// are delivered over the live.sync.> subject family and adapted by myEvents
// into public realtime events.
//
// Durable facts belong in Event on the EVT stream. Do not add new transient
// variants to Event.
type LiveEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Universal event identifier (NanoID) for dedupe and client-side idempotency.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// When this live signal was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// ID of the user or system actor that triggered this signal.
	ActorId string `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*LiveEvent_UserCreated
	//	*LiveEvent_UserProfileUpdated
	//	*LiveEvent_ServerUserPreferencesUpdated
	//	*LiveEvent_ThreadFollowChanged
	//	*LiveEvent_ServerMemberDeleted
	//	*LiveEvent_ServerUpdated
	//	*LiveEvent_UserTyping
	//	*LiveEvent_PresenceChanged
	//	*LiveEvent_CallParticipantJoined
	//	*LiveEvent_CallParticipantLeft
	//	*LiveEvent_NotificationOccurrencesInvalidated
	//	*LiveEvent_NotificationUnreadChanged
	//	*LiveEvent_RoomMarkedAsRead
	//	*LiveEvent_MentionStatusCleared
	//	*LiveEvent_RoomGroupsUpdated
	//	*LiveEvent_SessionTerminated
	Event         isLiveEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveEvent) Reset() {
	*x = LiveEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveEvent) ProtoMessage() {}

func (x *LiveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveEvent.ProtoReflect.Descriptor instead.
func (*LiveEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{0}
}

func (x *LiveEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LiveEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LiveEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *LiveEvent) GetEvent() isLiveEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *LiveEvent) GetUserCreated() *UserCreatedSyncEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_UserCreated); ok {
			return x.UserCreated
		}
	}
	return nil
}

func (x *LiveEvent) GetUserProfileUpdated() *UserProfileSyncEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_UserProfileUpdated); ok {
			return x.UserProfileUpdated
		}
	}
	return nil
}

func (x *LiveEvent) GetServerUserPreferencesUpdated() *ServerUserPreferencesSyncEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_ServerUserPreferencesUpdated); ok {
			return x.ServerUserPreferencesUpdated
		}
	}
	return nil
}

func (x *LiveEvent) GetThreadFollowChanged() *ThreadFollowChangedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_ThreadFollowChanged); ok {
			return x.ThreadFollowChanged
		}
	}
	return nil
}

func (x *LiveEvent) GetServerMemberDeleted() *ServerMemberDeletedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_ServerMemberDeleted); ok {
			return x.ServerMemberDeleted
		}
	}
	return nil
}

func (x *LiveEvent) GetServerUpdated() *ServerUpdatedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_ServerUpdated); ok {
			return x.ServerUpdated
		}
	}
	return nil
}

func (x *LiveEvent) GetUserTyping() *UserTypingEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_UserTyping); ok {
			return x.UserTyping
		}
	}
	return nil
}

func (x *LiveEvent) GetPresenceChanged() *PresenceChangedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_PresenceChanged); ok {
			return x.PresenceChanged
		}
	}
	return nil
}

func (x *LiveEvent) GetCallParticipantJoined() *CallParticipantJoinedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_CallParticipantJoined); ok {
			return x.CallParticipantJoined
		}
	}
	return nil
}

func (x *LiveEvent) GetCallParticipantLeft() *CallParticipantLeftEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_CallParticipantLeft); ok {
			return x.CallParticipantLeft
		}
	}
	return nil
}

func (x *LiveEvent) GetNotificationOccurrencesInvalidated() *NotificationOccurrencesInvalidatedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_NotificationOccurrencesInvalidated); ok {
			return x.NotificationOccurrencesInvalidated
		}
	}
	return nil
}

func (x *LiveEvent) GetNotificationUnreadChanged() *NotificationUnreadChangedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_NotificationUnreadChanged); ok {
			return x.NotificationUnreadChanged
		}
	}
	return nil
}

func (x *LiveEvent) GetRoomMarkedAsRead() *RoomMarkedAsReadEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_RoomMarkedAsRead); ok {
			return x.RoomMarkedAsRead
		}
	}
	return nil
}

func (x *LiveEvent) GetMentionStatusCleared() *MentionStatusClearedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_MentionStatusCleared); ok {
			return x.MentionStatusCleared
		}
	}
	return nil
}

func (x *LiveEvent) GetRoomGroupsUpdated() *RoomGroupsUpdatedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_RoomGroupsUpdated); ok {
			return x.RoomGroupsUpdated
		}
	}
	return nil
}

func (x *LiveEvent) GetSessionTerminated() *SessionTerminatedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_SessionTerminated); ok {
			return x.SessionTerminated
		}
	}
	return nil
}

type isLiveEvent_Event interface {
	isLiveEvent_Event()
}

type LiveEvent_UserCreated struct {
	// ----- User lifecycle / preferences -----
	UserCreated *UserCreatedSyncEvent `protobuf:"bytes,20,opt,name=user_created,json=userCreated,proto3,oneof"`
}

type LiveEvent_UserProfileUpdated struct {
	// Transient current-profile snapshot derived after a durable profile change.
	UserProfileUpdated *UserProfileSyncEvent `protobuf:"bytes,22,opt,name=user_profile_updated,json=userProfileUpdated,proto3,oneof"`
}

type LiveEvent_ServerUserPreferencesUpdated struct {
	ServerUserPreferencesUpdated *ServerUserPreferencesSyncEvent `protobuf:"bytes,23,opt,name=server_user_preferences_updated,json=serverUserPreferencesUpdated,proto3,oneof"`
}

type LiveEvent_ThreadFollowChanged struct {
	ThreadFollowChanged *ThreadFollowChangedEvent `protobuf:"bytes,25,opt,name=thread_follow_changed,json=threadFollowChanged,proto3,oneof"`
}

type LiveEvent_ServerMemberDeleted struct {
	// ----- Server membership / lifecycle -----
	ServerMemberDeleted *ServerMemberDeletedEvent `protobuf:"bytes,30,opt,name=server_member_deleted,json=serverMemberDeleted,proto3,oneof"`
}

type LiveEvent_ServerUpdated struct {
	ServerUpdated *ServerUpdatedEvent `protobuf:"bytes,31,opt,name=server_updated,json=serverUpdated,proto3,oneof"`
}

type LiveEvent_UserTyping struct {
	// ----- Typing -----
	UserTyping *UserTypingEvent `protobuf:"bytes,40,opt,name=user_typing,json=userTyping,proto3,oneof"`
}

type LiveEvent_PresenceChanged struct {
	// ----- Presence -----
	PresenceChanged *PresenceChangedEvent `protobuf:"bytes,45,opt,name=presence_changed,json=presenceChanged,proto3,oneof"`
}

type LiveEvent_CallParticipantJoined struct {
	// ----- Voice calls -----
	CallParticipantJoined *CallParticipantJoinedEvent `protobuf:"bytes,60,opt,name=call_participant_joined,json=callParticipantJoined,proto3,oneof"`
}

type LiveEvent_CallParticipantLeft struct {
	CallParticipantLeft *CallParticipantLeftEvent `protobuf:"bytes,61,opt,name=call_participant_left,json=callParticipantLeft,proto3,oneof"`
}

type LiveEvent_NotificationOccurrencesInvalidated struct {
	// ----- Notification sync -----
	NotificationOccurrencesInvalidated *NotificationOccurrencesInvalidatedEvent `protobuf:"bytes,72,opt,name=notification_occurrences_invalidated,json=notificationOccurrencesInvalidated,proto3,oneof"`
}

type LiveEvent_NotificationUnreadChanged struct {
	NotificationUnreadChanged *NotificationUnreadChangedEvent `protobuf:"bytes,73,opt,name=notification_unread_changed,json=notificationUnreadChanged,proto3,oneof"`
}

type LiveEvent_RoomMarkedAsRead struct {
	// ----- Unread indicators -----
	RoomMarkedAsRead *RoomMarkedAsReadEvent `protobuf:"bytes,80,opt,name=room_marked_as_read,json=roomMarkedAsRead,proto3,oneof"`
}

type LiveEvent_MentionStatusCleared struct {
	MentionStatusCleared *MentionStatusClearedEvent `protobuf:"bytes,81,opt,name=mention_status_cleared,json=mentionStatusCleared,proto3,oneof"`
}

type LiveEvent_RoomGroupsUpdated struct {
	// ----- Room layout -----
	RoomGroupsUpdated *RoomGroupsUpdatedEvent `protobuf:"bytes,90,opt,name=room_groups_updated,json=roomGroupsUpdated,proto3,oneof"`
}

type LiveEvent_SessionTerminated struct {
	// ----- Session termination -----
	SessionTerminated *SessionTerminatedEvent `protobuf:"bytes,100,opt,name=session_terminated,json=sessionTerminated,proto3,oneof"`
}

func (*LiveEvent_UserCreated) isLiveEvent_Event() {}

func (*LiveEvent_UserProfileUpdated) isLiveEvent_Event() {}

func (*LiveEvent_ServerUserPreferencesUpdated) isLiveEvent_Event() {}

func (*LiveEvent_ThreadFollowChanged) isLiveEvent_Event() {}

func (*LiveEvent_ServerMemberDeleted) isLiveEvent_Event() {}

func (*LiveEvent_ServerUpdated) isLiveEvent_Event() {}

func (*LiveEvent_UserTyping) isLiveEvent_Event() {}

func (*LiveEvent_PresenceChanged) isLiveEvent_Event() {}

func (*LiveEvent_CallParticipantJoined) isLiveEvent_Event() {}

func (*LiveEvent_CallParticipantLeft) isLiveEvent_Event() {}

func (*LiveEvent_NotificationOccurrencesInvalidated) isLiveEvent_Event() {}

func (*LiveEvent_NotificationUnreadChanged) isLiveEvent_Event() {}

func (*LiveEvent_RoomMarkedAsRead) isLiveEvent_Event() {}

func (*LiveEvent_MentionStatusCleared) isLiveEvent_Event() {}

func (*LiveEvent_RoomGroupsUpdated) isLiveEvent_Event() {}

func (*LiveEvent_SessionTerminated) isLiveEvent_Event() {}

// HeartbeatEvent is a synthetic event with no payload. StreamMyEvents
// emits one every ~15 seconds so clients can detect a dead subscription
// on an otherwise-healthy WebSocket. It is never persisted and never
// travels over NATS.
type HeartbeatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatEvent) Reset() {
	*x = HeartbeatEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatEvent) ProtoMessage() {}

func (x *HeartbeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatEvent.ProtoReflect.Descriptor instead.
func (*HeartbeatEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{1}
}

// ServerMemberDeletedEvent invalidates server member views after account
// deletion. It is a transient signal and is independent from the durable EVT
// payload with the same fields.
type ServerMemberDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMemberDeletedEvent) Reset() {
	*x = ServerMemberDeletedEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMemberDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMemberDeletedEvent) ProtoMessage() {}

func (x *ServerMemberDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMemberDeletedEvent.ProtoReflect.Descriptor instead.
func (*ServerMemberDeletedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{2}
}

func (x *ServerMemberDeletedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// CallParticipantJoinedEvent is the transient call-participant join signal.
type CallParticipantJoinedEvent struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	RoomId        string                     `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Source        CallParticipantEventSource `protobuf:"varint,2,opt,name=source,proto3,enum=chatto.core.live.v1.CallParticipantEventSource" json:"source,omitempty"`
	CallId        string                     `protobuf:"bytes,3,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallParticipantJoinedEvent) Reset() {
	*x = CallParticipantJoinedEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallParticipantJoinedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallParticipantJoinedEvent) ProtoMessage() {}

func (x *CallParticipantJoinedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallParticipantJoinedEvent.ProtoReflect.Descriptor instead.
func (*CallParticipantJoinedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{3}
}

func (x *CallParticipantJoinedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CallParticipantJoinedEvent) GetSource() CallParticipantEventSource {
	if x != nil {
		return x.Source
	}
	return CallParticipantEventSource_CALL_PARTICIPANT_EVENT_SOURCE_UNSPECIFIED
}

func (x *CallParticipantJoinedEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

// CallParticipantLeftEvent is the transient call-participant leave signal.
type CallParticipantLeftEvent struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	RoomId        string                     `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Source        CallParticipantEventSource `protobuf:"varint,2,opt,name=source,proto3,enum=chatto.core.live.v1.CallParticipantEventSource" json:"source,omitempty"`
	CallId        string                     `protobuf:"bytes,3,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallParticipantLeftEvent) Reset() {
	*x = CallParticipantLeftEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallParticipantLeftEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallParticipantLeftEvent) ProtoMessage() {}

func (x *CallParticipantLeftEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallParticipantLeftEvent.ProtoReflect.Descriptor instead.
func (*CallParticipantLeftEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{4}
}

func (x *CallParticipantLeftEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CallParticipantLeftEvent) GetSource() CallParticipantEventSource {
	if x != nil {
		return x.Source
	}
	return CallParticipantEventSource_CALL_PARTICIPANT_EVENT_SOURCE_UNSPECIFIED
}

func (x *CallParticipantLeftEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

// UserCreatedSyncEvent reports a newly created public user profile.
type UserCreatedSyncEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreatedSyncEvent) Reset() {
	*x = UserCreatedSyncEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreatedSyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreatedSyncEvent) ProtoMessage() {}

func (x *UserCreatedSyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreatedSyncEvent.ProtoReflect.Descriptor instead.
func (*UserCreatedSyncEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{5}
}

func (x *UserCreatedSyncEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCreatedSyncEvent) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserCreatedSyncEvent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// UserProfileSyncEvent is a transient, projection-derived live snapshot. It
// is published after a public profile field changes and is never stored in EVT.
// Durable user events remain the authoritative profile facts.
type UserProfileSyncEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UserId      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// URL to the user's avatar, or empty if no avatar is set.
	AvatarUrl string `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	// The user's current login/username.
	Login string `protobuf:"bytes,4,opt,name=login,proto3" json:"login,omitempty"`
	// The user's current public bio, or empty when unset.
	Bio string `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	// The user's shared IANA time zone, or empty when none is shared.
	Timezone      string `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileSyncEvent) Reset() {
	*x = UserProfileSyncEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileSyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileSyncEvent) ProtoMessage() {}

func (x *UserProfileSyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileSyncEvent.ProtoReflect.Descriptor instead.
func (*UserProfileSyncEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{6}
}

func (x *UserProfileSyncEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfileSyncEvent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserProfileSyncEvent) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserProfileSyncEvent) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserProfileSyncEvent) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfileSyncEvent) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

// ServerUserPreferencesSyncEvent reports updated user display preferences for
// synchronization between the user's active clients.
type ServerUserPreferencesSyncEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IANA time zone name. An empty value selects the browser default.
	Timezone string `protobuf:"bytes,1,opt,name=timezone,proto3" json:"timezone,omitempty"`
	// Preferred time display format.
	TimeFormat TimeFormat `protobuf:"varint,2,opt,name=time_format,json=timeFormat,proto3,enum=chatto.core.live.v1.TimeFormat" json:"time_format,omitempty"`
	// Whether the stored time zone may appear on the user's public profile.
	ShareTimezone bool `protobuf:"varint,3,opt,name=share_timezone,json=shareTimezone,proto3" json:"share_timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerUserPreferencesSyncEvent) Reset() {
	*x = ServerUserPreferencesSyncEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerUserPreferencesSyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerUserPreferencesSyncEvent) ProtoMessage() {}

func (x *ServerUserPreferencesSyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerUserPreferencesSyncEvent.ProtoReflect.Descriptor instead.
func (*ServerUserPreferencesSyncEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{7}
}

func (x *ServerUserPreferencesSyncEvent) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *ServerUserPreferencesSyncEvent) GetTimeFormat() TimeFormat {
	if x != nil {
		return x.TimeFormat
	}
	return TimeFormat_TIME_FORMAT_UNSPECIFIED
}

func (x *ServerUserPreferencesSyncEvent) GetShareTimezone() bool {
	if x != nil {
		return x.ShareTimezone
	}
	return false
}

type ServerUpdatedEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ServerId    string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// URL to the server's logo, or empty if no logo is set.
	LogoUrl string `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	// URL to the server's banner, or empty if no banner is set.
	BannerUrl     string `protobuf:"bytes,5,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerUpdatedEvent) Reset() {
	*x = ServerUpdatedEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerUpdatedEvent) ProtoMessage() {}

func (x *ServerUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerUpdatedEvent.ProtoReflect.Descriptor instead.
func (*ServerUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{8}
}

func (x *ServerUpdatedEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerUpdatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerUpdatedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServerUpdatedEvent) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *ServerUpdatedEvent) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

// Notifies clients that a user is typing in a room or thread.
// Published directly to NATS Core (bypasses JetStream storage).
// Clients should implement timeout-based clearing (e.g., 6 seconds).
type UserTypingEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID where the user is typing
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Thread root event ID (optional). If set, the user is typing a reply in this thread.
	// If empty, the user is typing in the main room view.
	ThreadRootEventId *string `protobuf:"bytes,3,opt,name=thread_root_event_id,json=threadRootEventId,proto3,oneof" json:"thread_root_event_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserTypingEvent) Reset() {
	*x = UserTypingEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTypingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTypingEvent) ProtoMessage() {}

func (x *UserTypingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTypingEvent.ProtoReflect.Descriptor instead.
func (*UserTypingEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{9}
}

func (x *UserTypingEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UserTypingEvent) GetThreadRootEventId() string {
	if x != nil && x.ThreadRootEventId != nil {
		return *x.ThreadRootEventId
	}
	return ""
}

// Notifies clients that a user's presence status changed.
// Published when a user comes online, goes offline, or changes their status.
// The user whose presence changed is identified by the parent envelope's actor_id.
// Presence is server-wide; the server context is implicit in the subscription.
type PresenceChangedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's new presence status ("ONLINE", "OFFLINE", "AWAY", "DO_NOT_DISTURB")
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceChangedEvent) Reset() {
	*x = PresenceChangedEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceChangedEvent) ProtoMessage() {}

func (x *PresenceChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceChangedEvent.ProtoReflect.Descriptor instead.
func (*PresenceChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{10}
}

func (x *PresenceChangedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// User-scoped invalidation for Notifications 2.0 authoritative replacement.
type NotificationOccurrencesInvalidatedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Legacy candidate for a one-shot local sound on a push-eligible
	// occurrence. Consumers must still validate the candidate against the
	// current occurrence and policy. Retained for rolling compatibility.
	AlertCandidateNotificationId *string `protobuf:"bytes,1,opt,name=alert_candidate_notification_id,json=alertCandidateNotificationId,proto3,oneof" json:"alert_candidate_notification_id,omitempty"`
	// Candidate occurrence for one-shot in-app sound. New publishers set this
	// for both in-app and push-notification modes. Older consumers ignore it.
	SoundCandidateNotificationId *string `protobuf:"bytes,2,opt,name=sound_candidate_notification_id,json=soundCandidateNotificationId,proto3,oneof" json:"sound_candidate_notification_id,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *NotificationOccurrencesInvalidatedEvent) Reset() {
	*x = NotificationOccurrencesInvalidatedEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationOccurrencesInvalidatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationOccurrencesInvalidatedEvent) ProtoMessage() {}

func (x *NotificationOccurrencesInvalidatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationOccurrencesInvalidatedEvent.ProtoReflect.Descriptor instead.
func (*NotificationOccurrencesInvalidatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{11}
}

func (x *NotificationOccurrencesInvalidatedEvent) GetAlertCandidateNotificationId() string {
	if x != nil && x.AlertCandidateNotificationId != nil {
		return *x.AlertCandidateNotificationId
	}
	return ""
}

func (x *NotificationOccurrencesInvalidatedEvent) GetSoundCandidateNotificationId() string {
	if x != nil && x.SoundCandidateNotificationId != nil {
		return *x.SoundCandidateNotificationId
	}
	return ""
}

// ThreadFollowChangedEvent invalidates one user's viewer-specific thread state.
// It is published for follow/unfollow and read-marker changes and is user-scoped
// for multi-tab/multi-device projection convergence.
type ThreadFollowChangedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The room containing the thread.
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// The root event ID of the thread.
	ThreadRootEventId string `protobuf:"bytes,3,opt,name=thread_root_event_id,json=threadRootEventId,proto3" json:"thread_root_event_id,omitempty"`
	// Whether the user is now following (true) or not following (false).
	IsFollowing   bool `protobuf:"varint,4,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadFollowChangedEvent) Reset() {
	*x = ThreadFollowChangedEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadFollowChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadFollowChangedEvent) ProtoMessage() {}

func (x *ThreadFollowChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadFollowChangedEvent.ProtoReflect.Descriptor instead.
func (*ThreadFollowChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{12}
}

func (x *ThreadFollowChangedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ThreadFollowChangedEvent) GetThreadRootEventId() string {
	if x != nil {
		return x.ThreadRootEventId
	}
	return ""
}

func (x *ThreadFollowChangedEvent) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

// Published to the user who marked a room as read. This enables real-time
// updates to other tabs/devices for the same user.
type RoomMarkedAsReadEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID that was marked as read
	RoomId        string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMarkedAsReadEvent) Reset() {
	*x = RoomMarkedAsReadEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMarkedAsReadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMarkedAsReadEvent) ProtoMessage() {}

func (x *RoomMarkedAsReadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMarkedAsReadEvent.ProtoReflect.Descriptor instead.
func (*RoomMarkedAsReadEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{13}
}

func (x *RoomMarkedAsReadEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Invalidates neutral unread attention after a Badge delivery decision or a
// read/visibility change. The signal is user-scoped and carries no message
// content. Projection transports hydrate authoritative room and thread state.
type NotificationUnreadChangedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room whose unread state changed.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Thread root whose unread state changed. Empty means room-level activity.
	ThreadRootEventId string `protobuf:"bytes,2,opt,name=thread_root_event_id,json=threadRootEventId,proto3" json:"thread_root_event_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NotificationUnreadChangedEvent) Reset() {
	*x = NotificationUnreadChangedEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationUnreadChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationUnreadChangedEvent) ProtoMessage() {}

func (x *NotificationUnreadChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationUnreadChangedEvent.ProtoReflect.Descriptor instead.
func (*NotificationUnreadChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{14}
}

func (x *NotificationUnreadChangedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *NotificationUnreadChangedEvent) GetThreadRootEventId() string {
	if x != nil {
		return x.ThreadRootEventId
	}
	return ""
}

// Published to the user whose mention indicator for a room was cleared.
// Fires whenever the server-side mention KV flag (`room_mention_status.*`) is
// deleted — that happens when the user marks a room as read (auto on entry or
// explicit) or dismisses a mention notification on any device. Other devices
// use this to drop the orange dot for the room without waiting for a refetch.
type MentionStatusClearedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID whose mention indicator was cleared
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentionStatusClearedEvent) Reset() {
	*x = MentionStatusClearedEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentionStatusClearedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentionStatusClearedEvent) ProtoMessage() {}

func (x *MentionStatusClearedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentionStatusClearedEvent.ProtoReflect.Descriptor instead.
func (*MentionStatusClearedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{15}
}

func (x *MentionStatusClearedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Notifies clients that the channel-room groups (their ordering, names,
// or membership) were updated. Clients should refetch `Server.roomGroups`.
// Published as a live server event (not stored in JetStream).
type RoomGroupsUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGroupsUpdatedEvent) Reset() {
	*x = RoomGroupsUpdatedEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGroupsUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGroupsUpdatedEvent) ProtoMessage() {}

func (x *RoomGroupsUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGroupsUpdatedEvent.ProtoReflect.Descriptor instead.
func (*RoomGroupsUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{16}
}

// Notifies a user that their session has been terminated.
// Published as a user-scoped event on logout or admin boot.
// The subscription handler closes the stream after forwarding this event,
// ensuring the WebSocket connection is torn down server-side.
type SessionTerminatedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reason for termination: "logout", "admin_boot", "account_deleted"
	Reason        string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionTerminatedEvent) Reset() {
	*x = SessionTerminatedEvent{}
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTerminatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTerminatedEvent) ProtoMessage() {}

func (x *SessionTerminatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_live_v1_live_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTerminatedEvent.ProtoReflect.Descriptor instead.
func (*SessionTerminatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_live_v1_live_events_proto_rawDescGZIP(), []int{17}
}

func (x *SessionTerminatedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_chatto_core_live_v1_live_events_proto protoreflect.FileDescriptor

const file_chatto_core_live_v1_live_events_proto_rawDesc = "" +
	"\n" +
	"%chatto/core/live/v1/live_events.proto\x12\x13chatto.core.live.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x0f\n" +
	"\tLiveEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12N\n" +
	"\fuser_created\x18\x14 \x01(\v2).chatto.core.live.v1.UserCreatedSyncEventH\x00R\vuserCreated\x12]\n" +
	"\x14user_profile_updated\x18\x16 \x01(\v2).chatto.core.live.v1.UserProfileSyncEventH\x00R\x12userProfileUpdated\x12|\n" +
	"\x1fserver_user_preferences_updated\x18\x17 \x01(\v23.chatto.core.live.v1.ServerUserPreferencesSyncEventH\x00R\x1cserverUserPreferencesUpdated\x12c\n" +
	"\x15thread_follow_changed\x18\x19 \x01(\v2-.chatto.core.live.v1.ThreadFollowChangedEventH\x00R\x13threadFollowChanged\x12c\n" +
	"\x15server_member_deleted\x18\x1e \x01(\v2-.chatto.core.live.v1.ServerMemberDeletedEventH\x00R\x13serverMemberDeleted\x12P\n" +
	"\x0eserver_updated\x18\x1f \x01(\v2'.chatto.core.live.v1.ServerUpdatedEventH\x00R\rserverUpdated\x12G\n" +
	"\vuser_typing\x18( \x01(\v2$.chatto.core.live.v1.UserTypingEventH\x00R\n" +
	"userTyping\x12V\n" +
	"\x10presence_changed\x18- \x01(\v2).chatto.core.live.v1.PresenceChangedEventH\x00R\x0fpresenceChanged\x12i\n" +
	"\x17call_participant_joined\x18< \x01(\v2/.chatto.core.live.v1.CallParticipantJoinedEventH\x00R\x15callParticipantJoined\x12c\n" +
	"\x15call_participant_left\x18= \x01(\v2-.chatto.core.live.v1.CallParticipantLeftEventH\x00R\x13callParticipantLeft\x12\x90\x01\n" +
	"$notification_occurrences_invalidated\x18H \x01(\v2<.chatto.core.live.v1.NotificationOccurrencesInvalidatedEventH\x00R\"notificationOccurrencesInvalidated\x12u\n" +
	"\x1bnotification_unread_changed\x18I \x01(\v23.chatto.core.live.v1.NotificationUnreadChangedEventH\x00R\x19notificationUnreadChanged\x12[\n" +
	"\x13room_marked_as_read\x18P \x01(\v2*.chatto.core.live.v1.RoomMarkedAsReadEventH\x00R\x10roomMarkedAsRead\x12f\n" +
	"\x16mention_status_cleared\x18Q \x01(\v2..chatto.core.live.v1.MentionStatusClearedEventH\x00R\x14mentionStatusCleared\x12]\n" +
	"\x13room_groups_updated\x18Z \x01(\v2+.chatto.core.live.v1.RoomGroupsUpdatedEventH\x00R\x11roomGroupsUpdated\x12\\\n" +
	"\x12session_terminated\x18d \x01(\v2+.chatto.core.live.v1.SessionTerminatedEventH\x00R\x11sessionTerminatedB\a\n" +
	"\x05eventJ\x04\b\n" +
	"\x10\vJ\x04\b\x15\x10\x16J\x04\b\x18\x10\x19J\x04\b)\x10*J\x04\b2\x103J\x04\b3\x104J\x04\bF\x10GJ\x04\bG\x10HR\x0econfig_updatedR\x1anotification_level_changedR\x1avideo_processing_completedR\x14mention_notificationR\x1fnew_direct_message_notificationR\x14notification_createdR\x16notification_dismissedR\fuser_deleted\"\x10\n" +
	"\x0eHeartbeatEvent\"C\n" +
	"\x18ServerMemberDeletedEvent\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userIdJ\x04\b\x01\x10\x02R\bspace_id\"\x97\x01\n" +
	"\x1aCallParticipantJoinedEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12G\n" +
	"\x06source\x18\x02 \x01(\x0e2/.chatto.core.live.v1.CallParticipantEventSourceR\x06source\x12\x17\n" +
	"\acall_id\x18\x03 \x01(\tR\x06callId\"\x95\x01\n" +
	"\x18CallParticipantLeftEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12G\n" +
	"\x06source\x18\x02 \x01(\x0e2/.chatto.core.live.v1.CallParticipantEventSourceR\x06source\x12\x17\n" +
	"\acall_id\x18\x03 \x01(\tR\x06callId\"h\n" +
	"\x14UserCreatedSyncEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"\xb5\x01\n" +
	"\x14UserProfileSyncEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05login\x18\x04 \x01(\tR\x05login\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\"\xa5\x01\n" +
	"\x1eServerUserPreferencesSyncEvent\x12\x1a\n" +
	"\btimezone\x18\x01 \x01(\tR\btimezone\x12@\n" +
	"\vtime_format\x18\x02 \x01(\x0e2\x1f.chatto.core.live.v1.TimeFormatR\n" +
	"timeFormat\x12%\n" +
	"\x0eshare_timezone\x18\x03 \x01(\bR\rshareTimezone\"\xa1\x01\n" +
	"\x12ServerUpdatedEvent\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\blogo_url\x18\x04 \x01(\tR\alogoUrl\x12\x1d\n" +
	"\n" +
	"banner_url\x18\x05 \x01(\tR\tbannerUrl\"\x89\x01\n" +
	"\x0fUserTypingEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x124\n" +
	"\x14thread_root_event_id\x18\x03 \x01(\tH\x00R\x11threadRootEventId\x88\x01\x01B\x17\n" +
	"\x15_thread_root_event_idJ\x04\b\x01\x10\x02R\bspace_id\".\n" +
	"\x14PresenceChangedEvent\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x89\x02\n" +
	"'NotificationOccurrencesInvalidatedEvent\x12J\n" +
	"\x1falert_candidate_notification_id\x18\x01 \x01(\tH\x00R\x1calertCandidateNotificationId\x88\x01\x01\x12J\n" +
	"\x1fsound_candidate_notification_id\x18\x02 \x01(\tH\x01R\x1csoundCandidateNotificationId\x88\x01\x01B\"\n" +
	" _alert_candidate_notification_idB\"\n" +
	" _sound_candidate_notification_id\"\x97\x01\n" +
	"\x18ThreadFollowChangedEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12/\n" +
	"\x14thread_root_event_id\x18\x03 \x01(\tR\x11threadRootEventId\x12!\n" +
	"\fis_following\x18\x04 \x01(\bR\visFollowingJ\x04\b\x01\x10\x02R\bspace_id\"@\n" +
	"\x15RoomMarkedAsReadEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomIdJ\x04\b\x01\x10\x02R\bspace_id\"j\n" +
	"\x1eNotificationUnreadChangedEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12/\n" +
	"\x14thread_root_event_id\x18\x02 \x01(\tR\x11threadRootEventId\"4\n" +
	"\x19MentionStatusClearedEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"(\n" +
	"\x16RoomGroupsUpdatedEventJ\x04\b\x01\x10\x02R\bspace_id\"0\n" +
	"\x16SessionTerminatedEvent\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason*S\n" +
	"\n" +
	"TimeFormat\x12\x1b\n" +
	"\x17TIME_FORMAT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTIME_FORMAT_12H\x10\x01\x12\x13\n" +
	"\x0fTIME_FORMAT_24H\x10\x02*\xd0\x01\n" +
	"\x1aCallParticipantEventSource\x12-\n" +
	")CALL_PARTICIPANT_EVENT_SOURCE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"CALL_PARTICIPANT_EVENT_SOURCE_USER\x10\x01\x12)\n" +
	"%CALL_PARTICIPANT_EVENT_SOURCE_LIVEKIT\x10\x02\x120\n" +
	",CALL_PARTICIPANT_EVENT_SOURCE_RECONCILIATION\x10\x03B\xd1\x01\n" +
	"\x17com.chatto.core.live.v1B\x0fLiveEventsProtoP\x01Z6hmans.de/chatto/internal/pb/chatto/core/live/v1;livev1\xa2\x02\x03CCL\xaa\x02\x13Chatto.Core.Live.V1\xca\x02\x13Chatto\\Core\\Live\\V1\xe2\x02\x1fChatto\\Core\\Live\\V1\\GPBMetadata\xea\x02\x16Chatto::Core::Live::V1b\x06proto3"

var (
	file_chatto_core_live_v1_live_events_proto_rawDescOnce sync.Once
	file_chatto_core_live_v1_live_events_proto_rawDescData []byte
)

func file_chatto_core_live_v1_live_events_proto_rawDescGZIP() []byte {
	file_chatto_core_live_v1_live_events_proto_rawDescOnce.Do(func() {
		file_chatto_core_live_v1_live_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_live_v1_live_events_proto_rawDesc), len(file_chatto_core_live_v1_live_events_proto_rawDesc)))
	})
	return file_chatto_core_live_v1_live_events_proto_rawDescData
}

var file_chatto_core_live_v1_live_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chatto_core_live_v1_live_events_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_chatto_core_live_v1_live_events_proto_goTypes = []any{
	(TimeFormat)(0),                                 // 0: chatto.core.live.v1.TimeFormat
	(CallParticipantEventSource)(0),                 // 1: chatto.core.live.v1.CallParticipantEventSource
	(*LiveEvent)(nil),                               // 2: chatto.core.live.v1.LiveEvent
	(*HeartbeatEvent)(nil),                          // 3: chatto.core.live.v1.HeartbeatEvent
	(*ServerMemberDeletedEvent)(nil),                // 4: chatto.core.live.v1.ServerMemberDeletedEvent
	(*CallParticipantJoinedEvent)(nil),              // 5: chatto.core.live.v1.CallParticipantJoinedEvent
	(*CallParticipantLeftEvent)(nil),                // 6: chatto.core.live.v1.CallParticipantLeftEvent
	(*UserCreatedSyncEvent)(nil),                    // 7: chatto.core.live.v1.UserCreatedSyncEvent
	(*UserProfileSyncEvent)(nil),                    // 8: chatto.core.live.v1.UserProfileSyncEvent
	(*ServerUserPreferencesSyncEvent)(nil),          // 9: chatto.core.live.v1.ServerUserPreferencesSyncEvent
	(*ServerUpdatedEvent)(nil),                      // 10: chatto.core.live.v1.ServerUpdatedEvent
	(*UserTypingEvent)(nil),                         // 11: chatto.core.live.v1.UserTypingEvent
	(*PresenceChangedEvent)(nil),                    // 12: chatto.core.live.v1.PresenceChangedEvent
	(*NotificationOccurrencesInvalidatedEvent)(nil), // 13: chatto.core.live.v1.NotificationOccurrencesInvalidatedEvent
	(*ThreadFollowChangedEvent)(nil),                // 14: chatto.core.live.v1.ThreadFollowChangedEvent
	(*RoomMarkedAsReadEvent)(nil),                   // 15: chatto.core.live.v1.RoomMarkedAsReadEvent
	(*NotificationUnreadChangedEvent)(nil),          // 16: chatto.core.live.v1.NotificationUnreadChangedEvent
	(*MentionStatusClearedEvent)(nil),               // 17: chatto.core.live.v1.MentionStatusClearedEvent
	(*RoomGroupsUpdatedEvent)(nil),                  // 18: chatto.core.live.v1.RoomGroupsUpdatedEvent
	(*SessionTerminatedEvent)(nil),                  // 19: chatto.core.live.v1.SessionTerminatedEvent
	(*timestamppb.Timestamp)(nil),                   // 20: google.protobuf.Timestamp
}
var file_chatto_core_live_v1_live_events_proto_depIdxs = []int32{
	20, // 0: chatto.core.live.v1.LiveEvent.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: chatto.core.live.v1.LiveEvent.user_created:type_name -> chatto.core.live.v1.UserCreatedSyncEvent
	8,  // 2: chatto.core.live.v1.LiveEvent.user_profile_updated:type_name -> chatto.core.live.v1.UserProfileSyncEvent
	9,  // 3: chatto.core.live.v1.LiveEvent.server_user_preferences_updated:type_name -> chatto.core.live.v1.ServerUserPreferencesSyncEvent
	14, // 4: chatto.core.live.v1.LiveEvent.thread_follow_changed:type_name -> chatto.core.live.v1.ThreadFollowChangedEvent
	4,  // 5: chatto.core.live.v1.LiveEvent.server_member_deleted:type_name -> chatto.core.live.v1.ServerMemberDeletedEvent
	10, // 6: chatto.core.live.v1.LiveEvent.server_updated:type_name -> chatto.core.live.v1.ServerUpdatedEvent
	11, // 7: chatto.core.live.v1.LiveEvent.user_typing:type_name -> chatto.core.live.v1.UserTypingEvent
	12, // 8: chatto.core.live.v1.LiveEvent.presence_changed:type_name -> chatto.core.live.v1.PresenceChangedEvent
	5,  // 9: chatto.core.live.v1.LiveEvent.call_participant_joined:type_name -> chatto.core.live.v1.CallParticipantJoinedEvent
	6,  // 10: chatto.core.live.v1.LiveEvent.call_participant_left:type_name -> chatto.core.live.v1.CallParticipantLeftEvent
	13, // 11: chatto.core.live.v1.LiveEvent.notification_occurrences_invalidated:type_name -> chatto.core.live.v1.NotificationOccurrencesInvalidatedEvent
	16, // 12: chatto.core.live.v1.LiveEvent.notification_unread_changed:type_name -> chatto.core.live.v1.NotificationUnreadChangedEvent
	15, // 13: chatto.core.live.v1.LiveEvent.room_marked_as_read:type_name -> chatto.core.live.v1.RoomMarkedAsReadEvent
	17, // 14: chatto.core.live.v1.LiveEvent.mention_status_cleared:type_name -> chatto.core.live.v1.MentionStatusClearedEvent
	18, // 15: chatto.core.live.v1.LiveEvent.room_groups_updated:type_name -> chatto.core.live.v1.RoomGroupsUpdatedEvent
	19, // 16: chatto.core.live.v1.LiveEvent.session_terminated:type_name -> chatto.core.live.v1.SessionTerminatedEvent
	1,  // 17: chatto.core.live.v1.CallParticipantJoinedEvent.source:type_name -> chatto.core.live.v1.CallParticipantEventSource
	1,  // 18: chatto.core.live.v1.CallParticipantLeftEvent.source:type_name -> chatto.core.live.v1.CallParticipantEventSource
	0,  // 19: chatto.core.live.v1.ServerUserPreferencesSyncEvent.time_format:type_name -> chatto.core.live.v1.TimeFormat
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_chatto_core_live_v1_live_events_proto_init() }
func file_chatto_core_live_v1_live_events_proto_init() {
	if File_chatto_core_live_v1_live_events_proto != nil {
		return
	}
	file_chatto_core_live_v1_live_events_proto_msgTypes[0].OneofWrappers = []any{
		(*LiveEvent_UserCreated)(nil),
		(*LiveEvent_UserProfileUpdated)(nil),
		(*LiveEvent_ServerUserPreferencesUpdated)(nil),
		(*LiveEvent_ThreadFollowChanged)(nil),
		(*LiveEvent_ServerMemberDeleted)(nil),
		(*LiveEvent_ServerUpdated)(nil),
		(*LiveEvent_UserTyping)(nil),
		(*LiveEvent_PresenceChanged)(nil),
		(*LiveEvent_CallParticipantJoined)(nil),
		(*LiveEvent_CallParticipantLeft)(nil),
		(*LiveEvent_NotificationOccurrencesInvalidated)(nil),
		(*LiveEvent_NotificationUnreadChanged)(nil),
		(*LiveEvent_RoomMarkedAsRead)(nil),
		(*LiveEvent_MentionStatusCleared)(nil),
		(*LiveEvent_RoomGroupsUpdated)(nil),
		(*LiveEvent_SessionTerminated)(nil),
	}
	file_chatto_core_live_v1_live_events_proto_msgTypes[9].OneofWrappers = []any{}
	file_chatto_core_live_v1_live_events_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_live_v1_live_events_proto_rawDesc), len(file_chatto_core_live_v1_live_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_live_v1_live_events_proto_goTypes,
		DependencyIndexes: file_chatto_core_live_v1_live_events_proto_depIdxs,
		EnumInfos:         file_chatto_core_live_v1_live_events_proto_enumTypes,
		MessageInfos:      file_chatto_core_live_v1_live_events_proto_msgTypes,
	}.Build()
	File_chatto_core_live_v1_live_events_proto = out.File
	file_chatto_core_live_v1_live_events_proto_goTypes = nil
	file_chatto_core_live_v1_live_events_proto_depIdxs = nil
}
