// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file chatto/api/v1/common.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chatto/api/v1/common.proto.
 */
export const file_chatto_api_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChpjaGF0dG8vYXBpL3YxL2NvbW1vbi5wcm90bxINY2hhdHRvLmFwaS52MSKCAQoVSW1hZ2VUcmFuc2Zvcm1PcHRpb25zEhkKBXdpZHRoGAEgASgFQgq6SAcaBRiAICgBEhoKBmhlaWdodBgCIAEoBUIKukgHGgUYgCAoARIyCgNmaXQYAyABKA4yGy5jaGF0dG8uYXBpLnYxLkltYWdlRml0TW9kZUIIukgFggECEAEiRAoLSW1hZ2VVcGxvYWQSDQoFaW1hZ2UYASABKAwSEAoIZmlsZW5hbWUYAiABKAkSFAoMY29udGVudF90eXBlGAMgASgJIqYBChBQcm92aWRlck1ldGFkYXRhEgoKAmlkGAEgASgJEgwKBHR5cGUYAiABKAkSDQoFbGFiZWwYAyABKAkSEQoJbG9naW5fdXJsGAQgASgJEhcKCmlzc3Vlcl91cmwYBSABKAlIAIgBARIbCg5hdXRvX3Byb3Zpc2lvbhgGIAEoCEgBiAEBQg0KC19pc3N1ZXJfdXJsQhEKD19hdXRvX3Byb3Zpc2lvbipkCgxJbWFnZUZpdE1vZGUSHgoaSU1BR0VfRklUX01PREVfVU5TUEVDSUZJRUQQABIaChZJTUFHRV9GSVRfTU9ERV9DT05UQUlOEAESGAoUSU1BR0VfRklUX01PREVfQ09WRVIQAirBAQoRUm9vbVRocmVhZGluZ01vZGUSIwofUk9PTV9USFJFQURJTkdfTU9ERV9VTlNQRUNJRklFRBAAEiAKHFJPT01fVEhSRUFESU5HX01PREVfUkVRVUlSRUQQARIiCh5ST09NX1RIUkVBRElOR19NT0RFX0VOQ09VUkFHRUQQAhIfChtST09NX1RIUkVBRElOR19NT0RFX0VOQUJMRUQQAxIgChxST09NX1RIUkVBRElOR19NT0RFX0RJU0FCTEVEEARCpwEKEWNvbS5jaGF0dG8uYXBpLnYxQgtDb21tb25Qcm90b1ABWi9obWFucy5kZS9jaGF0dG8vaW50ZXJuYWwvcGIvY2hhdHRvL2FwaS92MTthcGl2MaICA0NBWKoCDUNoYXR0by5BcGkuVjHKAg1DaGF0dG9cQXBpXFYx4gIZQ2hhdHRvXEFwaVxWMVxHUEJNZXRhZGF0YeoCD0NoYXR0bzo6QXBpOjpWMWIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * Image transform parameters for generated image URLs.
 *
 * @generated from message chatto.api.v1.ImageTransformOptions
 */
export type ImageTransformOptions = Message<"chatto.api.v1.ImageTransformOptions"> & {
  /**
   * Target image width in pixels.
   *
   * @generated from field: int32 width = 1;
   */
  width: number;

  /**
   * Target image height in pixels.
   *
   * @generated from field: int32 height = 2;
   */
  height: number;

  /**
   * Image crop/fit behavior.
   *
   * @generated from field: chatto.api.v1.ImageFitMode fit = 3;
   */
  fit: ImageFitMode;
};

/**
 * Describes the message chatto.api.v1.ImageTransformOptions.
 * Use `create(ImageTransformOptionsSchema)` to create a new message.
 */
export const ImageTransformOptionsSchema: GenMessage<ImageTransformOptions> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_common, 0);

/**
 * Browser-supplied image upload payload.
 *
 * @generated from message chatto.api.v1.ImageUpload
 */
export type ImageUpload = Message<"chatto.api.v1.ImageUpload"> & {
  /**
   * Raw image bytes.
   *
   * @generated from field: bytes image = 1;
   */
  image: Uint8Array;

  /**
   * Original browser filename, for diagnostics and future compatibility.
   *
   * @generated from field: string filename = 2;
   */
  filename: string;

  /**
   * Browser-provided content type, for diagnostics and future compatibility.
   *
   * @generated from field: string content_type = 3;
   */
  contentType: string;
};

/**
 * Describes the message chatto.api.v1.ImageUpload.
 * Use `create(ImageUploadSchema)` to create a new message.
 */
export const ImageUploadSchema: GenMessage<ImageUpload> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_common, 1);

/**
 * Public login/provider metadata shared by discovery and account-linking APIs.
 *
 * @generated from message chatto.api.v1.ProviderMetadata
 */
export type ProviderMetadata = Message<"chatto.api.v1.ProviderMetadata"> & {
  /**
   * Stable configured provider ID.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Provider type, such as "password", "oidc", "github", or "discord".
   *
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * Human-readable provider label.
   *
   * @generated from field: string label = 3;
   */
  label: string;

  /**
   * URL that starts login for this provider.
   *
   * @generated from field: string login_url = 4;
   */
  loginUrl: string;

  /**
   * OIDC issuer URL. Absent for providers that do not use OpenID Connect.
   * Clients can compare this value with their own trusted issuer selection;
   * the server does not select the client's identity provider.
   *
   * @generated from field: optional string issuer_url = 5;
   */
  issuerUrl?: string | undefined;

  /**
   * Whether an unlinked identity may create a new account through this provider.
   *
   * @generated from field: optional bool auto_provision = 6;
   */
  autoProvision?: boolean | undefined;
};

/**
 * Describes the message chatto.api.v1.ProviderMetadata.
 * Use `create(ProviderMetadataSchema)` to create a new message.
 */
export const ProviderMetadataSchema: GenMessage<ProviderMetadata> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_common, 2);

/**
 * Fit mode used when generating transformed image URLs.
 *
 * @generated from enum chatto.api.v1.ImageFitMode
 */
export enum ImageFitMode {
  /**
   * The fit mode was not specified.
   *
   * @generated from enum value: IMAGE_FIT_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Preserve the whole source image within the requested bounds.
   *
   * @generated from enum value: IMAGE_FIT_MODE_CONTAIN = 1;
   */
  CONTAIN = 1,

  /**
   * Fill the requested bounds, cropping when needed.
   *
   * @generated from enum value: IMAGE_FIT_MODE_COVER = 2;
   */
  COVER = 2,
}

/**
 * Describes the enum chatto.api.v1.ImageFitMode.
 */
export const ImageFitModeSchema: GenEnum<ImageFitMode> = /*@__PURE__*/
  enumDesc(file_chatto_api_v1_common, 0);

/**
 * Policy governing thread creation and reply placement in a channel room.
 * Direct-message rooms do not support threads and use UNSPECIFIED.
 *
 * @generated from enum chatto.api.v1.RoomThreadingMode
 */
export enum RoomThreadingMode {
  /**
   * No mode was supplied. CreateRoom treats this as ENABLED so older stored
   * rooms and omitted request fields preserve Chatto's default behavior.
   *
   * @generated from enum value: ROOM_THREADING_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Every new root message establishes a thread, and replies to root messages
   * must be posted in that root's thread.
   *
   * @generated from enum value: ROOM_THREADING_MODE_REQUIRED = 1;
   */
  REQUIRED = 1,

  /**
   * Clients should steer replies into threads, but the server accepts both
   * threaded and ordinary in-room replies.
   *
   * @generated from enum value: ROOM_THREADING_MODE_ENCOURAGED = 2;
   */
  ENCOURAGED = 2,

  /**
   * Threads are available and clients may freely choose whether to use them.
   *
   * @generated from enum value: ROOM_THREADING_MODE_ENABLED = 3;
   */
  ENABLED = 3,

  /**
   * New threads, thread replies, and channel echoes are rejected. Existing
   * threads and echoes remain readable and ordinary in-room reply attribution
   * remains available.
   *
   * @generated from enum value: ROOM_THREADING_MODE_DISABLED = 4;
   */
  DISABLED = 4,
}

/**
 * Describes the enum chatto.api.v1.RoomThreadingMode.
 */
export const RoomThreadingModeSchema: GenEnum<RoomThreadingMode> = /*@__PURE__*/
  enumDesc(file_chatto_api_v1_common, 1);
