// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/api/v1/member_directory.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { User } from "./users_pb.js";
import { PageInfo, PageRequest } from "./pagination_pb.js";

/**
 * Public user/member row used by user directory, room membership, and mention
 * surfaces.
 *
 * @generated from message chatto.api.v1.DirectoryMember
 */
export class DirectoryMember extends Message<DirectoryMember> {
  /**
   * Public user fields.
   *
   * @generated from field: chatto.api.v1.User user = 1;
   */
  user?: User;

  /**
   * Explicit roles assigned to the user. Member listings include the virtual
   * `everyone` role for parity with Chatto's permission model.
   *
   * @generated from field: repeated string roles = 2;
   */
  roles: string[] = [];

  /**
   * Account creation time when known.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 3;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<DirectoryMember>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.DirectoryMember";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: User },
    { no: 2, name: "roles", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "created_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DirectoryMember {
    return new DirectoryMember().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DirectoryMember {
    return new DirectoryMember().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DirectoryMember {
    return new DirectoryMember().fromJsonString(jsonString, options);
  }

  static equals(a: DirectoryMember | PlainMessage<DirectoryMember> | undefined, b: DirectoryMember | PlainMessage<DirectoryMember> | undefined): boolean {
    return proto3.util.equals(DirectoryMember, a, b);
  }
}

/**
 * Request for members of one room.
 *
 * @generated from message chatto.api.v1.ListMembersRequest
 */
export class ListMembersRequest extends Message<ListMembersRequest> {
  /**
   * Required. Room whose effective members should be listed. Existing members
   * and room.manage holders may list a channel room; other nonmembers need both
   * room.list and room.join.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Optional case-insensitive search against login and display name.
   *
   * @generated from field: string search = 2;
   */
  search = "";

  /**
   * Page request. Defaults to 250 results when absent or limit is zero.
   *
   * @generated from field: chatto.api.v1.PageRequest page = 5;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListMembersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ListMembersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "search", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListMembersRequest {
    return new ListMembersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListMembersRequest {
    return new ListMembersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListMembersRequest {
    return new ListMembersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListMembersRequest | PlainMessage<ListMembersRequest> | undefined, b: ListMembersRequest | PlainMessage<ListMembersRequest> | undefined): boolean {
    return proto3.util.equals(ListMembersRequest, a, b);
  }
}

/**
 * Room member page.
 *
 * @generated from message chatto.api.v1.ListMembersResponse
 */
export class ListMembersResponse extends Message<ListMembersResponse> {
  /**
   * Members in the requested page.
   *
   * @generated from field: repeated chatto.api.v1.DirectoryMember members = 1;
   */
  members: DirectoryMember[] = [];

  /**
   * Page metadata.
   *
   * @generated from field: chatto.api.v1.PageInfo page = 4;
   */
  page?: PageInfo;

  constructor(data?: PartialMessage<ListMembersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ListMembersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "members", kind: "message", T: DirectoryMember, repeated: true },
    { no: 4, name: "page", kind: "message", T: PageInfo },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListMembersResponse {
    return new ListMembersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListMembersResponse {
    return new ListMembersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListMembersResponse {
    return new ListMembersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListMembersResponse | PlainMessage<ListMembersResponse> | undefined, b: ListMembersResponse | PlainMessage<ListMembersResponse> | undefined): boolean {
    return proto3.util.equals(ListMembersResponse, a, b);
  }
}

/**
 * Request one member of one room by stable user ID.
 *
 * @generated from message chatto.api.v1.GetMemberRequest
 */
export class GetMemberRequest extends Message<GetMemberRequest> {
  /**
   * Required room ID.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required target user ID.
   *
   * @generated from field: string user_id = 2;
   */
  userId = "";

  constructor(data?: PartialMessage<GetMemberRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetMemberRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMemberRequest {
    return new GetMemberRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMemberRequest {
    return new GetMemberRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMemberRequest {
    return new GetMemberRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetMemberRequest | PlainMessage<GetMemberRequest> | undefined, b: GetMemberRequest | PlainMessage<GetMemberRequest> | undefined): boolean {
    return proto3.util.equals(GetMemberRequest, a, b);
  }
}

/**
 * Room member response.
 *
 * @generated from message chatto.api.v1.GetMemberResponse
 */
export class GetMemberResponse extends Message<GetMemberResponse> {
  /**
   * Requested room member.
   *
   * @generated from field: chatto.api.v1.DirectoryMember member = 1;
   */
  member?: DirectoryMember;

  constructor(data?: PartialMessage<GetMemberResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetMemberResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "member", kind: "message", T: DirectoryMember },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMemberResponse {
    return new GetMemberResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMemberResponse {
    return new GetMemberResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMemberResponse {
    return new GetMemberResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetMemberResponse | PlainMessage<GetMemberResponse> | undefined, b: GetMemberResponse | PlainMessage<GetMemberResponse> | undefined): boolean {
    return proto3.util.equals(GetMemberResponse, a, b);
  }
}

/**
 * Request room member rows for a set of stable user IDs.
 *
 * @generated from message chatto.api.v1.BatchGetMembersRequest
 */
export class BatchGetMembersRequest extends Message<BatchGetMembersRequest> {
  /**
   * Required room ID.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required target user IDs. Unknown IDs and users that are not members of the
   * room are omitted from the response.
   *
   * @generated from field: repeated string user_ids = 2;
   */
  userIds: string[] = [];

  constructor(data?: PartialMessage<BatchGetMembersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.BatchGetMembersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchGetMembersRequest {
    return new BatchGetMembersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchGetMembersRequest {
    return new BatchGetMembersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchGetMembersRequest {
    return new BatchGetMembersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: BatchGetMembersRequest | PlainMessage<BatchGetMembersRequest> | undefined, b: BatchGetMembersRequest | PlainMessage<BatchGetMembersRequest> | undefined): boolean {
    return proto3.util.equals(BatchGetMembersRequest, a, b);
  }
}

/**
 * Batch room member response.
 *
 * @generated from message chatto.api.v1.BatchGetMembersResponse
 */
export class BatchGetMembersResponse extends Message<BatchGetMembersResponse> {
  /**
   * Found members. The server preserves first-seen request order and
   * de-duplicates repeated IDs.
   *
   * @generated from field: repeated chatto.api.v1.DirectoryMember members = 1;
   */
  members: DirectoryMember[] = [];

  constructor(data?: PartialMessage<BatchGetMembersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.BatchGetMembersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "members", kind: "message", T: DirectoryMember, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchGetMembersResponse {
    return new BatchGetMembersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchGetMembersResponse {
    return new BatchGetMembersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchGetMembersResponse {
    return new BatchGetMembersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: BatchGetMembersResponse | PlainMessage<BatchGetMembersResponse> | undefined, b: BatchGetMembersResponse | PlainMessage<BatchGetMembersResponse> | undefined): boolean {
    return proto3.util.equals(BatchGetMembersResponse, a, b);
  }
}
