// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/api/v1/message_search.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { Message as Message$1, ThreadSummary } from "./message_types_pb.js";
import { RoomTimelineIncludes } from "./room_timeline_pb.js";
import { RoomSummary } from "./rooms_pb.js";

/**
 * Ordering for message or grouped-thread search results.
 *
 * @generated from enum chatto.api.v1.MessageSearchOrder
 */
export enum MessageSearchOrder {
  /**
   * Use relevance order.
   *
   * @generated from enum value: MESSAGE_SEARCH_ORDER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Highest message score first; grouped results use their best matching message.
   *
   * @generated from enum value: MESSAGE_SEARCH_ORDER_RELEVANCE = 1;
   */
  RELEVANCE = 1,

  /**
   * Newest matching message first, also when results are grouped.
   *
   * @generated from enum value: MESSAGE_SEARCH_ORDER_NEWEST = 2;
   */
  NEWEST = 2,

  /**
   * Return threads with the most recent activity first. Requires thread grouping.
   *
   * @generated from enum value: MESSAGE_SEARCH_ORDER_THREAD_ACTIVITY = 3;
   */
  THREAD_ACTIVITY = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(MessageSearchOrder)
proto3.util.setEnumType(MessageSearchOrder, "chatto.api.v1.MessageSearchOrder", [
  { no: 0, name: "MESSAGE_SEARCH_ORDER_UNSPECIFIED" },
  { no: 1, name: "MESSAGE_SEARCH_ORDER_RELEVANCE" },
  { no: 2, name: "MESSAGE_SEARCH_ORDER_NEWEST" },
  { no: 3, name: "MESSAGE_SEARCH_ORDER_THREAD_ACTIVITY" },
]);

/**
 * Candidate scope, intersected with the caller's current access and query filters.
 *
 * @generated from enum chatto.api.v1.MessageSearchScope
 */
export enum MessageSearchScope {
  /**
   * Search all accessible messages. This is the existing default.
   *
   * @generated from enum value: MESSAGE_SEARCH_SCOPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Search roots and replies in followed threads, including direct messages.
   *
   * @generated from enum value: MESSAGE_SEARCH_SCOPE_FOLLOWED_THREADS = 1;
   */
  FOLLOWED_THREADS = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(MessageSearchScope)
proto3.util.setEnumType(MessageSearchScope, "chatto.api.v1.MessageSearchScope", [
  { no: 0, name: "MESSAGE_SEARCH_SCOPE_UNSPECIFIED" },
  { no: 1, name: "MESSAGE_SEARCH_SCOPE_FOLLOWED_THREADS" },
]);

/**
 * Determines the result type and pagination unit.
 *
 * @generated from enum chatto.api.v1.MessageSearchGroupBy
 */
export enum MessageSearchGroupBy {
  /**
   * Return individual matching messages.
   *
   * @generated from enum value: MESSAGE_SEARCH_GROUP_BY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Return distinct thread rows. A root without replies is also a thread.
   *
   * @generated from enum value: MESSAGE_SEARCH_GROUP_BY_THREAD = 1;
   */
  THREAD = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(MessageSearchGroupBy)
proto3.util.setEnumType(MessageSearchGroupBy, "chatto.api.v1.MessageSearchGroupBy", [
  { no: 0, name: "MESSAGE_SEARCH_GROUP_BY_UNSPECIFIED" },
  { no: 1, name: "MESSAGE_SEARCH_GROUP_BY_THREAD" },
]);

/**
 * Current availability of message search on this server.
 *
 * @generated from enum chatto.api.v1.MessageSearchState
 */
export enum MessageSearchState {
  /**
   * The server did not report a meaningful state.
   *
   * @generated from enum value: MESSAGE_SEARCH_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Search is disabled by the server operator.
   *
   * @generated from enum value: MESSAGE_SEARCH_STATE_DISABLED = 1;
   */
  DISABLED = 1,

  /**
   * Search is enabled but its provider has not established index state yet.
   *
   * @generated from enum value: MESSAGE_SEARCH_STATE_STARTING = 2;
   */
  STARTING = 2,

  /**
   * The provider is rebuilding or catching up and cannot answer queries yet.
   *
   * @generated from enum value: MESSAGE_SEARCH_STATE_INDEXING = 3;
   */
  INDEXING = 3,

  /**
   * Search is ready to answer queries.
   *
   * @generated from enum value: MESSAGE_SEARCH_STATE_READY = 4;
   */
  READY = 4,

  /**
   * Search can answer queries but has a known non-fatal limitation.
   *
   * @generated from enum value: MESSAGE_SEARCH_STATE_DEGRADED = 5;
   */
  DEGRADED = 5,

  /**
   * Search is enabled but no provider can currently answer.
   *
   * @generated from enum value: MESSAGE_SEARCH_STATE_UNAVAILABLE = 6;
   */
  UNAVAILABLE = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(MessageSearchState)
proto3.util.setEnumType(MessageSearchState, "chatto.api.v1.MessageSearchState", [
  { no: 0, name: "MESSAGE_SEARCH_STATE_UNSPECIFIED" },
  { no: 1, name: "MESSAGE_SEARCH_STATE_DISABLED" },
  { no: 2, name: "MESSAGE_SEARCH_STATE_STARTING" },
  { no: 3, name: "MESSAGE_SEARCH_STATE_INDEXING" },
  { no: 4, name: "MESSAGE_SEARCH_STATE_READY" },
  { no: 5, name: "MESSAGE_SEARCH_STATE_DEGRADED" },
  { no: 6, name: "MESSAGE_SEARCH_STATE_UNAVAILABLE" },
]);

/**
 * Request to search current message bodies visible to the authenticated user.
 *
 * @generated from message chatto.api.v1.SearchMessagesRequest
 */
export class SearchMessagesRequest extends Message<SearchMessagesRequest> {
  /**
   * Required query expression. Words are required terms, quoted text is an
   * exact phrase, and `AND` may separate terms. The query also accepts `in:`,
   * `from:`, `before:`, `after:`, and `has:attachment` filters; a recognized
   * filter may be used without a word or phrase.
   *
   * @generated from field: string query = 1;
   */
  query = "";

  /**
   * Optional room-ID scope. The server intersects this room with rooms the
   * current user may read and with any `in:` filters in query.
   *
   * @generated from field: optional string room_id = 2;
   */
  roomId?: string;

  /**
   * Optional author-ID scope. The server intersects this author with any
   * `from:` filters in query.
   *
   * @generated from field: optional string author_id = 3;
   */
  authorId?: string;

  /**
   * Exclusive lower bound on message creation time. The stricter bound wins
   * when query also contains `after:`.
   *
   * @generated from field: google.protobuf.Timestamp created_after = 4;
   */
  createdAfter?: Timestamp;

  /**
   * Exclusive upper bound on message creation time. The stricter bound wins
   * when query also contains `before:`.
   *
   * @generated from field: google.protobuf.Timestamp created_before = 5;
   */
  createdBefore?: Timestamp;

  /**
   * When true, return only messages that currently have attachments.
   *
   * @generated from field: bool has_attachments = 6;
   */
  hasAttachments = false;

  /**
   * Defaults to relevance in both result modes. Thread activity order requires
   * thread grouping; newest order uses matching-message creation time.
   *
   * @generated from field: chatto.api.v1.MessageSearchOrder order = 7;
   */
  order = MessageSearchOrder.UNSPECIFIED;

  /**
   * Maximum results to return (messages or distinct threads). Zero uses 50; the
   * maximum is 100. Stale or no-longer-visible provider hits are omitted, so a
   * page may contain fewer messages than requested even when next_cursor is
   * present.
   *
   * @generated from field: uint32 page_size = 8;
   */
  pageSize = 0;

  /**
   * Opaque cursor returned by the preceding response. It is bound to the
   * authenticated user and every other query field.
   *
   * @generated from field: string cursor = 9;
   */
  cursor = "";

  /**
   * Candidate scope. Followed threads are selected before result pagination.
   *
   * @generated from field: chatto.api.v1.MessageSearchScope scope = 10;
   */
  scope = MessageSearchScope.UNSPECIFIED;

  /**
   * Result grouping. The server deduplicates threads before pagination.
   *
   * @generated from field: chatto.api.v1.MessageSearchGroupBy group_by = 11;
   */
  groupBy = MessageSearchGroupBy.UNSPECIFIED;

  constructor(data?: PartialMessage<SearchMessagesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.SearchMessagesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "author_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "created_after", kind: "message", T: Timestamp },
    { no: 5, name: "created_before", kind: "message", T: Timestamp },
    { no: 6, name: "has_attachments", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "order", kind: "enum", T: proto3.getEnumType(MessageSearchOrder) },
    { no: 8, name: "page_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 9, name: "cursor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "scope", kind: "enum", T: proto3.getEnumType(MessageSearchScope) },
    { no: 11, name: "group_by", kind: "enum", T: proto3.getEnumType(MessageSearchGroupBy) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchMessagesRequest {
    return new SearchMessagesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchMessagesRequest {
    return new SearchMessagesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchMessagesRequest {
    return new SearchMessagesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SearchMessagesRequest | PlainMessage<SearchMessagesRequest> | undefined, b: SearchMessagesRequest | PlainMessage<SearchMessagesRequest> | undefined): boolean {
    return proto3.util.equals(SearchMessagesRequest, a, b);
  }
}

/**
 * One current, authorized match. With thread grouping, each result represents
 * one thread and message is its best match in the selected order.
 *
 * @generated from message chatto.api.v1.MessageSearchResult
 */
export class MessageSearchResult extends Message<MessageSearchResult> {
  /**
   * Current renderable message that matched the query.
   *
   * @generated from field: chatto.api.v1.Message message = 1;
   */
  message?: Message$1;

  /**
   * Search-provider relevance score. Higher values are more relevant for the
   * same query. Clients may merge results from servers using compatible
   * search implementations by this value.
   *
   * @generated from field: double relevance_score = 2;
   */
  relevanceScore = 0;

  /**
   * Present only with THREAD grouping. The matching message can be a reply;
   * the root and latest reply in this context need not match the query.
   *
   * @generated from field: chatto.api.v1.ThreadSearchContext thread_context = 3;
   */
  threadContext?: ThreadSearchContext;

  constructor(data?: PartialMessage<MessageSearchResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.MessageSearchResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "message", T: Message$1 },
    { no: 2, name: "relevance_score", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "thread_context", kind: "message", T: ThreadSearchContext },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageSearchResult {
    return new MessageSearchResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageSearchResult {
    return new MessageSearchResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageSearchResult {
    return new MessageSearchResult().fromJsonString(jsonString, options);
  }

  static equals(a: MessageSearchResult | PlainMessage<MessageSearchResult> | undefined, b: MessageSearchResult | PlainMessage<MessageSearchResult> | undefined): boolean {
    return proto3.util.equals(MessageSearchResult, a, b);
  }
}

/**
 * One ordered page of current, authorized message or thread results. Pagination reads a live
 * search index rather than a pinned snapshot, so results may move, repeat, or
 * disappear between page requests while the index advances.
 *
 * @generated from message chatto.api.v1.SearchMessagesResponse
 */
export class SearchMessagesResponse extends Message<SearchMessagesResponse> {
  /**
   * Ordered matches. With THREAD grouping, one result per matching thread.
   * Otherwise each result is one message, without thread_context.
   *
   * @generated from field: repeated chatto.api.v1.MessageSearchResult results = 1;
   */
  results: MessageSearchResult[] = [];

  /**
   * Opaque cursor for the next page in the selected result mode.
   * Empty means no more matches. Live activity can reorder thread pages.
   *
   * @generated from field: string next_cursor = 2;
   */
  nextCursor = "";

  /**
   * Total distinct matching threads. Present only when group_by is THREAD.
   *
   * @generated from field: optional uint64 thread_total_count = 4;
   */
  threadTotalCount?: bigint;

  /**
   * Related entities for grouped results, avoiding per-row reads.
   *
   * @generated from field: chatto.api.v1.RoomTimelineIncludes includes = 5;
   */
  includes?: RoomTimelineIncludes;

  constructor(data?: PartialMessage<SearchMessagesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.SearchMessagesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "results", kind: "message", T: MessageSearchResult, repeated: true },
    { no: 2, name: "next_cursor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "thread_total_count", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 5, name: "includes", kind: "message", T: RoomTimelineIncludes },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchMessagesResponse {
    return new SearchMessagesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchMessagesResponse {
    return new SearchMessagesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchMessagesResponse {
    return new SearchMessagesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SearchMessagesResponse | PlainMessage<SearchMessagesResponse> | undefined, b: SearchMessagesResponse | PlainMessage<SearchMessagesResponse> | undefined): boolean {
    return proto3.util.equals(SearchMessagesResponse, a, b);
  }
}

/**
 * Current context for a grouped match. The viewer need not follow this thread.
 * Search evidence stays on the containing MessageSearchResult.
 *
 * @generated from message chatto.api.v1.ThreadSearchContext
 */
export class ThreadSearchContext extends Message<ThreadSearchContext> {
  /**
   * Renderable root message, when still visible.
   *
   * @generated from field: chatto.api.v1.Message root_message = 1;
   */
  rootMessage?: Message$1;

  /**
   * Room containing this thread.
   *
   * @generated from field: chatto.api.v1.RoomSummary room = 2;
   */
  room?: RoomSummary;

  /**
   * Current thread metadata and viewer follow/read state.
   *
   * @generated from field: chatto.api.v1.ThreadSummary thread = 3;
   */
  thread?: ThreadSummary;

  /**
   * Most recent visible reply, when present; it need not match the query.
   *
   * @generated from field: chatto.api.v1.Message latest_reply = 4;
   */
  latestReply?: Message$1;

  /**
   * Conversation-label participants for direct messages; empty for channels.
   *
   * @generated from field: repeated string direct_message_participant_user_ids = 5;
   */
  directMessageParticipantUserIds: string[] = [];

  constructor(data?: PartialMessage<ThreadSearchContext>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ThreadSearchContext";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "root_message", kind: "message", T: Message$1 },
    { no: 2, name: "room", kind: "message", T: RoomSummary },
    { no: 3, name: "thread", kind: "message", T: ThreadSummary },
    { no: 4, name: "latest_reply", kind: "message", T: Message$1 },
    { no: 5, name: "direct_message_participant_user_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ThreadSearchContext {
    return new ThreadSearchContext().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ThreadSearchContext {
    return new ThreadSearchContext().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ThreadSearchContext {
    return new ThreadSearchContext().fromJsonString(jsonString, options);
  }

  static equals(a: ThreadSearchContext | PlainMessage<ThreadSearchContext> | undefined, b: ThreadSearchContext | PlainMessage<ThreadSearchContext> | undefined): boolean {
    return proto3.util.equals(ThreadSearchContext, a, b);
  }
}

/**
 * Request for current message-search availability.
 *
 * @generated from message chatto.api.v1.GetStatusRequest
 */
export class GetStatusRequest extends Message<GetStatusRequest> {
  constructor(data?: PartialMessage<GetStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStatusRequest {
    return new GetStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStatusRequest {
    return new GetStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStatusRequest {
    return new GetStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetStatusRequest | PlainMessage<GetStatusRequest> | undefined, b: GetStatusRequest | PlainMessage<GetStatusRequest> | undefined): boolean {
    return proto3.util.equals(GetStatusRequest, a, b);
  }
}

/**
 * Current message-search availability.
 *
 * @generated from message chatto.api.v1.GetStatusResponse
 */
export class GetStatusResponse extends Message<GetStatusResponse> {
  /**
   * Current feature/provider state.
   *
   * @generated from field: chatto.api.v1.MessageSearchState state = 1;
   */
  state = MessageSearchState.UNSPECIFIED;

  /**
   * Suggested delay before checking again while search is not ready.
   *
   * @generated from field: google.protobuf.Duration retry_after = 4;
   */
  retryAfter?: Duration;

  constructor(data?: PartialMessage<GetStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "state", kind: "enum", T: proto3.getEnumType(MessageSearchState) },
    { no: 4, name: "retry_after", kind: "message", T: Duration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStatusResponse {
    return new GetStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStatusResponse {
    return new GetStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStatusResponse {
    return new GetStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetStatusResponse | PlainMessage<GetStatusResponse> | undefined, b: GetStatusResponse | PlainMessage<GetStatusResponse> | undefined): boolean {
    return proto3.util.equals(GetStatusResponse, a, b);
  }
}
