// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/permissions.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListEffectivePermissionsRequest, ListEffectivePermissionsResponse } from "./permissions_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Read-only effective authority. Configuration and explanations remain in
 * chatto.admin.v1.AdminPermissionService.
 *
 * @generated from service chatto.api.v1.PermissionService
 */
export const PermissionService = {
  typeName: "chatto.api.v1.PermissionService",
  methods: {
    /**
     * Any authenticated member may read a bot's effective permissions. Human
     * targets require user.manage-permissions, including self-targeted reads.
     * Bot authority includes the owner's current limits. Hidden room identities,
     * stored grants, credentials, and individual DM participants are not exposed.
     * Missing or deleted targets return NOT_FOUND. Each call returns the complete
     * visible set from one coherent read, without pagination or truncation. Clients
     * should refresh visible views (the bundled client uses 30 seconds) and clear
     * the view on close or read failure.
     *
     * @generated from rpc chatto.api.v1.PermissionService.ListEffectivePermissions
     */
    listEffectivePermissions: {
      name: "ListEffectivePermissions",
      I: ListEffectivePermissionsRequest,
      O: ListEffectivePermissionsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
