// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file chatto/admin/v1/event_log.proto (package chatto.admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chatto/admin/v1/event_log.proto.
 */
export const file_chatto_admin_v1_event_log: GenFile = /*@__PURE__*/
  fileDesc("Ch9jaGF0dG8vYWRtaW4vdjEvZXZlbnRfbG9nLnByb3RvEg9jaGF0dG8uYWRtaW4udjEiowEKE0FkbWluRXZlbnRMb2dGaWx0ZXISEgoKZXZlbnRfdHlwZRgBIAEoCRIQCghhY3Rvcl9pZBgCIAEoCRIzCg9jcmVhdGVkX2F0X2Zyb20YAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjEKDWNyZWF0ZWRfYXRfdG8YBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIngKEUxpc3RFdmVudHNSZXF1ZXN0Eg0KBWxpbWl0GAEgASgFEhMKBmJlZm9yZRgCIAEoCUgAiAEBEjQKBmZpbHRlchgDIAEoCzIkLmNoYXR0by5hZG1pbi52MS5BZG1pbkV2ZW50TG9nRmlsdGVyQgkKB19iZWZvcmUi2wEKEkxpc3RFdmVudHNSZXNwb25zZRI0CgdlbnRyaWVzGAEgAygLMiMuY2hhdHRvLmFkbWluLnYxLkFkbWluRXZlbnRMb2dFbnRyeRIRCgloYXNfb2xkZXIYAiABKAgSFwoKZW5kX2N1cnNvchgDIAEoCUgAiAEBEhMKC3RvdGFsX2NvdW50GAQgASgDEhUKDXNjYW5uZWRfY291bnQYBSABKAUSEgoKc2Nhbl9saW1pdBgGIAEoBRIUCgxzY2FuX2xpbWl0ZWQYByABKAhCDQoLX2VuZF9jdXJzb3IiFwoVTGlzdEV2ZW50VHlwZXNSZXF1ZXN0Ii0KFkxpc3RFdmVudFR5cGVzUmVzcG9uc2USEwoLZXZlbnRfdHlwZXMYASADKAkiIwoPR2V0RXZlbnRSZXF1ZXN0EhAKCHNlcXVlbmNlGAEgASgJIkYKEEdldEV2ZW50UmVzcG9uc2USMgoFZW50cnkYASABKAsyIy5jaGF0dG8uYWRtaW4udjEuQWRtaW5FdmVudExvZ0VudHJ5IuMBChJBZG1pbkV2ZW50TG9nRW50cnkSEAoIc2VxdWVuY2UYASABKAkSDwoHc3ViamVjdBgCIAEoCRIWCg5hZ2dyZWdhdGVfdHlwZRgDIAEoCRIUCgxhZ2dyZWdhdGVfaWQYBCABKAkSEgoKZXZlbnRfdHlwZRgFIAEoCRIQCghldmVudF9pZBgGIAEoCRIQCghhY3Rvcl9pZBgHIAEoCRIuCgpjcmVhdGVkX2F0GAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIUCgxwYXlsb2FkX2pzb24YCSABKAkyoQIKFEFkbWluRXZlbnRMb2dTZXJ2aWNlElUKCkxpc3RFdmVudHMSIi5jaGF0dG8uYWRtaW4udjEuTGlzdEV2ZW50c1JlcXVlc3QaIy5jaGF0dG8uYWRtaW4udjEuTGlzdEV2ZW50c1Jlc3BvbnNlEmEKDkxpc3RFdmVudFR5cGVzEiYuY2hhdHRvLmFkbWluLnYxLkxpc3RFdmVudFR5cGVzUmVxdWVzdBonLmNoYXR0by5hZG1pbi52MS5MaXN0RXZlbnRUeXBlc1Jlc3BvbnNlEk8KCEdldEV2ZW50EiAuY2hhdHRvLmFkbWluLnYxLkdldEV2ZW50UmVxdWVzdBohLmNoYXR0by5hZG1pbi52MS5HZXRFdmVudFJlc3BvbnNlQrcBChNjb20uY2hhdHRvLmFkbWluLnYxQg1FdmVudExvZ1Byb3RvUAFaM2htYW5zLmRlL2NoYXR0by9pbnRlcm5hbC9wYi9jaGF0dG8vYWRtaW4vdjE7YWRtaW52MaICA0NBWKoCD0NoYXR0by5BZG1pbi5WMcoCD0NoYXR0b1xBZG1pblxWMeICG0NoYXR0b1xBZG1pblxWMVxHUEJNZXRhZGF0YeoCEUNoYXR0bzo6QWRtaW46OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Filter for owner/auditor event-log inspection.
 *
 * @generated from message chatto.admin.v1.AdminEventLogFilter
 */
export type AdminEventLogFilter = Message<"chatto.admin.v1.AdminEventLogFilter"> & {
  /**
   * Event oneof payload type, such as MessagePostedEvent.
   *
   * @generated from field: string event_type = 1;
   */
  eventType: string;

  /**
   * Actor user ID.
   *
   * @generated from field: string actor_id = 2;
   */
  actorId: string;

  /**
   * Inclusive lower creation timestamp bound.
   *
   * @generated from field: google.protobuf.Timestamp created_at_from = 3;
   */
  createdAtFrom?: Timestamp | undefined;

  /**
   * Inclusive upper creation timestamp bound.
   *
   * @generated from field: google.protobuf.Timestamp created_at_to = 4;
   */
  createdAtTo?: Timestamp | undefined;
};

/**
 * Describes the message chatto.admin.v1.AdminEventLogFilter.
 * Use `create(AdminEventLogFilterSchema)` to create a new message.
 */
export const AdminEventLogFilterSchema: GenMessage<AdminEventLogFilter> = /*@__PURE__*/
  messageDesc(file_chatto_admin_v1_event_log, 0);

/**
 * Request to list durable EVT entries newest-first.
 *
 * @generated from message chatto.admin.v1.ListEventsRequest
 */
export type ListEventsRequest = Message<"chatto.admin.v1.ListEventsRequest"> & {
  /**
   * Maximum entries. Zero uses 50; values above 200 use 200.
   *
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * Exclusive sequence cursor. Returned entries are older than this sequence.
   *
   * @generated from field: optional string before = 2;
   */
  before?: string | undefined;

  /**
   * Optional filter. Filtered scans inspect a bounded window per request.
   *
   * @generated from field: chatto.admin.v1.AdminEventLogFilter filter = 3;
   */
  filter?: AdminEventLogFilter | undefined;
};

/**
 * Describes the message chatto.admin.v1.ListEventsRequest.
 * Use `create(ListEventsRequestSchema)` to create a new message.
 */
export const ListEventsRequestSchema: GenMessage<ListEventsRequest> = /*@__PURE__*/
  messageDesc(file_chatto_admin_v1_event_log, 1);

/**
 * Newest-first page of durable EVT entries.
 *
 * @generated from message chatto.admin.v1.ListEventsResponse
 */
export type ListEventsResponse = Message<"chatto.admin.v1.ListEventsResponse"> & {
  /**
   * Event-log rows.
   *
   * @generated from field: repeated chatto.admin.v1.AdminEventLogEntry entries = 1;
   */
  entries: AdminEventLogEntry[];

  /**
   * Whether older rows may be fetched with end_cursor.
   *
   * @generated from field: bool has_older = 2;
   */
  hasOlder: boolean;

  /**
   * Sequence cursor for loading older rows.
   *
   * @generated from field: optional string end_cursor = 3;
   */
  endCursor?: string | undefined;

  /**
   * Total EVT message count reported by JetStream.
   *
   * @generated from field: int64 total_count = 4;
   */
  totalCount: bigint;

  /**
   * Number of stream sequences inspected while building this page.
   *
   * @generated from field: int32 scanned_count = 5;
   */
  scannedCount: number;

  /**
   * Maximum number of stream sequences inspected for this page.
   *
   * @generated from field: int32 scan_limit = 6;
   */
  scanLimit: number;

  /**
   * True when a filtered request reached scan_limit before finding a full page.
   *
   * @generated from field: bool scan_limited = 7;
   */
  scanLimited: boolean;
};

/**
 * Describes the message chatto.admin.v1.ListEventsResponse.
 * Use `create(ListEventsResponseSchema)` to create a new message.
 */
export const ListEventsResponseSchema: GenMessage<ListEventsResponse> = /*@__PURE__*/
  messageDesc(file_chatto_admin_v1_event_log, 2);

/**
 * Request to list filterable event types.
 *
 * @generated from message chatto.admin.v1.ListEventTypesRequest
 */
export type ListEventTypesRequest = Message<"chatto.admin.v1.ListEventTypesRequest"> & {
};

/**
 * Describes the message chatto.admin.v1.ListEventTypesRequest.
 * Use `create(ListEventTypesRequestSchema)` to create a new message.
 */
export const ListEventTypesRequestSchema: GenMessage<ListEventTypesRequest> = /*@__PURE__*/
  messageDesc(file_chatto_admin_v1_event_log, 3);

/**
 * Finite snapshot of event types accepted by event-log filters.
 *
 * @generated from message chatto.admin.v1.ListEventTypesResponse
 */
export type ListEventTypesResponse = Message<"chatto.admin.v1.ListEventTypesResponse"> & {
  /**
   * Sorted event type names.
   *
   * @generated from field: repeated string event_types = 1;
   */
  eventTypes: string[];
};

/**
 * Describes the message chatto.admin.v1.ListEventTypesResponse.
 * Use `create(ListEventTypesResponseSchema)` to create a new message.
 */
export const ListEventTypesResponseSchema: GenMessage<ListEventTypesResponse> = /*@__PURE__*/
  messageDesc(file_chatto_admin_v1_event_log, 4);

/**
 * Request to read one durable EVT entry by stream sequence.
 *
 * @generated from message chatto.admin.v1.GetEventRequest
 */
export type GetEventRequest = Message<"chatto.admin.v1.GetEventRequest"> & {
  /**
   * Required EVT stream sequence.
   *
   * @generated from field: string sequence = 1;
   */
  sequence: string;
};

/**
 * Describes the message chatto.admin.v1.GetEventRequest.
 * Use `create(GetEventRequestSchema)` to create a new message.
 */
export const GetEventRequestSchema: GenMessage<GetEventRequest> = /*@__PURE__*/
  messageDesc(file_chatto_admin_v1_event_log, 5);

/**
 * Result of reading one durable EVT entry.
 *
 * @generated from message chatto.admin.v1.GetEventResponse
 */
export type GetEventResponse = Message<"chatto.admin.v1.GetEventResponse"> & {
  /**
   * Requested event-log entry.
   *
   * @generated from field: chatto.admin.v1.AdminEventLogEntry entry = 1;
   */
  entry?: AdminEventLogEntry | undefined;
};

/**
 * Describes the message chatto.admin.v1.GetEventResponse.
 * Use `create(GetEventResponseSchema)` to create a new message.
 */
export const GetEventResponseSchema: GenMessage<GetEventResponse> = /*@__PURE__*/
  messageDesc(file_chatto_admin_v1_event_log, 6);

/**
 * One durable EVT entry decoded for operator inspection.
 *
 * @generated from message chatto.admin.v1.AdminEventLogEntry
 */
export type AdminEventLogEntry = Message<"chatto.admin.v1.AdminEventLogEntry"> & {
  /**
   * EVT stream sequence.
   *
   * @generated from field: string sequence = 1;
   */
  sequence: string;

  /**
   * NATS subject.
   *
   * @generated from field: string subject = 2;
   */
  subject: string;

  /**
   * Aggregate type parsed from the subject.
   *
   * @generated from field: string aggregate_type = 3;
   */
  aggregateType: string;

  /**
   * Aggregate ID parsed from the subject.
   *
   * @generated from field: string aggregate_id = 4;
   */
  aggregateId: string;

  /**
   * Event oneof payload type, or decode-error when decoding failed.
   *
   * @generated from field: string event_type = 5;
   */
  eventType: string;

  /**
   * Durable event ID.
   *
   * @generated from field: string event_id = 6;
   */
  eventId: string;

  /**
   * Actor user ID stored on the event.
   *
   * @generated from field: string actor_id = 7;
   */
  actorId: string;

  /**
   * Event creation timestamp.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp | undefined;

  /**
   * Pretty-printed, sanitized JSON representation of the event payload.
   * Password verifiers are omitted.
   *
   * @generated from field: string payload_json = 9;
   */
  payloadJson: string;
};

/**
 * Describes the message chatto.admin.v1.AdminEventLogEntry.
 * Use `create(AdminEventLogEntrySchema)` to create a new message.
 */
export const AdminEventLogEntrySchema: GenMessage<AdminEventLogEntry> = /*@__PURE__*/
  messageDesc(file_chatto_admin_v1_event_log, 7);

/**
 * Provides server-admin audit/event-log diagnostics.
 *
 * @generated from service chatto.admin.v1.AdminEventLogService
 */
export const AdminEventLogService: GenService<{
  /**
   * Lists durable EVT entries newest-first. Requires admin.view-audit.
   *
   * @generated from rpc chatto.admin.v1.AdminEventLogService.ListEvents
   */
  listEvents: {
    methodKind: "unary";
    input: typeof ListEventsRequestSchema;
    output: typeof ListEventsResponseSchema;
  },
  /**
   * Lists filterable event type names as a finite snapshot. Requires
   * admin.view-audit.
   *
   * @generated from rpc chatto.admin.v1.AdminEventLogService.ListEventTypes
   */
  listEventTypes: {
    methodKind: "unary";
    input: typeof ListEventTypesRequestSchema;
    output: typeof ListEventTypesResponseSchema;
  },
  /**
   * Reads one durable EVT entry by stream sequence. Requires admin.view-audit.
   * Returns NOT_FOUND when the requested sequence does not exist.
   *
   * @generated from rpc chatto.admin.v1.AdminEventLogService.GetEvent
   */
  getEvent: {
    methodKind: "unary";
    input: typeof GetEventRequestSchema;
    output: typeof GetEventResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_chatto_admin_v1_event_log, 0);
