// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file chatto/clientsync/api/v1/client_sync.proto (package chatto.clientsync.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { FieldMask, Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * TimeFormat controls how times are displayed across the user's Chatto clients.
 *
 * @generated from enum chatto.clientsync.api.v1.TimeFormat
 */
export enum TimeFormat {
  /**
   * @generated from enum value: TIME_FORMAT_UNSPECIFIED = 0;
   */
  TIME_FORMAT_UNSPECIFIED = 0,

  /**
   * @generated from enum value: TIME_FORMAT_12_HOUR = 1;
   */
  TIME_FORMAT_12_HOUR = 1,

  /**
   * @generated from enum value: TIME_FORMAT_24_HOUR = 2;
   */
  TIME_FORMAT_24_HOUR = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(TimeFormat)
proto3.util.setEnumType(TimeFormat, "chatto.clientsync.api.v1.TimeFormat", [
  { no: 0, name: "TIME_FORMAT_UNSPECIFIED" },
  { no: 1, name: "TIME_FORMAT_12_HOUR" },
  { no: 2, name: "TIME_FORMAT_24_HOUR" },
]);

/**
 * Preferences contains personal settings which should follow the authenticated
 * user between Chatto clients.
 *
 * @generated from message chatto.clientsync.api.v1.Preferences
 */
export class Preferences extends Message<Preferences> {
  /**
   * BCP 47 locale tag, such as en-GB or de.
   *
   * @generated from field: optional string locale = 1;
   */
  locale?: string;

  /**
   * IANA timezone name. Empty means to use the client timezone.
   *
   * @generated from field: optional string timezone = 2;
   */
  timezone?: string;

  /**
   * Preferred time display format.
   *
   * @generated from field: optional chatto.clientsync.api.v1.TimeFormat time_format = 3;
   */
  timeFormat?: TimeFormat;

  constructor(data?: PartialMessage<Preferences>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.Preferences";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "locale", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "timezone", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "time_format", kind: "enum", T: proto3.getEnumType(TimeFormat), opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Preferences {
    return new Preferences().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Preferences {
    return new Preferences().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Preferences {
    return new Preferences().fromJsonString(jsonString, options);
  }

  static equals(a: Preferences | PlainMessage<Preferences> | undefined, b: Preferences | PlainMessage<Preferences> | undefined): boolean {
    return proto3.util.equals(Preferences, a, b);
  }
}

/**
 * KnownServer describes one server in the user's portable server directory.
 * Authentication credentials are device-local and are never included.
 *
 * @generated from message chatto.clientsync.api.v1.KnownServer
 */
export class KnownServer extends Message<KnownServer> {
  /**
   * Opaque identifier within this portable directory. Clients must match
   * servers by canonical URL origin rather than treating this as global identity.
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Canonical HTTP or HTTPS origin for the server.
   *
   * @generated from field: string url = 2;
   */
  url = "";

  /**
   * Last discovered display name.
   *
   * @generated from field: string name = 3;
   */
  name = "";

  /**
   * Last discovered server icon URL.
   *
   * @generated from field: optional string icon_url = 4;
   */
  iconUrl?: string;

  /**
   * Time this entry was first added to the portable directory.
   *
   * @generated from field: google.protobuf.Timestamp added_at = 5;
   */
  addedAt?: Timestamp;

  constructor(data?: PartialMessage<KnownServer>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.KnownServer";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "icon_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "added_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KnownServer {
    return new KnownServer().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KnownServer {
    return new KnownServer().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KnownServer {
    return new KnownServer().fromJsonString(jsonString, options);
  }

  static equals(a: KnownServer | PlainMessage<KnownServer> | undefined, b: KnownServer | PlainMessage<KnownServer> | undefined): boolean {
    return proto3.util.equals(KnownServer, a, b);
  }
}

/**
 * GetPreferencesRequest selects the authenticated user's preferences.
 *
 * @generated from message chatto.clientsync.api.v1.GetPreferencesRequest
 */
export class GetPreferencesRequest extends Message<GetPreferencesRequest> {
  constructor(data?: PartialMessage<GetPreferencesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.GetPreferencesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPreferencesRequest {
    return new GetPreferencesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPreferencesRequest {
    return new GetPreferencesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPreferencesRequest {
    return new GetPreferencesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetPreferencesRequest | PlainMessage<GetPreferencesRequest> | undefined, b: GetPreferencesRequest | PlainMessage<GetPreferencesRequest> | undefined): boolean {
    return proto3.util.equals(GetPreferencesRequest, a, b);
  }
}

/**
 * GetPreferencesResponse returns the authenticated user's portable preferences.
 *
 * @generated from message chatto.clientsync.api.v1.GetPreferencesResponse
 */
export class GetPreferencesResponse extends Message<GetPreferencesResponse> {
  /**
   * Current preferences; present even when no fields have been set.
   *
   * @generated from field: chatto.clientsync.api.v1.Preferences preferences = 1;
   */
  preferences?: Preferences;

  constructor(data?: PartialMessage<GetPreferencesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.GetPreferencesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "preferences", kind: "message", T: Preferences },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPreferencesResponse {
    return new GetPreferencesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPreferencesResponse {
    return new GetPreferencesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPreferencesResponse {
    return new GetPreferencesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetPreferencesResponse | PlainMessage<GetPreferencesResponse> | undefined, b: GetPreferencesResponse | PlainMessage<GetPreferencesResponse> | undefined): boolean {
    return proto3.util.equals(GetPreferencesResponse, a, b);
  }
}

/**
 * UpdatePreferencesRequest applies selected portable preference fields.
 *
 * @generated from message chatto.clientsync.api.v1.UpdatePreferencesRequest
 */
export class UpdatePreferencesRequest extends Message<UpdatePreferencesRequest> {
  /**
   * Replacement values for fields selected by update_mask.
   *
   * @generated from field: chatto.clientsync.api.v1.Preferences preferences = 1;
   */
  preferences?: Preferences;

  /**
   * Fields to replace. Supported paths are locale, timezone, and time_format.
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;

  constructor(data?: PartialMessage<UpdatePreferencesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.UpdatePreferencesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "preferences", kind: "message", T: Preferences },
    { no: 2, name: "update_mask", kind: "message", T: FieldMask },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdatePreferencesRequest {
    return new UpdatePreferencesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdatePreferencesRequest {
    return new UpdatePreferencesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdatePreferencesRequest {
    return new UpdatePreferencesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdatePreferencesRequest | PlainMessage<UpdatePreferencesRequest> | undefined, b: UpdatePreferencesRequest | PlainMessage<UpdatePreferencesRequest> | undefined): boolean {
    return proto3.util.equals(UpdatePreferencesRequest, a, b);
  }
}

/**
 * UpdatePreferencesResponse returns the preferences after the update.
 *
 * @generated from message chatto.clientsync.api.v1.UpdatePreferencesResponse
 */
export class UpdatePreferencesResponse extends Message<UpdatePreferencesResponse> {
  /**
   * Updated portable preferences.
   *
   * @generated from field: chatto.clientsync.api.v1.Preferences preferences = 1;
   */
  preferences?: Preferences;

  constructor(data?: PartialMessage<UpdatePreferencesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.UpdatePreferencesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "preferences", kind: "message", T: Preferences },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdatePreferencesResponse {
    return new UpdatePreferencesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdatePreferencesResponse {
    return new UpdatePreferencesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdatePreferencesResponse {
    return new UpdatePreferencesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdatePreferencesResponse | PlainMessage<UpdatePreferencesResponse> | undefined, b: UpdatePreferencesResponse | PlainMessage<UpdatePreferencesResponse> | undefined): boolean {
    return proto3.util.equals(UpdatePreferencesResponse, a, b);
  }
}

/**
 * ListKnownServersRequest selects the authenticated user's server directory.
 *
 * @generated from message chatto.clientsync.api.v1.ListKnownServersRequest
 */
export class ListKnownServersRequest extends Message<ListKnownServersRequest> {
  constructor(data?: PartialMessage<ListKnownServersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.ListKnownServersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListKnownServersRequest {
    return new ListKnownServersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListKnownServersRequest {
    return new ListKnownServersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListKnownServersRequest {
    return new ListKnownServersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListKnownServersRequest | PlainMessage<ListKnownServersRequest> | undefined, b: ListKnownServersRequest | PlainMessage<ListKnownServersRequest> | undefined): boolean {
    return proto3.util.equals(ListKnownServersRequest, a, b);
  }
}

/**
 * ListKnownServersResponse returns the portable server directory and home marker.
 *
 * @generated from message chatto.clientsync.api.v1.ListKnownServersResponse
 */
export class ListKnownServersResponse extends Message<ListKnownServersResponse> {
  /**
   * Servers known to the user, without authentication credentials.
   *
   * @generated from field: repeated chatto.clientsync.api.v1.KnownServer servers = 1;
   */
  servers: KnownServer[] = [];

  /**
   * ID of the server designated as home, when one has been chosen.
   *
   * @generated from field: optional string home_server_id = 2;
   */
  homeServerId?: string;

  constructor(data?: PartialMessage<ListKnownServersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.ListKnownServersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "servers", kind: "message", T: KnownServer, repeated: true },
    { no: 2, name: "home_server_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListKnownServersResponse {
    return new ListKnownServersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListKnownServersResponse {
    return new ListKnownServersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListKnownServersResponse {
    return new ListKnownServersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListKnownServersResponse | PlainMessage<ListKnownServersResponse> | undefined, b: ListKnownServersResponse | PlainMessage<ListKnownServersResponse> | undefined): boolean {
    return proto3.util.equals(ListKnownServersResponse, a, b);
  }
}

/**
 * CreateKnownServerRequest adds one server to the portable directory.
 *
 * @generated from message chatto.clientsync.api.v1.CreateKnownServerRequest
 */
export class CreateKnownServerRequest extends Message<CreateKnownServerRequest> {
  /**
   * Server metadata to add. added_at is assigned by the server.
   *
   * @generated from field: chatto.clientsync.api.v1.KnownServer server = 1;
   */
  server?: KnownServer;

  constructor(data?: PartialMessage<CreateKnownServerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.CreateKnownServerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "server", kind: "message", T: KnownServer },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateKnownServerRequest {
    return new CreateKnownServerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateKnownServerRequest {
    return new CreateKnownServerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateKnownServerRequest {
    return new CreateKnownServerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateKnownServerRequest | PlainMessage<CreateKnownServerRequest> | undefined, b: CreateKnownServerRequest | PlainMessage<CreateKnownServerRequest> | undefined): boolean {
    return proto3.util.equals(CreateKnownServerRequest, a, b);
  }
}

/**
 * CreateKnownServerResponse returns the created directory entry.
 *
 * @generated from message chatto.clientsync.api.v1.CreateKnownServerResponse
 */
export class CreateKnownServerResponse extends Message<CreateKnownServerResponse> {
  /**
   * Created server entry with its server-assigned added_at value.
   *
   * @generated from field: chatto.clientsync.api.v1.KnownServer server = 1;
   */
  server?: KnownServer;

  constructor(data?: PartialMessage<CreateKnownServerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.CreateKnownServerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "server", kind: "message", T: KnownServer },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateKnownServerResponse {
    return new CreateKnownServerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateKnownServerResponse {
    return new CreateKnownServerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateKnownServerResponse {
    return new CreateKnownServerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateKnownServerResponse | PlainMessage<CreateKnownServerResponse> | undefined, b: CreateKnownServerResponse | PlainMessage<CreateKnownServerResponse> | undefined): boolean {
    return proto3.util.equals(CreateKnownServerResponse, a, b);
  }
}

/**
 * UpdateKnownServerRequest updates discovery metadata for one known server.
 *
 * @generated from message chatto.clientsync.api.v1.UpdateKnownServerRequest
 */
export class UpdateKnownServerRequest extends Message<UpdateKnownServerRequest> {
  /**
   * Server ID and replacement values for fields selected by update_mask.
   *
   * @generated from field: chatto.clientsync.api.v1.KnownServer server = 1;
   */
  server?: KnownServer;

  /**
   * Fields to replace. Supported paths are url, name, and icon_url.
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;

  constructor(data?: PartialMessage<UpdateKnownServerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.UpdateKnownServerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "server", kind: "message", T: KnownServer },
    { no: 2, name: "update_mask", kind: "message", T: FieldMask },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateKnownServerRequest {
    return new UpdateKnownServerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateKnownServerRequest {
    return new UpdateKnownServerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateKnownServerRequest {
    return new UpdateKnownServerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateKnownServerRequest | PlainMessage<UpdateKnownServerRequest> | undefined, b: UpdateKnownServerRequest | PlainMessage<UpdateKnownServerRequest> | undefined): boolean {
    return proto3.util.equals(UpdateKnownServerRequest, a, b);
  }
}

/**
 * UpdateKnownServerResponse returns the directory entry after the update.
 *
 * @generated from message chatto.clientsync.api.v1.UpdateKnownServerResponse
 */
export class UpdateKnownServerResponse extends Message<UpdateKnownServerResponse> {
  /**
   * Updated known-server entry.
   *
   * @generated from field: chatto.clientsync.api.v1.KnownServer server = 1;
   */
  server?: KnownServer;

  constructor(data?: PartialMessage<UpdateKnownServerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.UpdateKnownServerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "server", kind: "message", T: KnownServer },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateKnownServerResponse {
    return new UpdateKnownServerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateKnownServerResponse {
    return new UpdateKnownServerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateKnownServerResponse {
    return new UpdateKnownServerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateKnownServerResponse | PlainMessage<UpdateKnownServerResponse> | undefined, b: UpdateKnownServerResponse | PlainMessage<UpdateKnownServerResponse> | undefined): boolean {
    return proto3.util.equals(UpdateKnownServerResponse, a, b);
  }
}

/**
 * DeleteKnownServerRequest removes a non-home server from the directory.
 *
 * @generated from message chatto.clientsync.api.v1.DeleteKnownServerRequest
 */
export class DeleteKnownServerRequest extends Message<DeleteKnownServerRequest> {
  /**
   * ID of the server to remove.
   *
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<DeleteKnownServerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.DeleteKnownServerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteKnownServerRequest {
    return new DeleteKnownServerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteKnownServerRequest {
    return new DeleteKnownServerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteKnownServerRequest {
    return new DeleteKnownServerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteKnownServerRequest | PlainMessage<DeleteKnownServerRequest> | undefined, b: DeleteKnownServerRequest | PlainMessage<DeleteKnownServerRequest> | undefined): boolean {
    return proto3.util.equals(DeleteKnownServerRequest, a, b);
  }
}

/**
 * DeleteKnownServerResponse acknowledges an idempotent directory removal.
 *
 * @generated from message chatto.clientsync.api.v1.DeleteKnownServerResponse
 */
export class DeleteKnownServerResponse extends Message<DeleteKnownServerResponse> {
  constructor(data?: PartialMessage<DeleteKnownServerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.DeleteKnownServerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteKnownServerResponse {
    return new DeleteKnownServerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteKnownServerResponse {
    return new DeleteKnownServerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteKnownServerResponse {
    return new DeleteKnownServerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteKnownServerResponse | PlainMessage<DeleteKnownServerResponse> | undefined, b: DeleteKnownServerResponse | PlainMessage<DeleteKnownServerResponse> | undefined): boolean {
    return proto3.util.equals(DeleteKnownServerResponse, a, b);
  }
}

/**
 * SetHomeServerRequest chooses an existing directory entry as home.
 *
 * @generated from message chatto.clientsync.api.v1.SetHomeServerRequest
 */
export class SetHomeServerRequest extends Message<SetHomeServerRequest> {
  /**
   * ID of the known server to designate as home.
   *
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<SetHomeServerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.SetHomeServerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetHomeServerRequest {
    return new SetHomeServerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetHomeServerRequest {
    return new SetHomeServerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetHomeServerRequest {
    return new SetHomeServerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SetHomeServerRequest | PlainMessage<SetHomeServerRequest> | undefined, b: SetHomeServerRequest | PlainMessage<SetHomeServerRequest> | undefined): boolean {
    return proto3.util.equals(SetHomeServerRequest, a, b);
  }
}

/**
 * SetHomeServerResponse returns the newly designated home server.
 *
 * @generated from message chatto.clientsync.api.v1.SetHomeServerResponse
 */
export class SetHomeServerResponse extends Message<SetHomeServerResponse> {
  /**
   * Known-server entry now designated as home.
   *
   * @generated from field: chatto.clientsync.api.v1.KnownServer server = 1;
   */
  server?: KnownServer;

  constructor(data?: PartialMessage<SetHomeServerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.clientsync.api.v1.SetHomeServerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "server", kind: "message", T: KnownServer },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetHomeServerResponse {
    return new SetHomeServerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetHomeServerResponse {
    return new SetHomeServerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetHomeServerResponse {
    return new SetHomeServerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SetHomeServerResponse | PlainMessage<SetHomeServerResponse> | undefined, b: SetHomeServerResponse | PlainMessage<SetHomeServerResponse> | undefined): boolean {
    return proto3.util.equals(SetHomeServerResponse, a, b);
  }
}
