# The Compose development image contains toolchains only. Allow the small set
# of files used as Compose Watch triggers, but do not send application source.
**
!docker/
!docker/Dockerfile.dev
!docker/compose-dev-entrypoint.sh
!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!.npmrc
!apps/
!apps/frontend/
!apps/frontend/package.json
!packages/
!packages/api-types/
!packages/api-types/package.json
!packages/lingua/
!packages/lingua/package.json
!authling/
!authling/package.json
!authling/pnpm-lock.yaml
!authling/pnpm-workspace.yaml
!authling/.npmrc
!authling/web/
!authling/web/package.json
