# Ignore everything by default.
*

# Release workflow builds the frontend once, then packages the static output.
!apps/frontend/build/
!apps/frontend/nginx.conf
!LICENSES/
!LICENSES/AGPL-3.0-or-later.txt
!NOTICE
