// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/admin/v1/oauth_clients.proto

package adminv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How a public OAuth client establishes its identity with this server.
type OAuthClientSource int32

const (
	// The server does not recognize the source value.
	OAuthClientSource_OAUTH_CLIENT_SOURCE_UNSPECIFIED OAuthClientSource = 0
	// The client identifies itself with an HTTPS Client ID Metadata Document.
	OAuthClientSource_OAUTH_CLIENT_SOURCE_CIMD OAuthClientSource = 1
	// The client uses a registration built into this Chatto release.
	OAuthClientSource_OAUTH_CLIENT_SOURCE_BUILT_IN OAuthClientSource = 2
)

// Enum value maps for OAuthClientSource.
var (
	OAuthClientSource_name = map[int32]string{
		0: "OAUTH_CLIENT_SOURCE_UNSPECIFIED",
		1: "OAUTH_CLIENT_SOURCE_CIMD",
		2: "OAUTH_CLIENT_SOURCE_BUILT_IN",
	}
	OAuthClientSource_value = map[string]int32{
		"OAUTH_CLIENT_SOURCE_UNSPECIFIED": 0,
		"OAUTH_CLIENT_SOURCE_CIMD":        1,
		"OAUTH_CLIENT_SOURCE_BUILT_IN":    2,
	}
)

func (x OAuthClientSource) Enum() *OAuthClientSource {
	p := new(OAuthClientSource)
	*p = x
	return p
}

func (x OAuthClientSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OAuthClientSource) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_admin_v1_oauth_clients_proto_enumTypes[0].Descriptor()
}

func (OAuthClientSource) Type() protoreflect.EnumType {
	return &file_chatto_admin_v1_oauth_clients_proto_enumTypes[0]
}

func (x OAuthClientSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OAuthClientSource.Descriptor instead.
func (OAuthClientSource) EnumDescriptor() ([]byte, []int) {
	return file_chatto_admin_v1_oauth_clients_proto_rawDescGZIP(), []int{0}
}

// Administrator policy for a public OAuth client. Trusted is an informational
// blessing and never bypasses individual user consent.
type OAuthClientPolicy int32

const (
	// No valid policy was supplied.
	OAuthClientPolicy_OAUTH_CLIENT_POLICY_UNSPECIFIED OAuthClientPolicy = 0
	// The client follows the normal open-client authorization policy.
	OAuthClientPolicy_OAUTH_CLIENT_POLICY_DEFAULT OAuthClientPolicy = 1
	// Administrators have labelled the client as trusted without changing consent.
	OAuthClientPolicy_OAUTH_CLIENT_POLICY_TRUSTED OAuthClientPolicy = 2
	// The client cannot authorize or use its existing OAuth access tokens.
	OAuthClientPolicy_OAUTH_CLIENT_POLICY_BLOCKED OAuthClientPolicy = 3
)

// Enum value maps for OAuthClientPolicy.
var (
	OAuthClientPolicy_name = map[int32]string{
		0: "OAUTH_CLIENT_POLICY_UNSPECIFIED",
		1: "OAUTH_CLIENT_POLICY_DEFAULT",
		2: "OAUTH_CLIENT_POLICY_TRUSTED",
		3: "OAUTH_CLIENT_POLICY_BLOCKED",
	}
	OAuthClientPolicy_value = map[string]int32{
		"OAUTH_CLIENT_POLICY_UNSPECIFIED": 0,
		"OAUTH_CLIENT_POLICY_DEFAULT":     1,
		"OAUTH_CLIENT_POLICY_TRUSTED":     2,
		"OAUTH_CLIENT_POLICY_BLOCKED":     3,
	}
)

func (x OAuthClientPolicy) Enum() *OAuthClientPolicy {
	p := new(OAuthClientPolicy)
	*p = x
	return p
}

func (x OAuthClientPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OAuthClientPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_admin_v1_oauth_clients_proto_enumTypes[1].Descriptor()
}

func (OAuthClientPolicy) Type() protoreflect.EnumType {
	return &file_chatto_admin_v1_oauth_clients_proto_enumTypes[1]
}

func (x OAuthClientPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OAuthClientPolicy.Descriptor instead.
func (OAuthClientPolicy) EnumDescriptor() ([]byte, []int) {
	return file_chatto_admin_v1_oauth_clients_proto_rawDescGZIP(), []int{1}
}

// An OAuth client that completed at least one successful user authorization.
type OAuthClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable client identifier: a CIMD URL or built-in application URI.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Display name from validated client metadata.
	ClientName string `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	// Privacy-safe canonical origin derived from validated client metadata.
	ClientOrigin string `protobuf:"bytes,3,opt,name=client_origin,json=clientOrigin,proto3" json:"client_origin,omitempty"`
	// How the client identity was established.
	Source OAuthClientSource `protobuf:"varint,4,opt,name=source,proto3,enum=chatto.admin.v1.OAuthClientSource" json:"source,omitempty"`
	// Current server-administrator policy for the client.
	Policy OAuthClientPolicy `protobuf:"varint,5,opt,name=policy,proto3,enum=chatto.admin.v1.OAuthClientPolicy" json:"policy,omitempty"`
	// When this server first completed an authorization for the client.
	FirstAuthorizationAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=first_authorization_at,json=firstAuthorizationAt,proto3" json:"first_authorization_at,omitempty"`
	// When this server most recently completed an authorization for the client.
	LastAuthorizationAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_authorization_at,json=lastAuthorizationAt,proto3" json:"last_authorization_at,omitempty"`
	// Canonical web origins or native callback schemes seen during authorization.
	RedirectOrigins []string `protobuf:"bytes,8,rep,name=redirect_origins,json=redirectOrigins,proto3" json:"redirect_origins,omitempty"`
	// Number of distinct users who have authorized this client.
	AuthorizedUserCount uint32 `protobuf:"varint,9,opt,name=authorized_user_count,json=authorizedUserCount,proto3" json:"authorized_user_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OAuthClient) Reset() {
	*x = OAuthClient{}
	mi := &file_chatto_admin_v1_oauth_clients_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthClient) ProtoMessage() {}

func (x *OAuthClient) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_oauth_clients_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthClient.ProtoReflect.Descriptor instead.
func (*OAuthClient) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_oauth_clients_proto_rawDescGZIP(), []int{0}
}

func (x *OAuthClient) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuthClient) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *OAuthClient) GetClientOrigin() string {
	if x != nil {
		return x.ClientOrigin
	}
	return ""
}

func (x *OAuthClient) GetSource() OAuthClientSource {
	if x != nil {
		return x.Source
	}
	return OAuthClientSource_OAUTH_CLIENT_SOURCE_UNSPECIFIED
}

func (x *OAuthClient) GetPolicy() OAuthClientPolicy {
	if x != nil {
		return x.Policy
	}
	return OAuthClientPolicy_OAUTH_CLIENT_POLICY_UNSPECIFIED
}

func (x *OAuthClient) GetFirstAuthorizationAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstAuthorizationAt
	}
	return nil
}

func (x *OAuthClient) GetLastAuthorizationAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAuthorizationAt
	}
	return nil
}

func (x *OAuthClient) GetRedirectOrigins() []string {
	if x != nil {
		return x.RedirectOrigins
	}
	return nil
}

func (x *OAuthClient) GetAuthorizedUserCount() uint32 {
	if x != nil {
		return x.AuthorizedUserCount
	}
	return 0
}

// Lists OAuth clients with recorded authorizations using offset pagination.
type ListOAuthClientsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requested offset and page size.
	Page          *v1.PageRequest `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOAuthClientsRequest) Reset() {
	*x = ListOAuthClientsRequest{}
	mi := &file_chatto_admin_v1_oauth_clients_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOAuthClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOAuthClientsRequest) ProtoMessage() {}

func (x *ListOAuthClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_oauth_clients_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOAuthClientsRequest.ProtoReflect.Descriptor instead.
func (*ListOAuthClientsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_oauth_clients_proto_rawDescGZIP(), []int{1}
}

func (x *ListOAuthClientsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// One page of OAuth clients in stable first-authorization order.
type ListOAuthClientsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Clients visible to the caller in this page.
	OauthClients []*OAuthClient `protobuf:"bytes,1,rep,name=oauth_clients,json=oauthClients,proto3" json:"oauth_clients,omitempty"`
	// Total count and whether another page is available.
	Page          *v1.PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOAuthClientsResponse) Reset() {
	*x = ListOAuthClientsResponse{}
	mi := &file_chatto_admin_v1_oauth_clients_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOAuthClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOAuthClientsResponse) ProtoMessage() {}

func (x *ListOAuthClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_oauth_clients_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOAuthClientsResponse.ProtoReflect.Descriptor instead.
func (*ListOAuthClientsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_oauth_clients_proto_rawDescGZIP(), []int{2}
}

func (x *ListOAuthClientsResponse) GetOauthClients() []*OAuthClient {
	if x != nil {
		return x.OauthClients
	}
	return nil
}

func (x *ListOAuthClientsResponse) GetPage() *v1.PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// Identifies one OAuth client by its exact stable client ID.
type GetOAuthClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exact CIMD URL or built-in application URI.
	ClientId      string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAuthClientRequest) Reset() {
	*x = GetOAuthClientRequest{}
	mi := &file_chatto_admin_v1_oauth_clients_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuthClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthClientRequest) ProtoMessage() {}

func (x *GetOAuthClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_oauth_clients_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthClientRequest.ProtoReflect.Descriptor instead.
func (*GetOAuthClientRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_oauth_clients_proto_rawDescGZIP(), []int{3}
}

func (x *GetOAuthClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Returns one OAuth client with a recorded authorization.
type GetOAuthClientResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested client.
	OauthClient   *OAuthClient `protobuf:"bytes,1,opt,name=oauth_client,json=oauthClient,proto3" json:"oauth_client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAuthClientResponse) Reset() {
	*x = GetOAuthClientResponse{}
	mi := &file_chatto_admin_v1_oauth_clients_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuthClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthClientResponse) ProtoMessage() {}

func (x *GetOAuthClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_oauth_clients_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthClientResponse.ProtoReflect.Descriptor instead.
func (*GetOAuthClientResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_oauth_clients_proto_rawDescGZIP(), []int{4}
}

func (x *GetOAuthClientResponse) GetOauthClient() *OAuthClient {
	if x != nil {
		return x.OauthClient
	}
	return nil
}

// Replaces the administrative policy for one OAuth client.
type UpdateOAuthClientPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exact CIMD URL or built-in application URI.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// New complete policy value. Default removes any trusted or blocked label.
	Policy        OAuthClientPolicy `protobuf:"varint,2,opt,name=policy,proto3,enum=chatto.admin.v1.OAuthClientPolicy" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOAuthClientPolicyRequest) Reset() {
	*x = UpdateOAuthClientPolicyRequest{}
	mi := &file_chatto_admin_v1_oauth_clients_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOAuthClientPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOAuthClientPolicyRequest) ProtoMessage() {}

func (x *UpdateOAuthClientPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_oauth_clients_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOAuthClientPolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdateOAuthClientPolicyRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_oauth_clients_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOAuthClientPolicyRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UpdateOAuthClientPolicyRequest) GetPolicy() OAuthClientPolicy {
	if x != nil {
		return x.Policy
	}
	return OAuthClientPolicy_OAUTH_CLIENT_POLICY_UNSPECIFIED
}

// Returns the OAuth client with its updated policy.
type UpdateOAuthClientPolicyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated client.
	OauthClient   *OAuthClient `protobuf:"bytes,1,opt,name=oauth_client,json=oauthClient,proto3" json:"oauth_client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOAuthClientPolicyResponse) Reset() {
	*x = UpdateOAuthClientPolicyResponse{}
	mi := &file_chatto_admin_v1_oauth_clients_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOAuthClientPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOAuthClientPolicyResponse) ProtoMessage() {}

func (x *UpdateOAuthClientPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_oauth_clients_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOAuthClientPolicyResponse.ProtoReflect.Descriptor instead.
func (*UpdateOAuthClientPolicyResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_oauth_clients_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOAuthClientPolicyResponse) GetOauthClient() *OAuthClient {
	if x != nil {
		return x.OauthClient
	}
	return nil
}

var File_chatto_admin_v1_oauth_clients_proto protoreflect.FileDescriptor

const file_chatto_admin_v1_oauth_clients_proto_rawDesc = "" +
	"\n" +
	"#chatto/admin/v1/oauth_clients.proto\x12\x0fchatto.admin.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1echatto/api/v1/pagination.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x03\n" +
	"\vOAuthClient\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\tR\n" +
	"clientName\x12#\n" +
	"\rclient_origin\x18\x03 \x01(\tR\fclientOrigin\x12:\n" +
	"\x06source\x18\x04 \x01(\x0e2\".chatto.admin.v1.OAuthClientSourceR\x06source\x12:\n" +
	"\x06policy\x18\x05 \x01(\x0e2\".chatto.admin.v1.OAuthClientPolicyR\x06policy\x12P\n" +
	"\x16first_authorization_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x14firstAuthorizationAt\x12N\n" +
	"\x15last_authorization_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x13lastAuthorizationAt\x12)\n" +
	"\x10redirect_origins\x18\b \x03(\tR\x0fredirectOrigins\x122\n" +
	"\x15authorized_user_count\x18\t \x01(\rR\x13authorizedUserCount\"I\n" +
	"\x17ListOAuthClientsRequest\x12.\n" +
	"\x04page\x18\x01 \x01(\v2\x1a.chatto.api.v1.PageRequestR\x04page\"\x8a\x01\n" +
	"\x18ListOAuthClientsResponse\x12A\n" +
	"\roauth_clients\x18\x01 \x03(\v2\x1c.chatto.admin.v1.OAuthClientR\foauthClients\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.chatto.api.v1.PageInfoR\x04page\"@\n" +
	"\x15GetOAuthClientRequest\x12'\n" +
	"\tclient_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x10R\bclientId\"Y\n" +
	"\x16GetOAuthClientResponse\x12?\n" +
	"\foauth_client\x18\x01 \x01(\v2\x1c.chatto.admin.v1.OAuthClientR\voauthClient\"\x91\x01\n" +
	"\x1eUpdateOAuthClientPolicyRequest\x12'\n" +
	"\tclient_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x10R\bclientId\x12F\n" +
	"\x06policy\x18\x02 \x01(\x0e2\".chatto.admin.v1.OAuthClientPolicyB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x06policy\"b\n" +
	"\x1fUpdateOAuthClientPolicyResponse\x12?\n" +
	"\foauth_client\x18\x01 \x01(\v2\x1c.chatto.admin.v1.OAuthClientR\voauthClient*x\n" +
	"\x11OAuthClientSource\x12#\n" +
	"\x1fOAUTH_CLIENT_SOURCE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OAUTH_CLIENT_SOURCE_CIMD\x10\x01\x12 \n" +
	"\x1cOAUTH_CLIENT_SOURCE_BUILT_IN\x10\x02*\x9b\x01\n" +
	"\x11OAuthClientPolicy\x12#\n" +
	"\x1fOAUTH_CLIENT_POLICY_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bOAUTH_CLIENT_POLICY_DEFAULT\x10\x01\x12\x1f\n" +
	"\x1bOAUTH_CLIENT_POLICY_TRUSTED\x10\x02\x12\x1f\n" +
	"\x1bOAUTH_CLIENT_POLICY_BLOCKED\x10\x032\xe3\x02\n" +
	"\x17AdminOAuthClientService\x12g\n" +
	"\x10ListOAuthClients\x12(.chatto.admin.v1.ListOAuthClientsRequest\x1a).chatto.admin.v1.ListOAuthClientsResponse\x12a\n" +
	"\x0eGetOAuthClient\x12&.chatto.admin.v1.GetOAuthClientRequest\x1a'.chatto.admin.v1.GetOAuthClientResponse\x12|\n" +
	"\x17UpdateOAuthClientPolicy\x12/.chatto.admin.v1.UpdateOAuthClientPolicyRequest\x1a0.chatto.admin.v1.UpdateOAuthClientPolicyResponseB\xbb\x01\n" +
	"\x13com.chatto.admin.v1B\x11OauthClientsProtoP\x01Z3hmans.de/chatto/internal/pb/chatto/admin/v1;adminv1\xa2\x02\x03CAX\xaa\x02\x0fChatto.Admin.V1\xca\x02\x0fChatto\\Admin\\V1\xe2\x02\x1bChatto\\Admin\\V1\\GPBMetadata\xea\x02\x11Chatto::Admin::V1b\x06proto3"

var (
	file_chatto_admin_v1_oauth_clients_proto_rawDescOnce sync.Once
	file_chatto_admin_v1_oauth_clients_proto_rawDescData []byte
)

func file_chatto_admin_v1_oauth_clients_proto_rawDescGZIP() []byte {
	file_chatto_admin_v1_oauth_clients_proto_rawDescOnce.Do(func() {
		file_chatto_admin_v1_oauth_clients_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_admin_v1_oauth_clients_proto_rawDesc), len(file_chatto_admin_v1_oauth_clients_proto_rawDesc)))
	})
	return file_chatto_admin_v1_oauth_clients_proto_rawDescData
}

var file_chatto_admin_v1_oauth_clients_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chatto_admin_v1_oauth_clients_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chatto_admin_v1_oauth_clients_proto_goTypes = []any{
	(OAuthClientSource)(0),                  // 0: chatto.admin.v1.OAuthClientSource
	(OAuthClientPolicy)(0),                  // 1: chatto.admin.v1.OAuthClientPolicy
	(*OAuthClient)(nil),                     // 2: chatto.admin.v1.OAuthClient
	(*ListOAuthClientsRequest)(nil),         // 3: chatto.admin.v1.ListOAuthClientsRequest
	(*ListOAuthClientsResponse)(nil),        // 4: chatto.admin.v1.ListOAuthClientsResponse
	(*GetOAuthClientRequest)(nil),           // 5: chatto.admin.v1.GetOAuthClientRequest
	(*GetOAuthClientResponse)(nil),          // 6: chatto.admin.v1.GetOAuthClientResponse
	(*UpdateOAuthClientPolicyRequest)(nil),  // 7: chatto.admin.v1.UpdateOAuthClientPolicyRequest
	(*UpdateOAuthClientPolicyResponse)(nil), // 8: chatto.admin.v1.UpdateOAuthClientPolicyResponse
	(*timestamppb.Timestamp)(nil),           // 9: google.protobuf.Timestamp
	(*v1.PageRequest)(nil),                  // 10: chatto.api.v1.PageRequest
	(*v1.PageInfo)(nil),                     // 11: chatto.api.v1.PageInfo
}
var file_chatto_admin_v1_oauth_clients_proto_depIdxs = []int32{
	0,  // 0: chatto.admin.v1.OAuthClient.source:type_name -> chatto.admin.v1.OAuthClientSource
	1,  // 1: chatto.admin.v1.OAuthClient.policy:type_name -> chatto.admin.v1.OAuthClientPolicy
	9,  // 2: chatto.admin.v1.OAuthClient.first_authorization_at:type_name -> google.protobuf.Timestamp
	9,  // 3: chatto.admin.v1.OAuthClient.last_authorization_at:type_name -> google.protobuf.Timestamp
	10, // 4: chatto.admin.v1.ListOAuthClientsRequest.page:type_name -> chatto.api.v1.PageRequest
	2,  // 5: chatto.admin.v1.ListOAuthClientsResponse.oauth_clients:type_name -> chatto.admin.v1.OAuthClient
	11, // 6: chatto.admin.v1.ListOAuthClientsResponse.page:type_name -> chatto.api.v1.PageInfo
	2,  // 7: chatto.admin.v1.GetOAuthClientResponse.oauth_client:type_name -> chatto.admin.v1.OAuthClient
	1,  // 8: chatto.admin.v1.UpdateOAuthClientPolicyRequest.policy:type_name -> chatto.admin.v1.OAuthClientPolicy
	2,  // 9: chatto.admin.v1.UpdateOAuthClientPolicyResponse.oauth_client:type_name -> chatto.admin.v1.OAuthClient
	3,  // 10: chatto.admin.v1.AdminOAuthClientService.ListOAuthClients:input_type -> chatto.admin.v1.ListOAuthClientsRequest
	5,  // 11: chatto.admin.v1.AdminOAuthClientService.GetOAuthClient:input_type -> chatto.admin.v1.GetOAuthClientRequest
	7,  // 12: chatto.admin.v1.AdminOAuthClientService.UpdateOAuthClientPolicy:input_type -> chatto.admin.v1.UpdateOAuthClientPolicyRequest
	4,  // 13: chatto.admin.v1.AdminOAuthClientService.ListOAuthClients:output_type -> chatto.admin.v1.ListOAuthClientsResponse
	6,  // 14: chatto.admin.v1.AdminOAuthClientService.GetOAuthClient:output_type -> chatto.admin.v1.GetOAuthClientResponse
	8,  // 15: chatto.admin.v1.AdminOAuthClientService.UpdateOAuthClientPolicy:output_type -> chatto.admin.v1.UpdateOAuthClientPolicyResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_chatto_admin_v1_oauth_clients_proto_init() }
func file_chatto_admin_v1_oauth_clients_proto_init() {
	if File_chatto_admin_v1_oauth_clients_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_admin_v1_oauth_clients_proto_rawDesc), len(file_chatto_admin_v1_oauth_clients_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_admin_v1_oauth_clients_proto_goTypes,
		DependencyIndexes: file_chatto_admin_v1_oauth_clients_proto_depIdxs,
		EnumInfos:         file_chatto_admin_v1_oauth_clients_proto_enumTypes,
		MessageInfos:      file_chatto_admin_v1_oauth_clients_proto_msgTypes,
	}.Build()
	File_chatto_admin_v1_oauth_clients_proto = out.File
	file_chatto_admin_v1_oauth_clients_proto_goTypes = nil
	file_chatto_admin_v1_oauth_clients_proto_depIdxs = nil
}
