// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/credential_usage.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CredentialUsageState stores approximate last-use telemetry for credentials
// that share one owning resource. Keys identify a credential kind and opaque
// credential ID. Values are Unix times in milliseconds.
type CredentialUsageState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LastUsedUnixMillis map[string]int64       `protobuf:"bytes,1,rep,name=last_used_unix_millis,json=lastUsedUnixMillis,proto3" json:"last_used_unix_millis,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CredentialUsageState) Reset() {
	*x = CredentialUsageState{}
	mi := &file_chatto_core_v1_credential_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialUsageState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialUsageState) ProtoMessage() {}

func (x *CredentialUsageState) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_credential_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialUsageState.ProtoReflect.Descriptor instead.
func (*CredentialUsageState) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_credential_usage_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialUsageState) GetLastUsedUnixMillis() map[string]int64 {
	if x != nil {
		return x.LastUsedUnixMillis
	}
	return nil
}

var File_chatto_core_v1_credential_usage_proto protoreflect.FileDescriptor

const file_chatto_core_v1_credential_usage_proto_rawDesc = "" +
	"\n" +
	"%chatto/core/v1/credential_usage.proto\x12\x0echatto.core.v1\"\xce\x01\n" +
	"\x14CredentialUsageState\x12o\n" +
	"\x15last_used_unix_millis\x18\x01 \x03(\v2<.chatto.core.v1.CredentialUsageState.LastUsedUnixMillisEntryR\x12lastUsedUnixMillis\x1aE\n" +
	"\x17LastUsedUnixMillisEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B\xb7\x01\n" +
	"\x12com.chatto.core.v1B\x14CredentialUsageProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_credential_usage_proto_rawDescOnce sync.Once
	file_chatto_core_v1_credential_usage_proto_rawDescData []byte
)

func file_chatto_core_v1_credential_usage_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_credential_usage_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_credential_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_credential_usage_proto_rawDesc), len(file_chatto_core_v1_credential_usage_proto_rawDesc)))
	})
	return file_chatto_core_v1_credential_usage_proto_rawDescData
}

var file_chatto_core_v1_credential_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chatto_core_v1_credential_usage_proto_goTypes = []any{
	(*CredentialUsageState)(nil), // 0: chatto.core.v1.CredentialUsageState
	nil,                          // 1: chatto.core.v1.CredentialUsageState.LastUsedUnixMillisEntry
}
var file_chatto_core_v1_credential_usage_proto_depIdxs = []int32{
	1, // 0: chatto.core.v1.CredentialUsageState.last_used_unix_millis:type_name -> chatto.core.v1.CredentialUsageState.LastUsedUnixMillisEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_credential_usage_proto_init() }
func file_chatto_core_v1_credential_usage_proto_init() {
	if File_chatto_core_v1_credential_usage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_credential_usage_proto_rawDesc), len(file_chatto_core_v1_credential_usage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_credential_usage_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_credential_usage_proto_depIdxs,
		MessageInfos:      file_chatto_core_v1_credential_usage_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_credential_usage_proto = out.File
	file_chatto_core_v1_credential_usage_proto_goTypes = nil
	file_chatto_core_v1_credential_usage_proto_depIdxs = nil
}
