# SPDX-FileCopyrightText: 2026 ChattoCorp GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  mongodb:
    image: mongo@sha256:b415b12f638e2685d06c58ab7fb5943577c50fadec6d9340ef67d21aeac72070
    volumes: ['${CONFORMANCE_MONGO_VOLUME:-${CONFORMANCE_STATE}/mongo}:/data/db']
    logging: {driver: none}

  server:
    image: registry.gitlab.com/openid/conformance-suite@sha256:606dd8e8e0ba7610fbc40cb8e087b1742493dbb4f7bc1e789e319a0e4f02991d
    environment:
      BASE_URL: https://conformance.localhost:8443
      MONGODB_HOST: mongodb
      SPRING_PROFILES_ACTIVE: dev
      OIDC_GOOGLE_CLIENTID: local-unused
      OIDC_GOOGLE_SECRET: local-unused
      OIDC_GITLAB_CLIENTID: local-unused
      OIDC_GITLAB_SECRET: local-unused
    depends_on: [mongodb]
    logging: {driver: none}
  nginx:
    image: registry.gitlab.com/openid/conformance-suite/nginx@sha256:1c2a0b96be21d2a3aad804157073c7a36b2addd9e32a04908ee0aa3bb7c76b4c
    extra_hosts: ['host.docker.internal:host-gateway']
    ports: ['127.0.0.1:8443:8443', '127.0.0.1:9443:9443']
    volumes:
      - '${CONFORMANCE_SOURCE}/nginx.conf:/etc/nginx/nginx.conf:ro'
      - '${CONFORMANCE_STATE}/proxy.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro'
      - '${CONFORMANCE_STATE}/proxy.key:/etc/ssl/private/nginx-selfsigned.key:ro'
    networks:
      default:
        aliases: [conformance.localhost]
    depends_on: [server]
    logging: {driver: none}

volumes:
  ephemeral-mongo:
