# SPDX-FileCopyrightText: 2026 ChattoCorp GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later
worker_processes auto;
events { worker_connections 1024; }
http {
    access_log off;
    error_log /dev/null;
    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    proxy_read_timeout 120s;
    server {
        listen 8443 ssl;
        location / {
            proxy_pass http://server:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Port 8443;
        }
    }
    server {
        listen 9443 ssl;
        location / {
            proxy_pass http://host.docker.internal:19400;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}
