// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/bots.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Availability of best-effort credential last-use telemetry.
type CredentialLastUsedState int32

const (
	// The server did not return a last-use state.
	CredentialLastUsedState_CREDENTIAL_LAST_USED_STATE_UNSPECIFIED CredentialLastUsedState = 0
	// The server has no recorded use for the credential.
	CredentialLastUsedState_CREDENTIAL_LAST_USED_STATE_NO_USE_RECORDED CredentialLastUsedState = 1
	// last_used_at contains the most recent recorded authentication time.
	CredentialLastUsedState_CREDENTIAL_LAST_USED_STATE_RECORDED CredentialLastUsedState = 2
	// Last-use telemetry is temporarily unavailable.
	CredentialLastUsedState_CREDENTIAL_LAST_USED_STATE_UNAVAILABLE CredentialLastUsedState = 3
)

// Enum value maps for CredentialLastUsedState.
var (
	CredentialLastUsedState_name = map[int32]string{
		0: "CREDENTIAL_LAST_USED_STATE_UNSPECIFIED",
		1: "CREDENTIAL_LAST_USED_STATE_NO_USE_RECORDED",
		2: "CREDENTIAL_LAST_USED_STATE_RECORDED",
		3: "CREDENTIAL_LAST_USED_STATE_UNAVAILABLE",
	}
	CredentialLastUsedState_value = map[string]int32{
		"CREDENTIAL_LAST_USED_STATE_UNSPECIFIED":     0,
		"CREDENTIAL_LAST_USED_STATE_NO_USE_RECORDED": 1,
		"CREDENTIAL_LAST_USED_STATE_RECORDED":        2,
		"CREDENTIAL_LAST_USED_STATE_UNAVAILABLE":     3,
	}
)

func (x CredentialLastUsedState) Enum() *CredentialLastUsedState {
	p := new(CredentialLastUsedState)
	*p = x
	return p
}

func (x CredentialLastUsedState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialLastUsedState) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_bots_proto_enumTypes[0].Descriptor()
}

func (CredentialLastUsedState) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_bots_proto_enumTypes[0]
}

func (x CredentialLastUsedState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialLastUsedState.Descriptor instead.
func (CredentialLastUsedState) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{0}
}

// Terminal state of one outbound webhook delivery.
type BotWebhookDeliveryStatus int32

const (
	// No recognised terminal state was supplied.
	BotWebhookDeliveryStatus_BOT_WEBHOOK_DELIVERY_STATUS_UNSPECIFIED BotWebhookDeliveryStatus = 0
	// The endpoint accepted the request with an HTTP 2xx response.
	BotWebhookDeliveryStatus_BOT_WEBHOOK_DELIVERY_STATUS_DELIVERED BotWebhookDeliveryStatus = 1
	// Attempts or delivery lifetime were exhausted.
	BotWebhookDeliveryStatus_BOT_WEBHOOK_DELIVERY_STATUS_FAILED BotWebhookDeliveryStatus = 2
	// Access, message availability, or endpoint settings prevented delivery.
	BotWebhookDeliveryStatus_BOT_WEBHOOK_DELIVERY_STATUS_SKIPPED BotWebhookDeliveryStatus = 3
)

// Enum value maps for BotWebhookDeliveryStatus.
var (
	BotWebhookDeliveryStatus_name = map[int32]string{
		0: "BOT_WEBHOOK_DELIVERY_STATUS_UNSPECIFIED",
		1: "BOT_WEBHOOK_DELIVERY_STATUS_DELIVERED",
		2: "BOT_WEBHOOK_DELIVERY_STATUS_FAILED",
		3: "BOT_WEBHOOK_DELIVERY_STATUS_SKIPPED",
	}
	BotWebhookDeliveryStatus_value = map[string]int32{
		"BOT_WEBHOOK_DELIVERY_STATUS_UNSPECIFIED": 0,
		"BOT_WEBHOOK_DELIVERY_STATUS_DELIVERED":   1,
		"BOT_WEBHOOK_DELIVERY_STATUS_FAILED":      2,
		"BOT_WEBHOOK_DELIVERY_STATUS_SKIPPED":     3,
	}
)

func (x BotWebhookDeliveryStatus) Enum() *BotWebhookDeliveryStatus {
	p := new(BotWebhookDeliveryStatus)
	*p = x
	return p
}

func (x BotWebhookDeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BotWebhookDeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_bots_proto_enumTypes[1].Descriptor()
}

func (BotWebhookDeliveryStatus) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_bots_proto_enumTypes[1]
}

func (x BotWebhookDeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BotWebhookDeliveryStatus.Descriptor instead.
func (BotWebhookDeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{1}
}

// A managed bot account. Raw API keys are returned only when Chatto issues
// them.
type Bot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical public bot identity.
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Stable human owner user ID.
	OwnerUserId string `protobuf:"bytes,2,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	// Account creation time.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Legacy time for the initial API key. Use api_keys for active credentials.
	ApiKeyCreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=api_key_created_at,json=apiKeyCreatedAt,proto3" json:"api_key_created_at,omitempty"`
	// Active incoming webhook credentials, ordered by creation time.
	IncomingWebhooks []*BotIncomingWebhook `protobuf:"bytes,6,rep,name=incoming_webhooks,json=incomingWebhooks,proto3" json:"incoming_webhooks,omitempty"`
	// Active API keys, ordered by creation time.
	ApiKeys       []*BotApiKey `protobuf:"bytes,7,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bot) Reset() {
	*x = Bot{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bot) ProtoMessage() {}

func (x *Bot) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bot.ProtoReflect.Descriptor instead.
func (*Bot) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{0}
}

func (x *Bot) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Bot) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Bot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Bot) GetApiKeyCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApiKeyCreatedAt
	}
	return nil
}

func (x *Bot) GetIncomingWebhooks() []*BotIncomingWebhook {
	if x != nil {
		return x.IncomingWebhooks
	}
	return nil
}

func (x *Bot) GetApiKeys() []*BotApiKey {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

// Safe metadata for one active bot API key. The raw key is returned only when
// Chatto creates it.
type BotApiKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable API-key credential ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Manager-defined name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Time the API key was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Availability of best-effort last-use telemetry.
	LastUsedState CredentialLastUsedState `protobuf:"varint,4,opt,name=last_used_state,json=lastUsedState,proto3,enum=chatto.api.v1.CredentialLastUsedState" json:"last_used_state,omitempty"`
	// Most recent recorded successful authentication time.
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotApiKey) Reset() {
	*x = BotApiKey{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotApiKey) ProtoMessage() {}

func (x *BotApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotApiKey.ProtoReflect.Descriptor instead.
func (*BotApiKey) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{1}
}

func (x *BotApiKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BotApiKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BotApiKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BotApiKey) GetLastUsedState() CredentialLastUsedState {
	if x != nil {
		return x.LastUsedState
	}
	return CredentialLastUsedState_CREDENTIAL_LAST_USED_STATE_UNSPECIFIED
}

func (x *BotApiKey) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

// Safe metadata for one active bot incoming webhook. The webhook URL is
// returned only when the credential is created.
type BotIncomingWebhook struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable webhook credential ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Manager-defined name for the credential.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Time the incoming webhook credential was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Availability of best-effort last-use telemetry.
	LastUsedState CredentialLastUsedState `protobuf:"varint,5,opt,name=last_used_state,json=lastUsedState,proto3,enum=chatto.api.v1.CredentialLastUsedState" json:"last_used_state,omitempty"`
	// Most recent recorded successful authentication time.
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotIncomingWebhook) Reset() {
	*x = BotIncomingWebhook{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotIncomingWebhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotIncomingWebhook) ProtoMessage() {}

func (x *BotIncomingWebhook) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotIncomingWebhook.ProtoReflect.Descriptor instead.
func (*BotIncomingWebhook) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{2}
}

func (x *BotIncomingWebhook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BotIncomingWebhook) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BotIncomingWebhook) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BotIncomingWebhook) GetLastUsedState() CredentialLastUsedState {
	if x != nil {
		return x.LastUsedState
	}
	return CredentialLastUsedState_CREDENTIAL_LAST_USED_STATE_UNSPECIFIED
}

func (x *BotIncomingWebhook) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

// Request bots visible to the caller. Owners see their own bots. Callers with
// bot.manage or user.manage-accounts see every bot.
type ListBotsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional case-insensitive login or display-name search.
	Search string `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	// Page request. Defaults to 20 results when absent or limit is zero.
	Page          *PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBotsRequest) Reset() {
	*x = ListBotsRequest{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBotsRequest) ProtoMessage() {}

func (x *ListBotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBotsRequest.ProtoReflect.Descriptor instead.
func (*ListBotsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{3}
}

func (x *ListBotsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListBotsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// Page of visible bots.
type ListBotsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Visible bots.
	Bots []*Bot `protobuf:"bytes,1,rep,name=bots,proto3" json:"bots,omitempty"`
	// Page metadata.
	Page          *PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBotsResponse) Reset() {
	*x = ListBotsResponse{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBotsResponse) ProtoMessage() {}

func (x *ListBotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBotsResponse.ProtoReflect.Descriptor instead.
func (*ListBotsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{4}
}

func (x *ListBotsResponse) GetBots() []*Bot {
	if x != nil {
		return x.Bots
	}
	return nil
}

func (x *ListBotsResponse) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// Request one bot by stable user ID.
type GetBotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required bot user ID.
	BotUserId     string `protobuf:"bytes,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotRequest) Reset() {
	*x = GetBotRequest{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotRequest) ProtoMessage() {}

func (x *GetBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotRequest.ProtoReflect.Descriptor instead.
func (*GetBotRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{5}
}

func (x *GetBotRequest) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

// Response containing one bot.
type GetBotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requested bot.
	Bot           *Bot `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotResponse) Reset() {
	*x = GetBotResponse{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotResponse) ProtoMessage() {}

func (x *GetBotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotResponse.ProtoReflect.Descriptor instead.
func (*GetBotResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{6}
}

func (x *GetBotResponse) GetBot() *Bot {
	if x != nil {
		return x.Bot
	}
	return nil
}

// Request several bots by stable user ID.
type BatchGetBotsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required bot user IDs. Missing or inaccessible bots are omitted.
	BotUserIds    []string `protobuf:"bytes,1,rep,name=bot_user_ids,json=botUserIds,proto3" json:"bot_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetBotsRequest) Reset() {
	*x = BatchGetBotsRequest{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetBotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetBotsRequest) ProtoMessage() {}

func (x *BatchGetBotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetBotsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetBotsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetBotsRequest) GetBotUserIds() []string {
	if x != nil {
		return x.BotUserIds
	}
	return nil
}

// Response containing accessible bots in first-seen request order.
type BatchGetBotsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Found bots.
	Bots          []*Bot `protobuf:"bytes,1,rep,name=bots,proto3" json:"bots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetBotsResponse) Reset() {
	*x = BatchGetBotsResponse{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetBotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetBotsResponse) ProtoMessage() {}

func (x *BatchGetBotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetBotsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetBotsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGetBotsResponse) GetBots() []*Bot {
	if x != nil {
		return x.Bots
	}
	return nil
}

// Request creation of a bot owned by the authenticated human caller.
type CreateBotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bot login. Must end in `_bot`.
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// Public display name.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Optional name for the initial API key. Defaults to "Default key".
	ApiKeyName    *string `protobuf:"bytes,3,opt,name=api_key_name,json=apiKeyName,proto3,oneof" json:"api_key_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBotRequest) Reset() {
	*x = CreateBotRequest{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotRequest) ProtoMessage() {}

func (x *CreateBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotRequest.ProtoReflect.Descriptor instead.
func (*CreateBotRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{9}
}

func (x *CreateBotRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateBotRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateBotRequest) GetApiKeyName() string {
	if x != nil && x.ApiKeyName != nil {
		return *x.ApiKeyName
	}
	return ""
}

// Result of creating a bot. api_key is shown once and cannot be retrieved.
type CreateBotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created bot.
	Bot *Bot `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	// Newly issued API key.
	ApiKey string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Safe metadata for the newly issued API key.
	ApiKeyMetadata *BotApiKey `protobuf:"bytes,3,opt,name=api_key_metadata,json=apiKeyMetadata,proto3" json:"api_key_metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBotResponse) Reset() {
	*x = CreateBotResponse{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotResponse) ProtoMessage() {}

func (x *CreateBotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotResponse.ProtoReflect.Descriptor instead.
func (*CreateBotResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{10}
}

func (x *CreateBotResponse) GetBot() *Bot {
	if x != nil {
		return x.Bot
	}
	return nil
}

func (x *CreateBotResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateBotResponse) GetApiKeyMetadata() *BotApiKey {
	if x != nil {
		return x.ApiKeyMetadata
	}
	return nil
}

// Request deletion of a bot account.
type DeleteBotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required bot user ID.
	BotUserId     string `protobuf:"bytes,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBotRequest) Reset() {
	*x = DeleteBotRequest{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBotRequest) ProtoMessage() {}

func (x *DeleteBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBotRequest.ProtoReflect.Descriptor instead.
func (*DeleteBotRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteBotRequest) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

// Result of deleting a bot account.
type DeleteBotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the bot was deleted.
	Deleted       bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBotResponse) Reset() {
	*x = DeleteBotResponse{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBotResponse) ProtoMessage() {}

func (x *DeleteBotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBotResponse.ProtoReflect.Descriptor instead.
func (*DeleteBotResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteBotResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// Request creation of one named API key for a bot.
type CreateBotApiKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required bot user ID.
	BotUserId string `protobuf:"bytes,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	// Required manager-defined name. Names do not need to be unique.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBotApiKeyRequest) Reset() {
	*x = CreateBotApiKeyRequest{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotApiKeyRequest) ProtoMessage() {}

func (x *CreateBotApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotApiKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateBotApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{13}
}

func (x *CreateBotApiKeyRequest) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

func (x *CreateBotApiKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Result of creating one API key. api_key is shown once and cannot be
// retrieved later.
type CreateBotApiKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated bot metadata.
	Bot *Bot `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	// Newly issued API key.
	ApiKey string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Safe metadata for the newly issued API key.
	ApiKeyMetadata *BotApiKey `protobuf:"bytes,3,opt,name=api_key_metadata,json=apiKeyMetadata,proto3" json:"api_key_metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBotApiKeyResponse) Reset() {
	*x = CreateBotApiKeyResponse{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotApiKeyResponse) ProtoMessage() {}

func (x *CreateBotApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotApiKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateBotApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{14}
}

func (x *CreateBotApiKeyResponse) GetBot() *Bot {
	if x != nil {
		return x.Bot
	}
	return nil
}

func (x *CreateBotApiKeyResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateBotApiKeyResponse) GetApiKeyMetadata() *BotApiKey {
	if x != nil {
		return x.ApiKeyMetadata
	}
	return nil
}

// Request irreversible revocation of one bot API key.
type RevokeBotApiKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required bot user ID.
	BotUserId string `protobuf:"bytes,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	// Required API-key credential ID.
	KeyId         string `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeBotApiKeyRequest) Reset() {
	*x = RevokeBotApiKeyRequest{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeBotApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeBotApiKeyRequest) ProtoMessage() {}

func (x *RevokeBotApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeBotApiKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokeBotApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{15}
}

func (x *RevokeBotApiKeyRequest) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

func (x *RevokeBotApiKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// Result of revoking one bot API key.
type RevokeBotApiKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated bot metadata.
	Bot           *Bot `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeBotApiKeyResponse) Reset() {
	*x = RevokeBotApiKeyResponse{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeBotApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeBotApiKeyResponse) ProtoMessage() {}

func (x *RevokeBotApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeBotApiKeyResponse.ProtoReflect.Descriptor instead.
func (*RevokeBotApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{16}
}

func (x *RevokeBotApiKeyResponse) GetBot() *Bot {
	if x != nil {
		return x.Bot
	}
	return nil
}

// Request creation of one named incoming webhook for a bot.
type CreateBotIncomingWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required bot user ID.
	BotUserId string `protobuf:"bytes,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	// Required manager-defined name. Names do not need to be unique.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBotIncomingWebhookRequest) Reset() {
	*x = CreateBotIncomingWebhookRequest{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotIncomingWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotIncomingWebhookRequest) ProtoMessage() {}

func (x *CreateBotIncomingWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotIncomingWebhookRequest.ProtoReflect.Descriptor instead.
func (*CreateBotIncomingWebhookRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{17}
}

func (x *CreateBotIncomingWebhookRequest) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

func (x *CreateBotIncomingWebhookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Result of creating an incoming webhook. webhook_url is shown once and cannot
// be retrieved later.
type CreateBotIncomingWebhookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated bot metadata.
	Bot *Bot `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	// Newly issued incoming webhook URL.
	WebhookUrl    string `protobuf:"bytes,2,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBotIncomingWebhookResponse) Reset() {
	*x = CreateBotIncomingWebhookResponse{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotIncomingWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotIncomingWebhookResponse) ProtoMessage() {}

func (x *CreateBotIncomingWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotIncomingWebhookResponse.ProtoReflect.Descriptor instead.
func (*CreateBotIncomingWebhookResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{18}
}

func (x *CreateBotIncomingWebhookResponse) GetBot() *Bot {
	if x != nil {
		return x.Bot
	}
	return nil
}

func (x *CreateBotIncomingWebhookResponse) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

// Request irreversible revocation of one incoming webhook credential.
type RevokeBotIncomingWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required bot user ID.
	BotUserId string `protobuf:"bytes,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	// Required webhook credential ID.
	WebhookId     string `protobuf:"bytes,2,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeBotIncomingWebhookRequest) Reset() {
	*x = RevokeBotIncomingWebhookRequest{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeBotIncomingWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeBotIncomingWebhookRequest) ProtoMessage() {}

func (x *RevokeBotIncomingWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeBotIncomingWebhookRequest.ProtoReflect.Descriptor instead.
func (*RevokeBotIncomingWebhookRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{19}
}

func (x *RevokeBotIncomingWebhookRequest) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

func (x *RevokeBotIncomingWebhookRequest) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

// Result of revoking an incoming webhook.
type RevokeBotIncomingWebhookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated bot metadata.
	Bot           *Bot `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeBotIncomingWebhookResponse) Reset() {
	*x = RevokeBotIncomingWebhookResponse{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeBotIncomingWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeBotIncomingWebhookResponse) ProtoMessage() {}

func (x *RevokeBotIncomingWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeBotIncomingWebhookResponse.ProtoReflect.Descriptor instead.
func (*RevokeBotIncomingWebhookResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{20}
}

func (x *RevokeBotIncomingWebhookResponse) GetBot() *Bot {
	if x != nil {
		return x.Bot
	}
	return nil
}

// Request an administrative reassignment of a bot to another human owner.
type ReassignBotOwnerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required bot user ID.
	BotUserId string `protobuf:"bytes,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	// Required user ID of the new human owner.
	OwnerUserId   string `protobuf:"bytes,2,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReassignBotOwnerRequest) Reset() {
	*x = ReassignBotOwnerRequest{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReassignBotOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReassignBotOwnerRequest) ProtoMessage() {}

func (x *ReassignBotOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReassignBotOwnerRequest.ProtoReflect.Descriptor instead.
func (*ReassignBotOwnerRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{21}
}

func (x *ReassignBotOwnerRequest) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

func (x *ReassignBotOwnerRequest) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

// Result of reassigning a bot owner. The bot's API keys and configured
// permission allowlist are unchanged.
type ReassignBotOwnerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reassigned bot.
	Bot           *Bot `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReassignBotOwnerResponse) Reset() {
	*x = ReassignBotOwnerResponse{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReassignBotOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReassignBotOwnerResponse) ProtoMessage() {}

func (x *ReassignBotOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReassignBotOwnerResponse.ProtoReflect.Descriptor instead.
func (*ReassignBotOwnerResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{22}
}

func (x *ReassignBotOwnerResponse) GetBot() *Bot {
	if x != nil {
		return x.Bot
	}
	return nil
}

// Endpoint settings visible only to the bot owner or a caller with bot.manage.
// Credentials are write-only. Replace the configuration to change them.
type BotOutboundWebhook struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration generation, used to cancel earlier pending work.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Whether this configuration accepts new messages.
	Enabled bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Whether an Authorization header is configured.
	HasAuthorization bool `protobuf:"varint,3,opt,name=has_authorization,json=hasAuthorization,proto3" json:"has_authorization,omitempty"`
	// Latest terminal delivery for this configuration, when available.
	LatestDelivery *BotWebhookDelivery `protobuf:"bytes,4,opt,name=latest_delivery,json=latestDelivery,proto3" json:"latest_delivery,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BotOutboundWebhook) Reset() {
	*x = BotOutboundWebhook{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotOutboundWebhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotOutboundWebhook) ProtoMessage() {}

func (x *BotOutboundWebhook) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotOutboundWebhook.ProtoReflect.Descriptor instead.
func (*BotOutboundWebhook) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{23}
}

func (x *BotOutboundWebhook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BotOutboundWebhook) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *BotOutboundWebhook) GetHasAuthorization() bool {
	if x != nil {
		return x.HasAuthorization
	}
	return false
}

func (x *BotOutboundWebhook) GetLatestDelivery() *BotWebhookDelivery {
	if x != nil {
		return x.LatestDelivery
	}
	return nil
}

// Safe summary of one terminal webhook delivery.
type BotWebhookDelivery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable delivery identifier shared by all retry attempts.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Final result of this delivery.
	Status BotWebhookDeliveryStatus `protobuf:"varint,2,opt,name=status,proto3,enum=chatto.api.v1.BotWebhookDeliveryStatus" json:"status,omitempty"`
	// Safe failure or skip category. Empty for successful delivery.
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// Reserved attempts, including requests with an uncertain crash outcome.
	Attempts uint32 `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
	// Zero if no HTTP response was received.
	HttpStatus uint32 `protobuf:"varint,5,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	// Time the terminal outcome was recorded.
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotWebhookDelivery) Reset() {
	*x = BotWebhookDelivery{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotWebhookDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotWebhookDelivery) ProtoMessage() {}

func (x *BotWebhookDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotWebhookDelivery.ProtoReflect.Descriptor instead.
func (*BotWebhookDelivery) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{24}
}

func (x *BotWebhookDelivery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BotWebhookDelivery) GetStatus() BotWebhookDeliveryStatus {
	if x != nil {
		return x.Status
	}
	return BotWebhookDeliveryStatus_BOT_WEBHOOK_DELIVERY_STATUS_UNSPECIFIED
}

func (x *BotWebhookDelivery) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BotWebhookDelivery) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *BotWebhookDelivery) GetHttpStatus() uint32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *BotWebhookDelivery) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// Read the current endpoint metadata for one managed bot.
type GetBotOutboundWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required bot user ID.
	BotUserId     string `protobuf:"bytes,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotOutboundWebhookRequest) Reset() {
	*x = GetBotOutboundWebhookRequest{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotOutboundWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotOutboundWebhookRequest) ProtoMessage() {}

func (x *GetBotOutboundWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotOutboundWebhookRequest.ProtoReflect.Descriptor instead.
func (*GetBotOutboundWebhookRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{25}
}

func (x *GetBotOutboundWebhookRequest) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

// Current endpoint metadata without URL or credentials.
type GetBotOutboundWebhookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absent when the bot has no configuration.
	Webhook       *BotOutboundWebhook `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotOutboundWebhookResponse) Reset() {
	*x = GetBotOutboundWebhookResponse{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotOutboundWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotOutboundWebhookResponse) ProtoMessage() {}

func (x *GetBotOutboundWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotOutboundWebhookResponse.ProtoReflect.Descriptor instead.
func (*GetBotOutboundWebhookResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{26}
}

func (x *GetBotOutboundWebhookResponse) GetWebhook() *BotOutboundWebhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

// Replace all endpoint settings. Each replacement cancels earlier pending work.
type ReplaceBotOutboundWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required bot user ID.
	BotUserId string `protobuf:"bytes,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	// Absolute HTTPS destination. Treat secret URL components as credentials.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Optional complete Authorization header value. Empty removes the header.
	Authorization string `protobuf:"bytes,3,opt,name=authorization,proto3" json:"authorization,omitempty"`
	// Accept new eligible messages for delivery. False stores a disabled endpoint.
	Enabled       bool `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceBotOutboundWebhookRequest) Reset() {
	*x = ReplaceBotOutboundWebhookRequest{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceBotOutboundWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceBotOutboundWebhookRequest) ProtoMessage() {}

func (x *ReplaceBotOutboundWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceBotOutboundWebhookRequest.ProtoReflect.Descriptor instead.
func (*ReplaceBotOutboundWebhookRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{27}
}

func (x *ReplaceBotOutboundWebhookRequest) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

func (x *ReplaceBotOutboundWebhookRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ReplaceBotOutboundWebhookRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *ReplaceBotOutboundWebhookRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// Saved endpoint metadata and its show-once signing secret.
type ReplaceBotOutboundWebhookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Saved configuration metadata.
	Webhook *BotOutboundWebhook `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	// Show-once secret for HMAC-SHA256 request verification.
	SigningSecret string `protobuf:"bytes,2,opt,name=signing_secret,json=signingSecret,proto3" json:"signing_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceBotOutboundWebhookResponse) Reset() {
	*x = ReplaceBotOutboundWebhookResponse{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceBotOutboundWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceBotOutboundWebhookResponse) ProtoMessage() {}

func (x *ReplaceBotOutboundWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceBotOutboundWebhookResponse.ProtoReflect.Descriptor instead.
func (*ReplaceBotOutboundWebhookResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{28}
}

func (x *ReplaceBotOutboundWebhookResponse) GetWebhook() *BotOutboundWebhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

func (x *ReplaceBotOutboundWebhookResponse) GetSigningSecret() string {
	if x != nil {
		return x.SigningSecret
	}
	return ""
}

// Remove the endpoint for one managed bot.
type DeleteBotOutboundWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required bot user ID.
	BotUserId     string `protobuf:"bytes,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBotOutboundWebhookRequest) Reset() {
	*x = DeleteBotOutboundWebhookRequest{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBotOutboundWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBotOutboundWebhookRequest) ProtoMessage() {}

func (x *DeleteBotOutboundWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBotOutboundWebhookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBotOutboundWebhookRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteBotOutboundWebhookRequest) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

// The endpoint was removed, or was already absent.
type DeleteBotOutboundWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBotOutboundWebhookResponse) Reset() {
	*x = DeleteBotOutboundWebhookResponse{}
	mi := &file_chatto_api_v1_bots_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBotOutboundWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBotOutboundWebhookResponse) ProtoMessage() {}

func (x *DeleteBotOutboundWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_bots_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBotOutboundWebhookResponse.ProtoReflect.Descriptor instead.
func (*DeleteBotOutboundWebhookResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_bots_proto_rawDescGZIP(), []int{30}
}

var File_chatto_api_v1_bots_proto protoreflect.FileDescriptor

const file_chatto_api_v1_bots_proto_rawDesc = "" +
	"\n" +
	"\x18chatto/api/v1/bots.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1echatto/api/v1/pagination.proto\x1a\x19chatto/api/v1/users.proto\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x02\n" +
	"\x03Bot\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.chatto.api.v1.UserR\x04user\x12\"\n" +
	"\rowner_user_id\x18\x02 \x01(\tR\vownerUserId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12G\n" +
	"\x12api_key_created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0fapiKeyCreatedAt\x12N\n" +
	"\x11incoming_webhooks\x18\x06 \x03(\v2!.chatto.api.v1.BotIncomingWebhookR\x10incomingWebhooks\x123\n" +
	"\bapi_keys\x18\a \x03(\v2\x18.chatto.api.v1.BotApiKeyR\aapiKeysJ\x04\b\x05\x10\x06R\x12api_key_rotated_at\"\x8e\x02\n" +
	"\tBotApiKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12N\n" +
	"\x0flast_used_state\x18\x04 \x01(\x0e2&.chatto.api.v1.CredentialLastUsedStateR\rlastUsedState\x12A\n" +
	"\flast_used_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"lastUsedAt\x88\x01\x01B\x0f\n" +
	"\r_last_used_at\"\xa9\x02\n" +
	"\x12BotIncomingWebhook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12N\n" +
	"\x0flast_used_state\x18\x05 \x01(\x0e2&.chatto.api.v1.CredentialLastUsedStateR\rlastUsedState\x12A\n" +
	"\flast_used_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"lastUsedAt\x88\x01\x01B\x0f\n" +
	"\r_last_used_atJ\x04\b\x04\x10\x05R\n" +
	"rotated_at\"b\n" +
	"\x0fListBotsRequest\x12\x1f\n" +
	"\x06search\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18dR\x06search\x12.\n" +
	"\x04page\x18\x02 \x01(\v2\x1a.chatto.api.v1.PageRequestR\x04page\"g\n" +
	"\x10ListBotsResponse\x12&\n" +
	"\x04bots\x18\x01 \x03(\v2\x12.chatto.api.v1.BotR\x04bots\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.chatto.api.v1.PageInfoR\x04page\"8\n" +
	"\rGetBotRequest\x12'\n" +
	"\vbot_user_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tbotUserId\"6\n" +
	"\x0eGetBotResponse\x12$\n" +
	"\x03bot\x18\x01 \x01(\v2\x12.chatto.api.v1.BotR\x03bot\"I\n" +
	"\x13BatchGetBotsRequest\x122\n" +
	"\fbot_user_ids\x18\x01 \x03(\tB\x10\xbaH\r\x92\x01\n" +
	"\b\x01\x10d\"\x04r\x02\x10\x01R\n" +
	"botUserIds\">\n" +
	"\x14BatchGetBotsResponse\x12&\n" +
	"\x04bots\x18\x01 \x03(\v2\x12.chatto.api.v1.BotR\x04bots\"\xa2\x01\n" +
	"\x10CreateBotRequest\x12\x1f\n" +
	"\x05login\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x18 R\x05login\x12*\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18 R\vdisplayName\x120\n" +
	"\fapi_key_name\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@H\x00R\n" +
	"apiKeyName\x88\x01\x01B\x0f\n" +
	"\r_api_key_name\"\x96\x01\n" +
	"\x11CreateBotResponse\x12$\n" +
	"\x03bot\x18\x01 \x01(\v2\x12.chatto.api.v1.BotR\x03bot\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12B\n" +
	"\x10api_key_metadata\x18\x03 \x01(\v2\x18.chatto.api.v1.BotApiKeyR\x0eapiKeyMetadata\";\n" +
	"\x10DeleteBotRequest\x12'\n" +
	"\vbot_user_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tbotUserId\"-\n" +
	"\x11DeleteBotResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"`\n" +
	"\x16CreateBotApiKeyRequest\x12'\n" +
	"\vbot_user_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tbotUserId\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x04name\"\x9c\x01\n" +
	"\x17CreateBotApiKeyResponse\x12$\n" +
	"\x03bot\x18\x01 \x01(\v2\x12.chatto.api.v1.BotR\x03bot\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12B\n" +
	"\x10api_key_metadata\x18\x03 \x01(\v2\x18.chatto.api.v1.BotApiKeyR\x0eapiKeyMetadata\"a\n" +
	"\x16RevokeBotApiKeyRequest\x12'\n" +
	"\vbot_user_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tbotUserId\x12\x1e\n" +
	"\x06key_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05keyId\"?\n" +
	"\x17RevokeBotApiKeyResponse\x12$\n" +
	"\x03bot\x18\x01 \x01(\v2\x12.chatto.api.v1.BotR\x03bot\"i\n" +
	"\x1fCreateBotIncomingWebhookRequest\x12'\n" +
	"\vbot_user_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tbotUserId\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x04name\"i\n" +
	" CreateBotIncomingWebhookResponse\x12$\n" +
	"\x03bot\x18\x01 \x01(\v2\x12.chatto.api.v1.BotR\x03bot\x12\x1f\n" +
	"\vwebhook_url\x18\x02 \x01(\tR\n" +
	"webhookUrl\"r\n" +
	"\x1fRevokeBotIncomingWebhookRequest\x12'\n" +
	"\vbot_user_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tbotUserId\x12&\n" +
	"\n" +
	"webhook_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\twebhookId\"H\n" +
	" RevokeBotIncomingWebhookResponse\x12$\n" +
	"\x03bot\x18\x01 \x01(\v2\x12.chatto.api.v1.BotR\x03bot\"o\n" +
	"\x17ReassignBotOwnerRequest\x12'\n" +
	"\vbot_user_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tbotUserId\x12+\n" +
	"\rowner_user_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vownerUserId\"@\n" +
	"\x18ReassignBotOwnerResponse\x12$\n" +
	"\x03bot\x18\x01 \x01(\v2\x12.chatto.api.v1.BotR\x03bot\"\xb7\x01\n" +
	"\x12BotOutboundWebhook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12+\n" +
	"\x11has_authorization\x18\x03 \x01(\bR\x10hasAuthorization\x12J\n" +
	"\x0flatest_delivery\x18\x04 \x01(\v2!.chatto.api.v1.BotWebhookDeliveryR\x0elatestDelivery\"\xf9\x01\n" +
	"\x12BotWebhookDelivery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\x06status\x18\x02 \x01(\x0e2'.chatto.api.v1.BotWebhookDeliveryStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\rR\battempts\x12\x1f\n" +
	"\vhttp_status\x18\x05 \x01(\rR\n" +
	"httpStatus\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"G\n" +
	"\x1cGetBotOutboundWebhookRequest\x12'\n" +
	"\vbot_user_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tbotUserId\"\\\n" +
	"\x1dGetBotOutboundWebhookResponse\x12;\n" +
	"\awebhook\x18\x01 \x01(\v2!.chatto.api.v1.BotOutboundWebhookR\awebhook\"\xb3\x01\n" +
	" ReplaceBotOutboundWebhookRequest\x12'\n" +
	"\vbot_user_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tbotUserId\x12\x1c\n" +
	"\x03url\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80 R\x03url\x12.\n" +
	"\rauthorization\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80 R\rauthorization\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\"\x87\x01\n" +
	"!ReplaceBotOutboundWebhookResponse\x12;\n" +
	"\awebhook\x18\x01 \x01(\v2!.chatto.api.v1.BotOutboundWebhookR\awebhook\x12%\n" +
	"\x0esigning_secret\x18\x02 \x01(\tR\rsigningSecret\"J\n" +
	"\x1fDeleteBotOutboundWebhookRequest\x12'\n" +
	"\vbot_user_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tbotUserId\"\"\n" +
	" DeleteBotOutboundWebhookResponse*\xca\x01\n" +
	"\x17CredentialLastUsedState\x12*\n" +
	"&CREDENTIAL_LAST_USED_STATE_UNSPECIFIED\x10\x00\x12.\n" +
	"*CREDENTIAL_LAST_USED_STATE_NO_USE_RECORDED\x10\x01\x12'\n" +
	"#CREDENTIAL_LAST_USED_STATE_RECORDED\x10\x02\x12*\n" +
	"&CREDENTIAL_LAST_USED_STATE_UNAVAILABLE\x10\x03*\xc3\x01\n" +
	"\x18BotWebhookDeliveryStatus\x12+\n" +
	"'BOT_WEBHOOK_DELIVERY_STATUS_UNSPECIFIED\x10\x00\x12)\n" +
	"%BOT_WEBHOOK_DELIVERY_STATUS_DELIVERED\x10\x01\x12&\n" +
	"\"BOT_WEBHOOK_DELIVERY_STATUS_FAILED\x10\x02\x12'\n" +
	"#BOT_WEBHOOK_DELIVERY_STATUS_SKIPPED\x10\x032\xc8\n" +
	"\n" +
	"\n" +
	"BotService\x12r\n" +
	"\x15GetBotOutboundWebhook\x12+.chatto.api.v1.GetBotOutboundWebhookRequest\x1a,.chatto.api.v1.GetBotOutboundWebhookResponse\x12~\n" +
	"\x19ReplaceBotOutboundWebhook\x12/.chatto.api.v1.ReplaceBotOutboundWebhookRequest\x1a0.chatto.api.v1.ReplaceBotOutboundWebhookResponse\x12\x80\x01\n" +
	"\x18DeleteBotOutboundWebhook\x12..chatto.api.v1.DeleteBotOutboundWebhookRequest\x1a/.chatto.api.v1.DeleteBotOutboundWebhookResponse\"\x03\x90\x02\x02\x12K\n" +
	"\bListBots\x12\x1e.chatto.api.v1.ListBotsRequest\x1a\x1f.chatto.api.v1.ListBotsResponse\x12E\n" +
	"\x06GetBot\x12\x1c.chatto.api.v1.GetBotRequest\x1a\x1d.chatto.api.v1.GetBotResponse\x12W\n" +
	"\fBatchGetBots\x12\".chatto.api.v1.BatchGetBotsRequest\x1a#.chatto.api.v1.BatchGetBotsResponse\x12N\n" +
	"\tCreateBot\x12\x1f.chatto.api.v1.CreateBotRequest\x1a .chatto.api.v1.CreateBotResponse\x12S\n" +
	"\tDeleteBot\x12\x1f.chatto.api.v1.DeleteBotRequest\x1a .chatto.api.v1.DeleteBotResponse\"\x03\x90\x02\x02\x12`\n" +
	"\x0fCreateBotApiKey\x12%.chatto.api.v1.CreateBotApiKeyRequest\x1a&.chatto.api.v1.CreateBotApiKeyResponse\x12e\n" +
	"\x0fRevokeBotApiKey\x12%.chatto.api.v1.RevokeBotApiKeyRequest\x1a&.chatto.api.v1.RevokeBotApiKeyResponse\"\x03\x90\x02\x02\x12{\n" +
	"\x18CreateBotIncomingWebhook\x12..chatto.api.v1.CreateBotIncomingWebhookRequest\x1a/.chatto.api.v1.CreateBotIncomingWebhookResponse\x12\x80\x01\n" +
	"\x18RevokeBotIncomingWebhook\x12..chatto.api.v1.RevokeBotIncomingWebhookRequest\x1a/.chatto.api.v1.RevokeBotIncomingWebhookResponse\"\x03\x90\x02\x02\x12h\n" +
	"\x10ReassignBotOwner\x12&.chatto.api.v1.ReassignBotOwnerRequest\x1a'.chatto.api.v1.ReassignBotOwnerResponse\"\x03\x90\x02\x02B\xa5\x01\n" +
	"\x11com.chatto.api.v1B\tBotsProtoP\x01Z/hmans.de/chatto/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_bots_proto_rawDescOnce sync.Once
	file_chatto_api_v1_bots_proto_rawDescData []byte
)

func file_chatto_api_v1_bots_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_bots_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_bots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_bots_proto_rawDesc), len(file_chatto_api_v1_bots_proto_rawDesc)))
	})
	return file_chatto_api_v1_bots_proto_rawDescData
}

var file_chatto_api_v1_bots_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chatto_api_v1_bots_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_chatto_api_v1_bots_proto_goTypes = []any{
	(CredentialLastUsedState)(0),              // 0: chatto.api.v1.CredentialLastUsedState
	(BotWebhookDeliveryStatus)(0),             // 1: chatto.api.v1.BotWebhookDeliveryStatus
	(*Bot)(nil),                               // 2: chatto.api.v1.Bot
	(*BotApiKey)(nil),                         // 3: chatto.api.v1.BotApiKey
	(*BotIncomingWebhook)(nil),                // 4: chatto.api.v1.BotIncomingWebhook
	(*ListBotsRequest)(nil),                   // 5: chatto.api.v1.ListBotsRequest
	(*ListBotsResponse)(nil),                  // 6: chatto.api.v1.ListBotsResponse
	(*GetBotRequest)(nil),                     // 7: chatto.api.v1.GetBotRequest
	(*GetBotResponse)(nil),                    // 8: chatto.api.v1.GetBotResponse
	(*BatchGetBotsRequest)(nil),               // 9: chatto.api.v1.BatchGetBotsRequest
	(*BatchGetBotsResponse)(nil),              // 10: chatto.api.v1.BatchGetBotsResponse
	(*CreateBotRequest)(nil),                  // 11: chatto.api.v1.CreateBotRequest
	(*CreateBotResponse)(nil),                 // 12: chatto.api.v1.CreateBotResponse
	(*DeleteBotRequest)(nil),                  // 13: chatto.api.v1.DeleteBotRequest
	(*DeleteBotResponse)(nil),                 // 14: chatto.api.v1.DeleteBotResponse
	(*CreateBotApiKeyRequest)(nil),            // 15: chatto.api.v1.CreateBotApiKeyRequest
	(*CreateBotApiKeyResponse)(nil),           // 16: chatto.api.v1.CreateBotApiKeyResponse
	(*RevokeBotApiKeyRequest)(nil),            // 17: chatto.api.v1.RevokeBotApiKeyRequest
	(*RevokeBotApiKeyResponse)(nil),           // 18: chatto.api.v1.RevokeBotApiKeyResponse
	(*CreateBotIncomingWebhookRequest)(nil),   // 19: chatto.api.v1.CreateBotIncomingWebhookRequest
	(*CreateBotIncomingWebhookResponse)(nil),  // 20: chatto.api.v1.CreateBotIncomingWebhookResponse
	(*RevokeBotIncomingWebhookRequest)(nil),   // 21: chatto.api.v1.RevokeBotIncomingWebhookRequest
	(*RevokeBotIncomingWebhookResponse)(nil),  // 22: chatto.api.v1.RevokeBotIncomingWebhookResponse
	(*ReassignBotOwnerRequest)(nil),           // 23: chatto.api.v1.ReassignBotOwnerRequest
	(*ReassignBotOwnerResponse)(nil),          // 24: chatto.api.v1.ReassignBotOwnerResponse
	(*BotOutboundWebhook)(nil),                // 25: chatto.api.v1.BotOutboundWebhook
	(*BotWebhookDelivery)(nil),                // 26: chatto.api.v1.BotWebhookDelivery
	(*GetBotOutboundWebhookRequest)(nil),      // 27: chatto.api.v1.GetBotOutboundWebhookRequest
	(*GetBotOutboundWebhookResponse)(nil),     // 28: chatto.api.v1.GetBotOutboundWebhookResponse
	(*ReplaceBotOutboundWebhookRequest)(nil),  // 29: chatto.api.v1.ReplaceBotOutboundWebhookRequest
	(*ReplaceBotOutboundWebhookResponse)(nil), // 30: chatto.api.v1.ReplaceBotOutboundWebhookResponse
	(*DeleteBotOutboundWebhookRequest)(nil),   // 31: chatto.api.v1.DeleteBotOutboundWebhookRequest
	(*DeleteBotOutboundWebhookResponse)(nil),  // 32: chatto.api.v1.DeleteBotOutboundWebhookResponse
	(*User)(nil),                              // 33: chatto.api.v1.User
	(*timestamppb.Timestamp)(nil),             // 34: google.protobuf.Timestamp
	(*PageRequest)(nil),                       // 35: chatto.api.v1.PageRequest
	(*PageInfo)(nil),                          // 36: chatto.api.v1.PageInfo
}
var file_chatto_api_v1_bots_proto_depIdxs = []int32{
	33, // 0: chatto.api.v1.Bot.user:type_name -> chatto.api.v1.User
	34, // 1: chatto.api.v1.Bot.created_at:type_name -> google.protobuf.Timestamp
	34, // 2: chatto.api.v1.Bot.api_key_created_at:type_name -> google.protobuf.Timestamp
	4,  // 3: chatto.api.v1.Bot.incoming_webhooks:type_name -> chatto.api.v1.BotIncomingWebhook
	3,  // 4: chatto.api.v1.Bot.api_keys:type_name -> chatto.api.v1.BotApiKey
	34, // 5: chatto.api.v1.BotApiKey.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: chatto.api.v1.BotApiKey.last_used_state:type_name -> chatto.api.v1.CredentialLastUsedState
	34, // 7: chatto.api.v1.BotApiKey.last_used_at:type_name -> google.protobuf.Timestamp
	34, // 8: chatto.api.v1.BotIncomingWebhook.created_at:type_name -> google.protobuf.Timestamp
	0,  // 9: chatto.api.v1.BotIncomingWebhook.last_used_state:type_name -> chatto.api.v1.CredentialLastUsedState
	34, // 10: chatto.api.v1.BotIncomingWebhook.last_used_at:type_name -> google.protobuf.Timestamp
	35, // 11: chatto.api.v1.ListBotsRequest.page:type_name -> chatto.api.v1.PageRequest
	2,  // 12: chatto.api.v1.ListBotsResponse.bots:type_name -> chatto.api.v1.Bot
	36, // 13: chatto.api.v1.ListBotsResponse.page:type_name -> chatto.api.v1.PageInfo
	2,  // 14: chatto.api.v1.GetBotResponse.bot:type_name -> chatto.api.v1.Bot
	2,  // 15: chatto.api.v1.BatchGetBotsResponse.bots:type_name -> chatto.api.v1.Bot
	2,  // 16: chatto.api.v1.CreateBotResponse.bot:type_name -> chatto.api.v1.Bot
	3,  // 17: chatto.api.v1.CreateBotResponse.api_key_metadata:type_name -> chatto.api.v1.BotApiKey
	2,  // 18: chatto.api.v1.CreateBotApiKeyResponse.bot:type_name -> chatto.api.v1.Bot
	3,  // 19: chatto.api.v1.CreateBotApiKeyResponse.api_key_metadata:type_name -> chatto.api.v1.BotApiKey
	2,  // 20: chatto.api.v1.RevokeBotApiKeyResponse.bot:type_name -> chatto.api.v1.Bot
	2,  // 21: chatto.api.v1.CreateBotIncomingWebhookResponse.bot:type_name -> chatto.api.v1.Bot
	2,  // 22: chatto.api.v1.RevokeBotIncomingWebhookResponse.bot:type_name -> chatto.api.v1.Bot
	2,  // 23: chatto.api.v1.ReassignBotOwnerResponse.bot:type_name -> chatto.api.v1.Bot
	26, // 24: chatto.api.v1.BotOutboundWebhook.latest_delivery:type_name -> chatto.api.v1.BotWebhookDelivery
	1,  // 25: chatto.api.v1.BotWebhookDelivery.status:type_name -> chatto.api.v1.BotWebhookDeliveryStatus
	34, // 26: chatto.api.v1.BotWebhookDelivery.completed_at:type_name -> google.protobuf.Timestamp
	25, // 27: chatto.api.v1.GetBotOutboundWebhookResponse.webhook:type_name -> chatto.api.v1.BotOutboundWebhook
	25, // 28: chatto.api.v1.ReplaceBotOutboundWebhookResponse.webhook:type_name -> chatto.api.v1.BotOutboundWebhook
	27, // 29: chatto.api.v1.BotService.GetBotOutboundWebhook:input_type -> chatto.api.v1.GetBotOutboundWebhookRequest
	29, // 30: chatto.api.v1.BotService.ReplaceBotOutboundWebhook:input_type -> chatto.api.v1.ReplaceBotOutboundWebhookRequest
	31, // 31: chatto.api.v1.BotService.DeleteBotOutboundWebhook:input_type -> chatto.api.v1.DeleteBotOutboundWebhookRequest
	5,  // 32: chatto.api.v1.BotService.ListBots:input_type -> chatto.api.v1.ListBotsRequest
	7,  // 33: chatto.api.v1.BotService.GetBot:input_type -> chatto.api.v1.GetBotRequest
	9,  // 34: chatto.api.v1.BotService.BatchGetBots:input_type -> chatto.api.v1.BatchGetBotsRequest
	11, // 35: chatto.api.v1.BotService.CreateBot:input_type -> chatto.api.v1.CreateBotRequest
	13, // 36: chatto.api.v1.BotService.DeleteBot:input_type -> chatto.api.v1.DeleteBotRequest
	15, // 37: chatto.api.v1.BotService.CreateBotApiKey:input_type -> chatto.api.v1.CreateBotApiKeyRequest
	17, // 38: chatto.api.v1.BotService.RevokeBotApiKey:input_type -> chatto.api.v1.RevokeBotApiKeyRequest
	19, // 39: chatto.api.v1.BotService.CreateBotIncomingWebhook:input_type -> chatto.api.v1.CreateBotIncomingWebhookRequest
	21, // 40: chatto.api.v1.BotService.RevokeBotIncomingWebhook:input_type -> chatto.api.v1.RevokeBotIncomingWebhookRequest
	23, // 41: chatto.api.v1.BotService.ReassignBotOwner:input_type -> chatto.api.v1.ReassignBotOwnerRequest
	28, // 42: chatto.api.v1.BotService.GetBotOutboundWebhook:output_type -> chatto.api.v1.GetBotOutboundWebhookResponse
	30, // 43: chatto.api.v1.BotService.ReplaceBotOutboundWebhook:output_type -> chatto.api.v1.ReplaceBotOutboundWebhookResponse
	32, // 44: chatto.api.v1.BotService.DeleteBotOutboundWebhook:output_type -> chatto.api.v1.DeleteBotOutboundWebhookResponse
	6,  // 45: chatto.api.v1.BotService.ListBots:output_type -> chatto.api.v1.ListBotsResponse
	8,  // 46: chatto.api.v1.BotService.GetBot:output_type -> chatto.api.v1.GetBotResponse
	10, // 47: chatto.api.v1.BotService.BatchGetBots:output_type -> chatto.api.v1.BatchGetBotsResponse
	12, // 48: chatto.api.v1.BotService.CreateBot:output_type -> chatto.api.v1.CreateBotResponse
	14, // 49: chatto.api.v1.BotService.DeleteBot:output_type -> chatto.api.v1.DeleteBotResponse
	16, // 50: chatto.api.v1.BotService.CreateBotApiKey:output_type -> chatto.api.v1.CreateBotApiKeyResponse
	18, // 51: chatto.api.v1.BotService.RevokeBotApiKey:output_type -> chatto.api.v1.RevokeBotApiKeyResponse
	20, // 52: chatto.api.v1.BotService.CreateBotIncomingWebhook:output_type -> chatto.api.v1.CreateBotIncomingWebhookResponse
	22, // 53: chatto.api.v1.BotService.RevokeBotIncomingWebhook:output_type -> chatto.api.v1.RevokeBotIncomingWebhookResponse
	24, // 54: chatto.api.v1.BotService.ReassignBotOwner:output_type -> chatto.api.v1.ReassignBotOwnerResponse
	42, // [42:55] is the sub-list for method output_type
	29, // [29:42] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_bots_proto_init() }
func file_chatto_api_v1_bots_proto_init() {
	if File_chatto_api_v1_bots_proto != nil {
		return
	}
	file_chatto_api_v1_pagination_proto_init()
	file_chatto_api_v1_users_proto_init()
	file_chatto_api_v1_bots_proto_msgTypes[1].OneofWrappers = []any{}
	file_chatto_api_v1_bots_proto_msgTypes[2].OneofWrappers = []any{}
	file_chatto_api_v1_bots_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_bots_proto_rawDesc), len(file_chatto_api_v1_bots_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_bots_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_bots_proto_depIdxs,
		EnumInfos:         file_chatto_api_v1_bots_proto_enumTypes,
		MessageInfos:      file_chatto_api_v1_bots_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_bots_proto = out.File
	file_chatto_api_v1_bots_proto_goTypes = nil
	file_chatto_api_v1_bots_proto_depIdxs = nil
}
